### ISSUE TITLE
`mesh.unite()` causes segementaion fault

### ISSUE THREAD

**Issue by mbenkmann** [FreeCAD/FreeCAD#10462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Full version info

```shell
OS: Ubuntu 20.04.6 LTS
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Installed mods: 
  * Help 1.0.3
  * CubeMenu
```

### Subproject(s) affected?

None

### Problem description

PRECONDITION: Create a New document and add a Box.

**Works**: The following code works when pasted directly into the Python console. 

**Broken**: If saved in a macro `test.FCMacro` and executed via Macro/Macros.../Execute causes a SEGMENTATION FAULT.

The code worked fine in FreeCAD 0.20

```
import FreeCAD, Mesh, MeshPart

shape = FreeCAD.ActiveDocument.getObject("Box").Shape
mesh = Mesh.Mesh()
mesh2 = MeshPart.meshFromShape(Shape=shape, LinearDeflection=.1, AngularDeflection=3, Relative=False)
mesh = mesh.unite(mesh2)
```

This is the backtrace printed by FreeCAD:

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7ff482919090]
#1  0x7ff482c15c5b in std::ostream::sentry::sentry(std::ostream&) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libstdc++.so.6+0x13
#2  0x7ff482c16d62 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libstdc++.so.6+0x29
#3  0x7ff483bc445b in Base::Builder3D::Builder3D() from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADBase.so+0x4b
#4  0x7ff42d45d971 in MeshCore::SetOperations::SetOperations(MeshCore::MeshKernel const&, MeshCore::MeshKernel const&, MeshCore::MeshKernel&, MeshCore::SetOperations::OperationType, float) from /tmp/.mount_freecaMyqEOK/usr/lib/Mesh.so+0x111
#5  0x7ff42d5af6b2 in Mesh::MeshObject::unite(Mesh::MeshObject const&) const from /tmp/.mount_freecaMyqEOK/usr/lib/Mesh.so+0xa2
#6  0x7ff42d5bf3ad in Mesh::MeshPy::unite(_object*) from /tmp/.mount_freecaMyqEOK/usr/lib/Mesh.so+0x6d
#7  0x7ff42d5bf42e in Mesh::MeshPy::staticCallback_unite(_object*, _object*) from /tmp/.mount_freecaMyqEOK/usr/lib/Mesh.so+0x1e
#8  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(+0x148c18) [0x7ff484475c18]
#9  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(_PyObject_MakeTpCall+0x27b) [0x7ff48446ef0b]
#10  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(_PyEval_EvalFrameDefault+0x5453) [0x7ff48446adc3]
#11  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(+0x1de9b0) [0x7ff48450b9b0]
#12  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(PyEval_EvalCode+0x8c) [0x7ff48450b8fc]
#13  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(+0x20db43) [0x7ff48453ab43]
#14  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(+0x208efa) [0x7ff484535efa]
#15  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(+0x9d2fd) [0x7ff4843ca2fd]
#16  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libpython3.10.so.1.0(PyRun_FileExFlags+0x47) [0x7ff48444ab0b]
#17  0x7ff483c00c02 in Base::InterpreterSingleton::runFile(char const*, bool) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADBase.so+0xa2
#18  0x7ff484bb7193 in Gui::MacroManager::run(Gui::MacroManager::MacroType, char const*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x1e3
#19  0x7ff484bee767 in Gui::RecentMacrosAction::activateFile(int) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x237
#20  0x7ff484bfff98 in Gui::Command::_invoke(int, bool) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x2a8
#21  0x7ff484c00354 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x134
#22  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5(+0x1dff9b) [0x7ff482ed3f9b]
#23  0x7ff4837079c9 in QActionGroup::triggered(QAction*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0x2f
#24  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5(+0x1dfff5) [0x7ff482ed3ff5]
#25  0x7ff483705136 in QAction::triggered(bool) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0x32
#26  0x7ff483706c20 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0xc6
#27  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5(+0x259c3f) [0x7ff4837f9c3f]
#28  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5(+0x25eb0e) [0x7ff4837feb0e]
#29  0x7ff483734202 in QWidget::event(QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0x134
#30  0x7ff48370a087 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0xd9
#31  0x7ff48370e36d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0x663
#32  0x7ff484bb4339 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x99
#33  0x7ff482eb6a18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5+0x8e
#34  0x7ff48370d981 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0x283
#35  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5(+0x1a2e02) [0x7ff483742e02]
#36  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5(+0x1a4505) [0x7ff483744505]
#37  0x7ff48370a087 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Widgets.so.5+0xd9
#38  0x7ff484bb4339 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x99
#39  0x7ff482eb6a18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5+0x8e
#40  0x7ff48328456e in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Gui.so.5+0x6b6
#41  0x7ff483271091 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Gui.so.5+0x57
#42  /tmp/.mount_freecaMyqEOK/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5672c) [0x7ff47d52a72c]
#43  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x2ad) [0x7ff47f2d138d]
#44  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/./libglib-2.0.so.0(+0x5d649) [0x7ff47f2d1649]
#45  /tmp/.mount_freecaMyqEOK/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7ff47f2d16de]
#46  0x7ff482ee7d50 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5+0x5c
#47  0x7ff482eb45d8 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5+0x180
#48  0x7ff482eb87af in QCoreApplication::exec() from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libQt5Core.so.5+0x107
#49  0x7ff484b1abfe in Gui::Application::runApplication() from /tmp/.mount_freecaMyqEOK/usr/bin/../lib/libFreeCADGui.so+0x1e3e
#50  /tmp/.mount_freecaMyqEOK/usr/bin/freecad(+0x8608) [0x5589e8481608]
#51  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff4828fa083]
#52  /tmp/.mount_freecaMyqEOK/usr/bin/freecad(+0x8969) [0x5589e8481969]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
I've tried to reproduce the problem.

<details><summary>On Windows 10:</summary>


```ruby
19:00:26  Traceback (most recent call last):
  File "C:/Users/xtemp09/AppData/Roaming/FreeCAD/Macro/test.FCMacro", line 6, in <module>
    mesh = mesh.unite(mesh2)
<class 'OSError'>: Access violation
```

No crash.

```ruby
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
```

</details>


<details><summary>On Ubuntu 22.04:</summary>

```c++
* thread #1, name = 'FreeCAD', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x00007ffff1b3bf91 libstdc++.so.6`std::ostream::sentry::sentry(std::ostream&) + 33
    frame #1: 0x00007ffff1b3ca0c libstdc++.so.6`std::basic_ostream<char, std::char_traits<char>>& std::__ostream_insert<char, std::char_traits<char>>(std::basic_ostream<char, std::char_traits<char>>&, char const*, long) + 60
    frame #2: 0x00007ffff1b3cebb libstdc++.so.6`std::basic_ostream<char, std::char_traits<char>>& std::operator<<<std::char_traits<char>>(std::basic_ostream<char, std::char_traits<char>>&, char const*) + 43
    frame #3: 0x00007ffff3cba126 libFreeCADBase.so`Base::InventorBuilder::InventorBuilder(this=0x00007fffffffb180, output=0x00007fffffffb1a8) at Builder3D.cpp:918:15
    frame #4: 0x00007ffff3cba300 libFreeCADBase.so`Base::Builder3D::Builder3D(this=0x00007fffffffb180) at Builder3D.cpp:958:27
    frame #5: 0x00007fff335851a2 Mesh.so`MeshCore::SetOperations::SetOperations(this=0x00007fffffffb040, cutMesh1=0x00007fffffffafa0, cutMesh2=0x00007fffffffaff0, result=0x00007fffffffaf50, opType=Union, minDistanceToPoint=0.00000999999974) at SetOperations.cpp:53:41
    frame #6: 0x00007fff3375fc54 Mesh.so`Mesh::MeshObject::unite(this=0x00005555590bd850, mesh=0x000055555908e210) const at Mesh.cpp:1166:74
    frame #7: 0x00007fff3379951e Mesh.so`Mesh::MeshPy::unite(this=0x0000555555d53b80, args=0x00007fff7444c4c0) at MeshPyImp.cpp:411:53
    frame #8: 0x00007fff3378823c Mesh.so`Mesh::MeshPy::staticCallback_unite(self=0x0000555555d53b88, args=0x00007fff7444c4c0) at MeshPy.cpp:1067:58
    frame #9: 0x00007ffff3528008 libpython3.10.so.1.0`___lldb_unnamed_symbol3713 + 72
    frame #10: 0x00007ffff34dfadc libpython3.10.so.1.0`_PyObject_MakeTpCall + 140
    frame #11: 0x00007ffff347ba1c libpython3.10.so.1.0`_PyEval_EvalFrameDefault + 40380
    frame #12: 0x00007ffff35c23af libpython3.10.so.1.0`___lldb_unnamed_symbol4418 + 1647
    frame #13: 0x00007ffff35bd3de libpython3.10.so.1.0`PyEval_EvalCode + 190
    frame #14: 0x00007ffff360c4cd libpython3.10.so.1.0`___lldb_unnamed_symbol4668 + 157
    frame #15: 0x00007ffff360d698 libpython3.10.so.1.0`PyRun_FileExFlags + 184
    frame #16: 0x00007ffff3d0f59e libFreeCADBase.so`Base::InterpreterSingleton::runFile(this=0x0000555555629730, pxFileName="/home/fyr/.local/share/FreeCAD/Macro/test.FCMacro", local=true) at Interpreter.cpp:436:28
    frame #17: 0x00007ffff67ececa libFreeCADGui.so`Gui::MacroManager::run(this=0x0000555555d0f410, eType=File, sName="/home/fyr/.local/share/FreeCAD/Macro/test.FCMacro") at Macro.cpp:382:36
    frame #18: 0x00007ffff68380ae libFreeCADGui.so`Gui::RecentMacrosAction::activateFile(this=0x0000555556c478f0, id=0) at Action.cpp:1117:59
    frame #19: 0x00007ffff6889a53 libFreeCADGui.so`StdCmdRecentMacros::activated(this=0x0000555555d70580, iMsg=0) at CommandStd.cpp:194:31
    frame #20: 0x00007ffff68499a7 libFreeCADGui.so`Gui::Command::_invoke(this=0x0000555555d70580, id=0, disablelog=true) at Command.cpp:444:26
    frame #21: 0x00007ffff68496cf libFreeCADGui.so`Gui::Command::invoke(this=0x0000555555d70580, i=0, trigger=TriggerChildAction) at Command.cpp:408:12
    frame #22: 0x00007ffff6833c72 libFreeCADGui.so`Gui::ActionGroup::onActivated(this=0x0000555556c478f0, act=0x0000555556c5d4b0) at Action.cpp:595:22
    frame #23: 0x00007ffff6841b5e libFreeCADGui.so`QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QAction*>, void, void (Gui::ActionGroup::*)(QAction*)>::call(f=18 3b 83 f6 ff 7f 00 00 00 00 00 00 00 00 00 00, o=0x0000555556c478f0, arg=0x00007fffffffbfb0) at qobjectdefs_impl.h:152:20
    frame #24: 0x00007ffff6840f92 libFreeCADGui.so`void QtPrivate::FunctionPointer<void (Gui::ActionGroup::*)(QAction*)>::call<QtPrivate::List<QAction*>, void>(f=18 3b 83 f6 ff 7f 00 00 00 00 00 00 00 00 00 00, o=0x0000555556c478f0, arg=0x00007fffffffbfb0) at qobjectdefs_impl.h:185:95
    frame #25: 0x00007ffff68401af libFreeCADGui.so`QtPrivate::QSlotObject<void (Gui::ActionGroup::*)(QAction*), QtPrivate::List<QAction*>, void>::impl(which=1, this_=0x0000555556c5d3e0, r=0x0000555556c478f0, a=0x00007fffffffbfb0, ret=0x0000000000000000) at qobjectdefs_impl.h:418:49
    frame #26: 0x00007ffff20f1793 libQt5Core.so.5`___lldb_unnamed_symbol11821 + 1315
    frame #27: 0x00007ffff2d69b03 libQt5Widgets.so.5`QActionGroup::triggered(QAction*) + 67
    frame #28: 0x00007ffff20f17c8 libQt5Core.so.5`___lldb_unnamed_symbol11821 + 1368
    frame #29: 0x00007ffff2d65be6 libQt5Widgets.so.5`QAction::triggered(bool) + 70
    frame #30: 0x00007ffff2d688fc libQt5Widgets.so.5`QAction::activate(QAction::ActionEvent) + 172
    frame #31: 0x00007ffff2ef3142 libQt5Widgets.so.5`___lldb_unnamed_symbol16279 + 450
    frame #32: 0x00007ffff2efad39 libQt5Widgets.so.5`___lldb_unnamed_symbol16303 + 201
    frame #33: 0x00007ffff2daf4ee libQt5Widgets.so.5`QWidget::event(QEvent*) + 526
    frame #34: 0x00007ffff2d6c713 libQt5Widgets.so.5`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 131
    frame #35: 0x00007ffff2d74364 libQt5Widgets.so.5`QApplication::notify(QObject*, QEvent*) + 2692
    frame #36: 0x00007ffff67e5f70 libFreeCADGui.so`Gui::GUIApplication::notify(this=0x00007fffffffd2e0, receiver=0x0000555558f50830, event=0x00007fffffffc900) at GuiApplication.cpp:83:40
    frame #37: 0x00007ffff20b9e3a libQt5Core.so.5`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 314
    frame #38: 0x00007ffff2d72e47 libQt5Widgets.so.5`QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 439
    frame #39: 0x00007ffff2dc9843 libQt5Widgets.so.5`___lldb_unnamed_symbol14622 + 3555
    frame #40: 0x00007ffff2dcbfd5 libQt5Widgets.so.5`___lldb_unnamed_symbol14633 + 517
    frame #41: 0x00007ffff2d6c713 libQt5Widgets.so.5`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 131
    frame #42: 0x00007ffff67e5f70 libFreeCADGui.so`Gui::GUIApplication::notify(this=0x00007fffffffd2e0, receiver=0x00005555587600d0, event=0x00007fffffffce00) at GuiApplication.cpp:83:40
    frame #43: 0x00007ffff20b9e3a libQt5Core.so.5`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 314
    frame #44: 0x00007ffff2541307 libQt5Gui.so.5`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 1687
    frame #45: 0x00007ffff2516a2c libQt5Gui.so.5`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 172
    frame #46: 0x00007fffebac8d6e libQt5XcbQpa.so.5`___lldb_unnamed_symbol4098 + 30
    frame #47: 0x00007ffff151bd3b libglib-2.0.so.0`g_main_context_dispatch + 619
    frame #48: 0x00007ffff1571258 libglib-2.0.so.0`___lldb_unnamed_symbol2709 + 488
    frame #49: 0x00007ffff15193e3 libglib-2.0.so.0`g_main_context_iteration + 51
    frame #50: 0x00007ffff21130b8 libQt5Core.so.5`QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 104
    frame #51: 0x00007ffff20b875b libQt5Core.so.5`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 299
    frame #52: 0x00007ffff20c0cf4 libQt5Core.so.5`QCoreApplication::exec() + 148
    frame #53: 0x00007ffff6678b2d libFreeCADGui.so`Gui::Application::runApplication() at Application.cpp:2400:21
    frame #54: 0x000055555557ee32 FreeCAD`main(argc=1, argv=0x00007fffffffdf88) at MainGui.cpp:272:45
    frame #55: 0x00007ffff1629d90 libc.so.6`__libc_start_call_main(main=(FreeCAD`main at MainGui.cpp:99:1), argc=1, argv=0x00007fffffffdf88) at libc_start_call_main.h:58:16
    frame #56: 0x00007ffff1629e40 libc.so.6`__libc_start_main_impl(main=(FreeCAD`main at MainGui.cpp:99:1), argc=1, argv=0x00007fffffffdf88, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdf78) at libc-start.c:392:3
    frame #57: 0x000055555557e005 FreeCAD`_start + 37
```



```ruby
OS: Ubuntu 22.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.14555 (Git shallow)
Build type: Debug
Branch: master
Hash: 49e83787ef9412b80c46e41e424c3d61e92a82e4
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
```





</details>

The crash is present on Linux.
