### ISSUE TITLE
[Problem] Part HLR Projector Python API misses argument

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#10726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When applying HLR via the Part API, you will have to set the projector. However, there is a small bug in the Python wrapper code that prevents you to do so. To reproduce:

``` python
>>> origin = App.Vector(0, 0, 0)
>>> direction = App.Vector(0, 1, 0)
>>> xDirection = App.Vector(1, 0, 0)
>>> algo = Part.HLRBRep.Algo()
>>> algo.setProjector(origin, direction, xDirection)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
SystemError: more argument specifiers than keyword list entries (remaining format:'d')
>>> algo.setProjector(origin, direction, xDirection, 1.0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: function takes at most 3 arguments (4 given)
```

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34337 (Git)
Build type: Unknown
Branch: master
Hash: 4293c4a65b0e69975dcdbbf68c80d8019a4f850d
Python 3.11.3, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * osh-autodoc-workbench
[/code]
```

### Subproject(s) affected?

Part

### Anything else?

This [forum post](https://forum.freecad.org/viewtopic.php?p=699331#p699331) discusses the requested behavior. It is a very small problem, and I will submit a pull request that fixes this shortly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pieterhijma** [comment]
Yes, fully solved with PR #10727.
