### ISSUE TITLE
[Feature Request] Hydrostatic (non-uniform) pressure load in FEM

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#11645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hydrostatic pressure loads are commonly used in pressure vessel analyses. Unfortunately, CalculiX doesn't support them in the form of keywords (only as a dload.f subroutine) but there are ways to define them in preprocessors - internally, they could be converted to multiple *CLOAD or *DLOAD lines.

Support for general non-uniform pressure loads (e.g. defined by a user-specified equation) would be great but hydrostatic pressure will be sufficient for now.

Old forum discussion: https://forum.freecad.org/viewtopic.php?t=37631

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35274 (Git)
Build type: Release
Branch: main
Hash: dc063eabec61bffc72c92595c66a4649f25fe381
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jwharington** [comment]
@FEA-eng  I have some hooks established in a fork of FreeCAD to support this.  
It would be easy to set up a FeaturePython object to give pressure that linearly increases in a given direction, if that would satisfy your need.

**Comment by FEA-eng** [comment]
> [@FEA-eng](https://github.com/FEA-eng) I have some hooks established in a fork of FreeCAD to support this. It would be easy to set up a FeaturePython object to give pressure that linearly increases in a given direction, if that would satisfy your need.

Great, I hope it can be implemented into main in the next release cycle. This would be a very useful feature. For now, I think that linear variation from point to point (not necessarily from 0 to x) in a given direction (can be aligned with the global axes) would suffice.

**Comment by luzpaz** [comment]
@jwharington do you want to be assigned to this feature request ?

**Comment by jwharington** [comment]
Yes happy to

**Comment by jwharington** [comment]
Mostly done now, just a few user interface glitches to clean up, and a test+example to write.

https://github.com/jwharington/FreeCAD/tree/fem-hydrostaticpressure

**Comment by luzpaz** [comment]
Nice! Would be cool if you posted a screencast showing the feature in action

**Comment by jwharington** [comment]
https://github.com/user-attachments/assets/ae8cf825-8125-4d4d-b5ea-bf4280d88ecb

Here is an example, available in femexamples.

The hydrostatic force is oriented in the z direction; initially with no 'zero vertex' (a point at which the hydrostatic pressure is zero).   Note the deformation of the top and bottom skins is different due to the different positive pressure applied across these faces.

Later in the demo the zero vertex is set to the top of the box, so pressure is now applied increasingly in suction below the zero vertex.  Note the deformation increases away from the zero vertex and makes the shell bulge out.

**Comment by jwharington** [comment]
<img width="796" height="395" alt="Image" src="https://github.com/user-attachments/assets/034da476-1f26-41de-b1ae-6fe5e45db3ac" />

The tool to create the hydrostatic pressure load is adapted from the basic pressure icon.

**Comment by jwharington** [comment]
The same FP object can be used to define a pressure field using nearest neighbour or linear interpolation from supplied data.      I've changed the interface to now use a local coordinate system as this combines the function of the gravity direction as well as having a datum for zero pressure.

**Comment by FEA-eng** [comment]
@jwharington Did you modify the regular pressure load object too in your branch? I get these errors when I try to apply it to a shell:

```
16:21:38  Unexpected error when writing CalculiX input file: 'App.DocumentObject' object has no attribute 'Proxy'
16:21:38  Traceback (most recent call last):
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femtaskpanels/task_solver_ccxtools.py", line 317, in write_input_file_handler
16:21:38      self.fea.write_inp_file()
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femtools/ccxtools.py", line 385, in write_inp_file
16:21:38      self.inp_file_name = inp_writer.write_solver_input()
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femsolver/calculix/writer.py", line 206, in write_solver_input
16:21:38      self.write_constraints_meshsets(inpfile, self.member.cons_pressure, con_pressure)
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femsolver/writerbase.py", line 180, in write_constraints_meshsets
16:21:38      constraint_sets_loop_writing(f, femobjs, write_before, write_after)
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femsolver/writerbase.py", line 161, in constraint_sets_loop_writing
16:21:38      con_module.write_meshdata_constraint(the_file, femobj, the_obj, self)
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femsolver/calculix/write_constraint_pressure.py", line 80, in write_meshdata_constraint
16:21:38      if has_pressure_field(prs_obj):
16:21:38    File "/home/ubuntu/Documents/freecad_hydro/freecad-source/build/Mod/Fem/femsolver/calculix/write_constraint_pressure.py", line 50, in has_pressure_field
16:21:38      if hasattr(prs_obj.Proxy, "get_pressure_field"):
16:21:38  AttributeError: 'App.DocumentObject' object has no attribute 'Proxy'
```

The new hydrostatic pressure load looks good apart from the fact that it takes an indefinitely long time to write an input deck, even for medium-density meshes.

**Comment by jwharington** [comment]
Thanks @FEA-eng , I'll check re the errors you got.  I'm doing performance testing to see where the code is slow.  Some of it comes from some of the geometry queries --- a well known poor performance in FreeCAD to find the shapes corresponding to particular FEM mesh nodes.  I don't see quite why we can't use element groups from gmsh to bypass this performance hit.

I'll work up an example also, and post here, of the extended usage that allows for pressure distributions to be defined in a csv file.

**Comment by 3xxx** [comment]
@jwharington Really need this feature, looking forward to it being available soon.
