### ISSUE TITLE
[Problem] Segfault in Tests_run - missing `Py_Initialize();`

### ISSUE THREAD

**Issue by StefanBruens** [FreeCAD/FreeCAD#11878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

There is a `Py_Initialize();` missing here:  
https://github.com/FreeCAD/FreeCAD/blob/ef15fbfea6878ccfb0d83b5b45ba3047f4f98ac1/tests/src/App/StringHasher.cpp#L1008-L1010

Destruction of any FreeCAD PyObjectBase requires an initialized interpreter, otherwise `PyGILState_Ensure` crashes:

```
#0  0x00007ffff6e2dbd0 in ?? () from /lib64/libpython3.11.so.1.0
#1  0x00007ffff6e2db96 in PyThreadState_New () from /lib64/libpython3.11.so.1.0
#2  0x00007ffff6d2715b in ?? () from /lib64/libpython3.11.so.1.0
#3  0x00007ffff77502ec in Base::PyGILStateLocker::PyGILStateLocker (this=<optimized out>, this=<optimized out>) at /home/abuild/rpmbuild/BUILD/FreeCAD-0.22.0~g20240101.ef15fbfea6/src/Base/Interpreter.h:188
#4  Base::PyObjectBase::~PyObjectBase (this=<optimized out>, this=<optimized out>) at /home/abuild/rpmbuild/BUILD/FreeCAD-0.22.0~g20240101.ef15fbfea6/src/Base/PyObjectBase.cpp:78
#5  0x00007ffff7d98d49 in App::StringIDPy::~StringIDPy (this=<optimized out>, this=<optimized out>) at /home/abuild/rpmbuild/BUILD/FreeCAD-0.22.0~g20240101.ef15fbfea6/build/src/App/StringIDPy.cpp:425
#6  0x000055555569f304 in Py::Object::release (this=0x7fffffffdd10) at /home/abuild/rpmbuild/BUILD/FreeCAD-0.22.0~g20240101.ef15fbfea6/src/CXX/Python3/Objects.hxx:166
#7  Py::Object::~Object (this=<optimized out>, this=<optimized out>) at /home/abuild/rpmbuild/BUILD/FreeCAD-0.22.0~g20240101.ef15fbfea6/src/CXX/Python3/Objects.hxx:210
#8  StringIDRefTest_getPyObject_Test::TestBody (this=<optimized out>) at /home/abuild/rpmbuild/BUILD/FreeCAD-0.22.0~g20240101.ef15fbfea6/tests/src/App/StringHasher.cpp:1020
#9  0x00007ffff7f9078c in ?? () from /lib64/libgtest.so.1.12.1
#10 0x00007ffff7f7de4e in testing::Test::Run() () from /lib64/libgtest.so.1.12.1
```

To reproduce, just run  
`gdb  -ex run --batch  --args tests/Tests_run "--gtest_filter=StringIDRefTest.getPyObject"`

### Full version info

```shell
0.22.0 ef15fbfea6878ccfb0d83b5b45ba3047f4f98ac1
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syres916** [comment]
@StefanBruens if you're confident that you've established a fix, could you please raise a Pull Request and add Fixes https://github.com/FreeCAD/FreeCAD/issues/11878 to the text. The maintainers can then evaluate it and if they are happy will merge the PR.
