### ISSUE TITLE
Crash with select preferencies menu.

### ISSUE THREAD

**Issue by joneblade2024** [FreeCAD/FreeCAD#12386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Manjaro linux 2024. Fully updated.Freecad installed from oficial repo.
Also i install AppImage variant, and  error saved. Disabled all addons and clear cache, do not result.

```
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3e710) [0x7f64d985c710]
#1  /usr/lib/libpython3.11.so.1.0(PyDict_GetItem+0x152) [0x7f64db5da4d2]
#2  /usr/lib/libpython3.11.so.1.0(PyDict_GetItemString+0x2c) [0x7f64db59143d]
#3  0x7f64dc8ed72e in Gui::PythonCommand::isChecked() const from /usr/lib/freecad/lib/libFreeCADGui.so+0x1e
#4  0x7f64dc8f409d in Gui::PythonCommand::createAction() from /usr/lib/freecad/lib/libFreeCADGui.so+0x13d
#5  0x7f64dc8eb8b4 in Gui::Command::initAction() from /usr/lib/freecad/lib/libFreeCADGui.so+0x54
#6  0x7f64dca0216c in Gui::Dialog::DlgCustomKeyboardImp::DlgCustomKeyboardImp(QWidget*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x126c
#7  /usr/lib/freecad/lib/libFreeCADGui.so(+0x4c4793) [0x7f64dc8c4793]
#8  0x7f64dccc0248 in Gui::WidgetFactoryInst::createWidget(char const*, QWidget*) const from /usr/lib/freecad/lib/libFreeCADGui.so+0x18
#9  0x7f64dc9ef48b in Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp(QWidget*, QFlags<Qt::WindowType>) from /usr/lib/freecad/lib/libFreeCADGui.so+0x31b
#10  0x7f64dc91a6d2 in StdCmdDlgCustomize::activated(int) from /usr/lib/freecad/lib/libFreeCADGui.so+0xb2
#11  0x7f64dc8eb13f in Gui::Command::_invoke(int, bool) from /usr/lib/freecad/lib/libFreeCADGui.so+0x1ef
#12  0x7f64dc8eb4f7 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /usr/lib/freecad/lib/libFreeCADGui.so+0x137
#13  /usr/lib/libQt5Core.so.5(+0x2d0e27) [0x7f64da0d0e27]
#14  0x7f64dad6bbb7 in QAction::triggered(bool) from /usr/lib/libQt5Widgets.so.5+0x47
#15  0x7f64dad7160b in QAction::activate(QAction::ActionEvent) from /usr/lib/libQt5Widgets.so.5+0xbb
#16  /usr/lib/libQt5Widgets.so.5(+0x2f437b) [0x7f64daef437b]
#17  /usr/lib/libQt5Widgets.so.5(+0x2f449d) [0x7f64daef449d]
#18  0x7f64dadaf1a1 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8d1
#19  0x7f64dad788ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8f
#20  0x7f64dad7ddaf in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x10ff
#21  0x7f64dc8b6419 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#22  0x7f64da09bef8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#23  0x7f64dad7c0ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /usr/lib/libQt5Widgets.so.5+0x1ca
#24  /usr/lib/libQt5Widgets.so.5(+0x1cd9c4) [0x7f64dadcd9c4]
#25  /usr/lib/libQt5Widgets.so.5(+0x1cec17) [0x7f64dadcec17]
#26  0x7f64dad788ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8f
#27  0x7f64dc8b6419 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#28  0x7f64da09bef8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#29  0x7f64da54196c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/libQt5Gui.so.5+0x6ec
#30  0x7f64da52a6f5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xb5
#31  /usr/lib/libQt5XcbQpa.so.5(+0x65560) [0x7f64d3c7d560]
#32  /usr/lib/libglib-2.0.so.0(+0x59f69) [0x7f64d830df69]
#33  /usr/lib/libglib-2.0.so.0(+0xb8367) [0x7f64d836c367]
#34  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x7f64d830c162]
#35  0x7f64da0ead0c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x6c
#36  0x7f64da09ac04 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x134
#37  0x7f64da09c0a3 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x93
#38  0x7f64dc8271cb in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x1c5b
#39  freecad(+0x4e13) [0x5638a9c8fe13]
#40  /usr/lib/libc.so.6(+0x27cd0) [0x7f64d9845cd0]
#41  /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f64d9845d8a]
#42  freecad(+0x5fd5) [0x5638a9c90fd5]
```

### Full version info

```shell
[code]
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.11.6, Qt 5.15.11, Coin 4.0.1, Vtk 9.3.0, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Installed mods: 
  * Lithophane
  * ImportNURBS 1.1.0
  * GDML.backup1698872055.6411848 2.0.0 (Disabled)
  * AnimationFreeCAD 1.0.0
  * Help 1.0.3
  * FEM_FrontISTR 0.1.0
  * workfeature
  * CADExchanger (Disabled)
  * Render 2024.1.23
  * 3D_Printing_Tools
  * offline-documentation 1.0.0-alpha
  * SteelColumn
  * pyOpToolsWorkbench 0.0.1
  * Estimate 0.1.2
  * CfdOF 1.25.1
  * DynamicData 2.60.0
  * Trails 2022.1.0
  * BCFPlugin 1.0.0
  * woodworking 0.21.2.33771
  * CurvedShapes 1.0.5
  * DesignSPHysics 0.7.0(15-09-2023)
  * Pyramids-and-Polyhedrons
  * BIMBots
  * Marz 0.0.27-alpha
  * fasteners.backup1698872050.9961174 0.4.68 (Disabled)
  * BIM 2021.12.0
  * pcb 6.2023.1
  * ExplodedAssembly
  * InventorLoader 1.4.0 (Disabled)
  * Ship 2022.4.11
  * symbols_library
  * MakerWorkbench 1.0.1
  * FEMbyGEN 2.1.0
  * ose-piping
  * MnesarcoUtils 0.2.5
  * EM
  * A2plus 0.4.62
  * LCInterlocking
  * bimtester
  * Nodes 0.1.36
  * Manipulator 1.5.7
  * TitleBlock 0.5.2
  * AirPlaneDesign 0.4.0
  * GDML.backup1707391506.8205104 2.0.0 (Disabled)
  * Silk 0.1.5
  * Defeaturing 1.2.2
  * MOOC 2022.4.21
  * yaml-workspace 0.1.2
  * PieMenu 1.2.7 (Disabled)
  * OSE3dPrinter 0.1.0 (Disabled)
  * CadbaseLibrary 0.3.0
  * Reporting
  * Plot 2022.4.17 (Disabled)
  * Part-o-magic 1.1.0
  * POV-Ray-Rendering
  * Assembly4 0.50.7
  * Design456 0.0.1
  * FeedsAndSpeeds 0.5.0
  * retr3d
  * slic3r-tools
  * OpticsWorkbench 1.0.11
  * Rocket 3.3.0
  * 3DfindIT 1.2.0
  * fasteners 0.5.10
  * Cfd (Disabled)
  * ArchTextures
  * cadquery_module (Disabled)
  * parts_library
  * freecad.gears 1.0.0
  * pyrate
  * Alternate_OpenSCAD 1.0.0
  * lattice2 1.0.0
  * ThreadProfile 1.89.0
  * Curves 0.6.23
  * kicadStepUpMod 10.23.1
  * dxf-library
  * toSketch 1.0.1
  * WB_Organizer 2024.1.29 (Disabled)
  * Beltrami 1.0.8-alpha
  * frame 0.1.1
  * pivy_trackers
  * BillOfMaterials 0.0.3
  * SlopedPlanesMacro
  * Assembly3 0.12.2
  * SearchBar 1.0.2 (Disabled)
  * kerkythea
  * Fcmcua 1.0.0 (Disabled)
  * sheetmetal 0.4.1
  * NikraDAP 2.0.0
  * Reinforcement
  * OSAFE 2022.5.29
  * workfeature-macro
  * nurbs
  * GDML 2.0.0
  * MeshRemodel 1.9.22
  * WebTools 1.0.0
  * dodo 1.0.0
  * QuickMeasure 2022.10.28
  * Movie 2023.6.10
  * boltsfc 2022.11.5
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
please provide clear reproduction steps...

**Comment by joneblade2024** [comment]
Open FreeCad>Instruments>Preferencies>CRASH!!! or right clicked to panel and select Preferencies>CRASH!!!

**Comment by luzpaz** [comment]
Some of those addons are deprecated. I wonder if they are introducing any instability ?

**Comment by maxwxyz** [comment]
can you try with a fresh install without addons or also with the dev builds?

**Comment by joneblade2024** [comment]
I wrote that I tried deleting the entire addons folder and cache. I also completely reinstalled FreeCAD. And tried the AppImage version

**Comment by joneblade2024** [comment]
Dev build do not interesting

**Comment by joneblade2024** [comment]
Forgot to mention. Toolbar location settings are constantly being reset. I have already begun to come to terms with this.

**Comment by joneblade2024** [comment]
Python dependencies for add-ons are also not updated. Writes a new pip security policy. Use virtual space or install packages using the system manager.

**Comment by maxwxyz** [comment]
I don't know how to reproduce this. Could you try deleting your user.cfg and try again?

**Comment by joneblade2024** [comment]
I found two user.cfg, one in /home/freecad, the second in /home/local/share/FreeCAD. I'll try.

**Comment by adrianinsaval** [comment]
user.cfg is at ~/.config/FreeCAD addons are at ~/.local/share/FreeCAD please clear both directories and try again

**Comment by adrianinsaval** [comment]
Is the problem still present if you change language?

**Comment by joneblade2024** [comment]
Thanks for the help! It turned out like this... The /home/user/freecad folder contained user.cfg, but also the Mod folder. Apparently from an old version of FreeCad or from an AppImage version. I deleted it and everything is OK. Then I began setting up workbenches, simultaneously checking the stability after each one. And Oops, after GDML this problem appears.

**Comment by joneblade2024** [comment]
Solved
