### ISSUE TITLE
[Problem] Executing Macro throws `ModuleNotFoundError - No module names gui_facebinders` (solution: `Application::sAddCommand` needs be fixed)

### ISSUE THREAD

**Issue by RandomLegend** [FreeCAD/FreeCAD#12604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I wanted to record a macro that creates a facebinder via the draft workbench on a selected face. Using either the gui buttons or using shortcuts, i can create the facebinder without issues.

Executing the macro however throws the following error:

```
12:55:12  pyException: Traceback (most recent call last):
  File "/home/frank-garuda/.local/share/Ondsel/Macro/Facebind.FCMacro", line 6, in <module>
    import gui_facebinders
  File "/tmp/.mount_Ondsell3G3CT/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'gui_facebinders'
```

Tested this with the weekly build i currently use, the stable version and the repackaged Ondsel version. All behave the same.

### Full version info

```shell
OS: Garuda Linux (Hyprland/garuda-hyprland)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35594 (Git) AppImage
Build type: Release
Branch: main
Hash: 49e7bba9c7390b11e6cc9acebd10cc1568ec8869
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can you provide the macro for testing purposes ?

**Comment by RandomLegend** [comment]
```python
# -*- coding: utf-8 -*-

# Macro Begin: /home/frank-garuda/.local/share/FreeCAD/Macro/Test.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import PartDesignGui
import gui_facebinders
import Draft

# Gui.runCommand('Std_DlgMacroRecord',0)
# Gui.Selection.addSelection('Unnamed','Body','Pad.Face6',21.6569,8.72649,10)
### Begin command Std_Workbench
# Gui.activateWorkbench("DraftWorkbench")
### End command Std_Workbench
### Begin command Draft_Facebinder
sels = FreeCADGui.Selection.getSelectionEx('', 0)
facebinder = Draft.make_facebinder(sels)
Draft.autogroup(facebinder)
FreeCAD.ActiveDocument.recompute()
### End command Draft_Facebinder
# Gui.Selection.addSelection('Unnamed','Facebinder')
# Macro End: /home/frank-garuda/.local/share/FreeCAD/Macro/Test.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++

```

This was generated via Macro Recording and resulted in this error:

```
15:51:31  pyException: Traceback (most recent call last):
  File "/home/frank-garuda/.local/share/FreeCAD/Macro/Test.FCMacro", line 6, in <module>
    import gui_facebinders
  File "/tmp/.mount_FreeCAwwOnnt/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'gui_facebinders'

```

___

Deleting facebinder_gui in the import section resolves the issue and executes the macro as intended.

**Comment by wwmayer** [comment]
The correct import statement should be: `from draftguitools import gui_facebinders` But I have no idea where the line `import gui_facebinders`. 

Since you use a fork of FreeCAD the problem may come from this fork.

**Comment by luzpaz** [comment]
@RandomLegend please respond.

**Comment by RandomLegend** [comment]
Sorry guys, had much going on

So i fixed it:

This is the correct script now:

```
import FreeCAD
import PartDesignGui
import Draft
import Part
import PartDesign

# Gui.runCommand('Std_DlgMacroRecord',0)
### Begin command Part_Loft
from FreeCAD import Base

# Get document name
doc_name = App.activeDocument().Label

# Gui.runCommand('Std_DlgMacroRecord',0)
### Begin command Std_Workbench
# Gui.activateWorkbench("DraftWorkbench")
### End command Std_Workbench
### Begin command Draft_Facebinder
sels = FreeCADGui.Selection.getSelectionEx('', 0)
facebinder1 = Draft.make_facebinder(sels[0])
facebinder1.Label = "Facebinder_Loft_1"
facebinder2 = Draft.make_facebinder(sels[1])
facebinder2.Label = "Facebinder_Loft_2"
Draft.autogroup(facebinder1)
Draft.autogroup(facebinder2)
FreeCAD.ActiveDocument.recompute()
App.getDocument(doc_name).addObject('Part::Loft','Loft')
App.getDocument(doc_name).ActiveObject.Sections=[facebinder1, facebinder2, ]
App.getDocument(doc_name).ActiveObject.Solid=True
App.getDocument(doc_name).ActiveObject.Ruled=False
App.getDocument(doc_name).ActiveObject.Closed=False
```

So unlike @wwmayer proposed it wasn't needed to do from `draftguitools import gui_facebinders`. The `import gui_facebinders` came from the Macro recording.

Also @wwmayer yes i posted the results from the fork (ondsel) but i can replicate this macro identically on the original freecad version.

**Comment by wwmayer** [comment]
> but i can replicate this macro identically on the original freecad version.

How?

**Comment by RandomLegend** [comment]
1. Start Macro Record
2. Select face of body
3. Switch to "Draft" Workspace
4. Create facebinder on the selected face
5. Stop Macro Recording

It created the import gui_facebinders on the stable version and the 0.22.dev version that i also had installed.

**Comment by wwmayer** [comment]
Confirmed! Thanks.

I will reopen the bug report because recorded macro code must be correct.

**Comment by wwmayer** [comment]
The function Application::sAddCommand needs be fixed to determine the module and package names.
E.g. for the registered face binder command it determines the module name "gui_facebinders" without the package name "draftguitools" and passes it to the PythonCommand/PythonGroupCommand with setAppModuleName.

This app module name is written to the recorded macro.

**Comment by luzpaz** [comment]
Can this ticket now be closed @wwmayer ?

**Comment by FEA-eng** [comment]
Still relevant

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/16 20:38:23
Build type: Release
Branch: main
Hash: bac49e465908071e7400a547eb813bc5017ae7dc
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

**Comment by maxwxyz** [comment]
There is a fix for this issue https://codeberg.org/wwmayer/FreeCAD11/commit/bd279c38a76bd7cf55df5e5168d6addddd22586d

**Comment by luzpaz** [comment]
> The function Application::sAddCommand needs be fixed to determine the module and package names. E.g. for the registered face binder command it determines the module name "gui_facebinders" without the package name "draftguitools" and passes it to the PythonCommand/PythonGroupCommand with setAppModuleName.
> 
> This app module name is written to the recorded macro.

This is the proposed solution

**Comment by FEA-eng** [comment]
Still relevant

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20260602 (Git shallow)
Build date: 2026/06/02 19:21:10
Build type: Release
Branch: (HEAD detached at 07de249ec)
Hash: 07de249ec749d3fba6710c78da8bca7c66243347
Python 3.11.15, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL) [ OS: Polish/Poland (pl_PL) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/113.268/1.25
```

**Comment by luzpaz** [comment]
@maxwxyz codeberg link in https://github.com/FreeCAD/FreeCAD/issues/12604#issuecomment-3475938854 is broken
