### ISSUE TITLE
TechDraw TaskFillTemplateFields.py error

### ISSUE THREAD

**Issue by prrvchr** [FreeCAD/FreeCAD#12910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi,

when I use TechDraw for importing an Arch Section Plan I have the following message:

```
Traceback (most recent call last):                                                                              
  File "/usr/share/freecad-daily/Mod/TechDraw/TechDrawTools/CommandFillTemplateFields.py", line 59, in Activated
    TechDrawTools.TaskFillTemplateFields()                                                                      
  File "/usr/share/freecad-daily/Mod/TechDraw/TechDrawTools/TaskFillTemplateFields.py", line 166, in __init__   
    if str(key).lower() in ScaleChkLst and projgrp_view:                                                        
                                                                                                                
local variable 'projgrp_view' referenced before assignment
```

Indeed if we look in the [source code](https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/TechDraw/TechDrawTools/TaskFillTemplateFields.py#L166) the variable **projgrp_view** can be used without being initialized.

As the correction does not seem too complicated I will propose a PR.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (LXQt/Lubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36340 (Git)
Build type: Release
Branch: main
Hash: addf08ce6b0df264a47e836e799b6756626f146e
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * parts_library
  * Material
  * BIM 2021.12.0
  * Render 2023.8.18
  * Help 1.0.3
  * Blender-Importer
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prrvchr** [comment]
Ok PR is [here](https://github.com/FreeCAD/FreeCAD/pull/12911)
