### ISSUE TITLE
Material editor can't be opened from FEM_MaterialSolid and FEM_MaterialFluid

### ISSUE THREAD

**Issue by FEA-eng** [FreeCAD/FreeCAD#12949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the recent weekly builds, clicking the "use FreeCAD material editor" button in FEM_MaterialSolid or FEM_MaterialFluid results in the following error:

```
12:20:24  Traceback (most recent call last):
12:20:24    File "E:\Program Files\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Fem\femtaskpanels\task_material_common.py", line 352, in edit_material
12:20:24      new_material_params = MaterialEditor.editMaterial(card_path=self.card_path,
12:20:24    File "E:\Program Files\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\MaterialEditor.py", line 966, in editMaterial
12:20:24      editor = MaterialEditor(material=material, card_path=card_path, category=category)
12:20:24    File "E:\Program Files\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\MaterialEditor.py", line 72, in __init__
12:20:24      self.widget = FreeCADGui.PySideUic.loadUi(filePath + "Resources" + os.sep + "ui" + os.sep + "materials-editor.ui")
12:20:24    File "<string>", line 4, in <module>
12:20:24  RuntimeError: Cannot open file
```

However, the FEM_MaterialEditor button works.

@davesrocketshop 

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
> However, the FEM_MaterialEditor button works.

Actually, it doesn't work either on another computer (same error).

**Comment by FEA-eng** [comment]
> @FEA-eng For the editor, I'm not able to reproduce this problem so I have no idea what's going on. It would help if I could see the string path for the .ui file, so could you add this line of code at line 72 before the call to loadUi and report the output:

It showed this (on a different computer):

```
13:37:35  E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\Resources\ui\materials-editor.ui
```

The file really exists.

> Loading Materials first solves that. After that you may get the same error affecting the dialogs

I get this both when trying to open the editor without loading the Material workbench and after loading it:

```
13:44:13  Running the Python command 'FEM_MaterialEditor' failed:
Traceback (most recent call last):
  File "E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Fem\femcommands\commands.py", line 637, in Activated
    FreeCADGui.doCommand("MaterialEditor.openEditor()")
  File "<string>", line 1, in <module>
  File "E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\MaterialEditor.py", line 951, in openEditor
    editor = MaterialEditor(obj, prop)
  File "E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\MaterialEditor.py", line 73, in __init__
    self.widget = FreeCADGui.PySideUic.loadUi(filePath + "Resources" + os.sep + "ui" + os.sep + "materials-editor.ui")
  File "<string>", line 4, in <module>

Cannot open file
```

**Comment by davesrocketshop** [comment]
I'm stumped. Everything looks correct.

Permissions issue? Can you open the file using Notepad or similar?

(The requirement to load the Materials WB is already being addressed elsewhere)

**Comment by FEA-eng** [comment]
> Permissions issue? 

I don't think so, I keep weekly builds on E drive which has no access restrictions.

> Can you open the file using Notepad or similar?

Yes, I can. But I've just noticed one thing. The path reported in FreeCAD is:

`E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\Resources\ui\materials-editor.ui`

while the `materials-editor.ui` file is actually here on my computer:

`E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\materials-editor.ui`

The `Resources` catalog only has the `icons` folder, nothing more.

**Comment by davesrocketshop** [comment]
> > Permissions issue?
> 
> I don't think so, I keep weekly builds on E drive which has no access restrictions.
> 
> > Can you open the file using Notepad or similar?
> 
> Yes, I can. But I've just noticed one thing. The path reported in FreeCAD is:
> 
> `E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\Resources\ui\materials-editor.ui`
> 
> while the `materials-editor.ui` file is actually here on my computer:
> 
> `E:\FreeCAD_weekly-builds-36391-2024-03-11-conda-Windows-x86_64-py310\Mod\Material\materials-editor.ui`
> 
> The `Resources` catalog only has the `icons` folder, nothing more.

Ok, this is the problem. It's an issue with the installer that I don't see in the development branch. This I can fix.

**Comment by RiccaDS** [comment]
I have the same problem

**Comment by RiccaDS** [comment]
Apparently seems to be present only in the developement versions

**Comment by davesrocketshop** [comment]
Somehow in the packaging process the files get moved. Not yet sure how or why. They're placed exactly where I wanted them in the build.

**Comment by wwmayer** [comment]
The relatives path names must not change when running the install target of a build and that's exactly what happens here. In the past the file materials-editor.ui was copied to Mod/Material of the build directory and the install target also copied it to Mod/Material of the install directory.

This has changed with 6624fa3 where materials-editor.ui is copied to Resources/ui/materials-editor.ui but the install target still copies it to Mod/Material. MaterialEditor.py was adjusted to load the ui file from the new location but this broke it for the installed version.

**Comment by wwmayer** [comment]
https://github.com/FreeCAD/FreeCAD/pull/13255 fixes this and a few other problems.
