### ISSUE TITLE
Crash when selecting a path in pipe feature of PartDesign

### ISSUE THREAD

**Issue by NomAnor** [FreeCAD/FreeCAD#13001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

1. Select the profile sketch for a pipe
2. Create pipe
3. Click the "Object" button in the task gui
4. Select the path sketch

FreeCAD crashes with the following backtrace:
```
AdditivePipe: No spine linked
AdditivePipe: No spine linked
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3c770) [0x718c886f2770]
#1  0x718c8e35ffb7 in Gui::DocumentObjectItem::setCheckState(bool) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x81
#2  0x718c8e3588ce in Gui::DocumentItem::updateItemSelection(Gui::DocumentObjectItem*) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x562
#3  0x718c8e35814e in Gui::DocumentItem::clearSelection(Gui::DocumentObjectItem*) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x10c
#4  0x718c8e34e9dc in Gui::TreeWidget::onItemSelectionChanged() from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x4ee
#5  0x718c8e385e72 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::TreeWidget::*)()>::call(void (Gui::TreeWidget::*)(), Gui::TreeWidget*, void**) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x7a
#6  0x718c8e37e1c1 in void QtPrivate::FunctionPointer<void (Gui::TreeWidget::*)()>::call<QtPrivate::List<>, void>(void (Gui::TreeWidget::*)(), Gui::TreeWidget*, void**) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x42
#7  0x718c8e374fa9 in QtPrivate::QSlotObject<void (Gui::TreeWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x80
#8  /usr/lib/libQt5Core.so.5(+0x2c8e27) [0x718c89086e27]
#9  /usr/lib/libQt5Widgets.so.5(+0x440954) [0x718c89d9b954]
#10  /usr/lib/libQt5Core.so.5(+0x2c8fe3) [0x718c89086fe3]
#11  0x718c8901e64c in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) from /usr/lib/libQt5Core.so.5+0x3c
#12  0x718c8901c3df in QItemSelectionModel::select(QItemSelection const&, QFlags<QItemSelectionModel::SelectionFlag>) from /usr/lib/libQt5Core.so.5+0x3ff
#13  0x718c89d93a45 in QTreeViewPrivate::select(QModelIndex const&, QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) from /usr/lib/libQt5Widgets.so.5+0x915
#14  0x718c89d87e62 in QTreeView::setSelection(QRect const&, QFlags<QItemSelectionModel::SelectionFlag>) from /usr/lib/libQt5Widgets.so.5+0x182
#15  0x718c89d17f96 in QAbstractItemView::mousePressEvent(QMouseEvent*) from /usr/lib/libQt5Widgets.so.5+0x306
#16  0x718c8e33f557 in Gui::TreeWidget::mousePressEvent(QMouseEvent*) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x33
#17  0x718c89ae94e9 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0xc19
#18  0x718c89b97a83 in QFrame::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x23
#19  0x718c8904eed2 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x92
#20  0x718c89ab28ef in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7f
#21  0x718c89ab7daf in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x10ff
#22  0x718c8e031b82 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x114
#23  0x718c89051ef8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#24  0x718c89ab60ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /usr/lib/libQt5Widgets.so.5+0x1ca
#25  /usr/lib/libQt5Widgets.so.5(+0x1abec5) [0x718c89b06ec5]
#26  /usr/lib/libQt5Widgets.so.5(+0x1adc17) [0x718c89b08c17]
#27  0x718c89ab28ff in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8f
#28  0x718c8e031b82 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x114
#29  0x718c89051ef8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#30  0x718c8941f94c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/libQt5Gui.so.5+0x6ec
#31  0x718c894086d5 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xb5
#32  /usr/lib/libQt5XcbQpa.so.5(+0x5f540) [0x718c82d0f540]
#33  /usr/lib/libglib-2.0.so.0(+0x59f69) [0x718c84f5cf69]
#34  /usr/lib/libglib-2.0.so.0(+0xb83a7) [0x718c84fbb3a7]
#35  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x718c84f5b162]
#36  0x718c890a0d0c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x6c
#37  0x718c89050c04 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x134
#38  0x718c890520a3 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x93
#39  /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so(+0x118a9fd) [0x718c8de9a9fd]
#40  /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so(+0x118ad22) [0x718c8de9ad22]
#41  0x718c8de9b0ec in Gui::Application::runApplication() from /home/xxxx/src/FreeCAD/main/build/debug/lib/libFreeCADGui.so+0x240
#42  build/debug/bin/FreeCAD(+0x265ac) [0x6453b16875ac]
#43  /usr/lib/libc.so.6(+0x25cd0) [0x718c886dbcd0]
#44  /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x718c886dbd8a]
#45  build/debug/bin/FreeCAD(+0x25755) [0x6453b1686755]
```

Selecting both sketches before creating the pipe does not crash. Also selecting segment with the "Add edge" button does not crash.
This also occures with loft.

### Full version info

```shell
OS: Arch Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36392 (Git)
Build type: Debug
Branch: main
Hash: 9140327832b94ea4325dfcf185e2e68659875e47
Python 3.11.8, Qt 5.15.12, Coin 4.0.2, Vtk 9.3.0, OCC 7.3.0
Locale: German/Germany (de_DE)
Installed mods: 
  * Manipulator 1.5.7
  * ThreadProfile 1.84.0
  * DynamicData 2.60.0
  * lattice2 1.0.0
  * 3D_Printing_Tools
  * freecad.gears 1.0.0
  * Assembly3 0.11.3
  * QuickMeasure 2022.10.28
  * fasteners 0.4.21
```

### Subproject(s) affected?

PartDesign

### Anything else?
```git bisect``` leads me to commit 677cadee5ec6e85ada4f7bd83747c71dbb629f3f from @FlachyJoe.

Removing the ViewProvider changes, fixed it. If I uncomment
https://github.com/FreeCAD/FreeCAD/blob/677cadee5ec6e85ada4f7bd83747c71dbb629f3f/src/Gui/ViewProviderSuppressibleExtension.cpp#L60
the crash does not occur.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FlachyJoe** [comment]
I am on this, the signal is certainly triggered after the deletion of an object but I am not aware of how it works internally. If someone can help me to install a guard I'd be grateful.
