### ISSUE TITLE
CAM_Sanity failure

### ISSUE THREAD

**Issue by ShamanTcler** [FreeCAD/FreeCAD#13028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have a test model of a GottShall Block (included) it fails the sanity test with this error:

```
10:04:40  Running the Python command 'CAM_Sanity' failed:
Traceback (most recent call last):
  File "C:\FreeCadBeta\Mod\CAM\Path\Main\Gui\Sanity.py", line 156, in Activated
    html = self.__report(data, obj)
  File "C:\FreeCadBeta\Mod\CAM\Path\Main\Gui\Sanity.py", line 822, in __report
    for o in value["ops"]:

('ops',)
```
[GottshallBlockSimplePath.zip](https://github.com/FreeCAD/FreeCAD/files/14637466/GottshallBlockSimplePath.zip)

Also any GCode simulation just crashes ... not only lead in / out but other operations too

### Full version info

```shell
OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36391 (Git)
Build type: Release
Branch: main
Hash: 52fffaf50ef8facea2ecfde23d6f1a7d3ad3d80c
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Curves 0.6.29
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
I would add that _CAM Simulator_ stops with these messages:



```ruby
19:04:45  Traceback (most recent call last):
19:04:45    File "/home/xtemp09/Downloads/FreeCAD/build/Mod/CAM/Path/Main/Gui/Simulator.py", line 397, in PerformCut
19:04:45      self.PerformCutVoxel()
19:04:45    File "/home/xtemp09/Downloads/FreeCAD/build/Mod/CAM/Path/Main/Gui/Simulator.py", line 343, in PerformCutVoxel
19:04:45      dz = (cmd.z - self.curpos.Base.z) / n
19:04:45  TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

Though I have not observed crash with this file.


<details>

```ruby
OS: Ubuntu 22.04.3 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36487 (Git)
Build type: Debug
Branch: main
Hash: f5baef888c25937026ee50001a4fe4293a9f11ee
Python 3.10.12, Qt 5.15.12, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
```


</details>
