### ISSUE TITLE
The weekly build won't even open. It crashes as soon as I launch it.

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD#13035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The weekly build won't even open. It crashes as soon as I launch it.

```
~/Applications …
➜ ./FreeCAD_weekly-builds-36480-2024-03-18-conda-Linux-x86_64-py311.AppImage 
FreeCAD 0.22.0, Libs: 0.22.0devR36480 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2024
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Sheet Metal workbench loaded
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x42990) [0x7d49d5842990]
#1  0x7d49d8e40913 in Gui::MDIView::buildWindowTitle() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0x23
#2  0x7d49d8dc9eec in Gui::MainWindow::_updateActions() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0x6c
#3  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5(+0x2e9214) [0x7d49d5ee9214]
#4  0x7d49d5eecc8a in QTimer::timeout(QTimer::QPrivateSignal) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5+0x2a
#5  0x7d49d5eddfad in QObject::event(QEvent*) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5+0x7d
#6  0x7d49d6d7035e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#7  0x7d49d8927399 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0x99
#8  0x7d49d5eb3fc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5+0x108
#9  0x7d49d5f078f1 in QTimerInfoList::activateTimers() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5+0x381
#10  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5(+0x3080c4) [0x7d49d5f080c4]
#11  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x7d49d4510ad7]
#12  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x7d49d4513ac7]
#13  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7d49d45140ce]
#14  0x7d49d5f083d6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libQt5Core.so.5+0x66
#15  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so(+0xa02922) [0x7d49d8e02922]
#16  0x7d49d74f8555 in Base::ConsoleSingleton::notifyPrivate(Base::LogStyle, Base::IntendedRecipient, Base::ContentType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADBase.so+0x75
#17  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADBase.so(+0x108a39) [0x7d49d7508a39]
#18  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADBase.so(+0xf433a) [0x7d49d74f433a]
#19  0x7d49d74f498a in Base::ConsoleSingleton::sPyLog(_object*, _object*) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADBase.so+0x4a
#20  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(+0x205a58) [0x7d49d8005a58]
#21  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x25c) [0x7d49d7fe559c]
#22  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x6f2) [0x7d49d7ff0f52]
#23  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(+0x2aa9ad) [0x7d49d80aa9ad]
#24  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(PyEval_EvalCode+0xa4) [0x7d49d80aa424]
#25  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(+0x2c9893) [0x7d49d80c9893]
#26  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(+0x2c532a) [0x7d49d80c532a]
#27  /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libpython3.11.so.1.0(PyRun_StringFlags+0x69) [0x7d49d80b9669]
#28  0x7d49d753ba1c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADBase.so+0x6c
#29  0x7d49d886a193 in Gui::Application::runInitGuiScript() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0x43
#30  0x7d49d89554f1 in Gui::StartupPostProcess::showMainWindow() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0xe1
#31  0x7d49d89572a4 in Gui::StartupPostProcess::execute() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0x64
#32  0x7d49d888a756 in Gui::Application::runApplication() from /tmp/.mount_FreeCAQVaylH/usr/bin/../lib/libFreeCADGui.so+0x4d6
#33  /tmp/.mount_FreeCAQVaylH/usr/bin/freecad(+0x7620) [0x5a0832518620]
#34  /lib/x86_64-linux-gnu/libc.so.6(+0x28150) [0x7d49d5828150]
#35  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7d49d5828209]
#36  /tmp/.mount_FreeCAQVaylH/usr/bin/freecad(+0x7981) [0x5a0832518981]
```

### Full version info

```shell
This is all I have 

./FreeCAD_weekly-builds-36480-2024-03-18-conda-Linux-x86_64-py311.AppImage```
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Should be fixed with #13033
