### ISSUE TITLE
HTML export fails if document contains Draft arrays: 'Gui.ViewProviderLink' object has no attribute 'Deviation'

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Follow up to #13160. I keep trying to export the same file and it keeps failing:

Steps to reproduce:

1. Open attached file
2. Select "Project" in the tree
3. Go to the "File > Export..." menu
4. On the export dialog, select the "WebGL file (*.html)" option in the "Files of type" dropdown
5. Press "OK"
6. Export fails with the following traceback:

```python traceback
08:27:35  pyException: Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/snap/freecad/969/usr/Mod/Arch/importWebGL.py", line 737, in export
    deviation = obj.ViewObject.Deviation
<class 'AttributeError'>: 'Gui.ViewProviderLink' object has no attribute 'Deviation'
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36638 (Git) Snap 969
Build type: Release
Branch: main
Hash: 10b9229492b9e57648235173998d68c9a14c1610
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Installed mods: 
  * BIM 2021.12.0
  * Assembly4 0.50.12
  * ExplodedAssembly
```

### Subproject(s) affected?

Draft

### Anything else?

File to reproduce: [Columns.zip](https://github.com/FreeCAD/FreeCAD/files/14755112/Columns.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
@maxwxyz thanks for the triaging. I believe it needs the "WB Arch" label instead of "WB Draft". At least the file touched by the linked PR are in the `src/mod/Arch` folder.
