### ISSUE TITLE
PySide6 called with wrong argument types

### ISSUE THREAD

**Issue by sdifru** [FreeCAD/FreeCAD#13449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When I launch freecad, I get these error:
```
During initialization the error "'PySide6.QtWidgets.QStatusBar.removeWidget' called with wrong argument types:
  PySide6.QtWidgets.QStatusBar.removeWidget(QPushButton)
Supported signatures:
  PySide6.QtWidgets.QStatusBar.removeWidget(PySide6.QtWidgets.QWidget)" occurred in /usr/lib/freecad/Mod/Tux/InitGui.py
Please look into the log file for further information
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/lib/freecad/bin/qtwebengine_dictionaries'
```

When I open addon manager, I get these error:
```
Running the Python command 'Std_AddonMgr' failed:
Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/AddonManager/AddonManager.py", line 161, in Activated
    NetworkManager.InitializeNetworkManager()
  File "/usr/lib/freecad/Mod/AddonManager/NetworkManager.py", line 655, in InitializeNetworkManager
    AM_NETWORK_MANAGER = NetworkManager()
                         ^^^^^^^^^^^^^^^^
  File "/usr/lib/freecad/Mod/AddonManager/NetworkManager.py", line 171, in __init__
    self.QNAM.setCache(self.diskCache)

'PySide6.QtNetwork.QNetworkAccessManager.setCache' called with wrong argument types:
  PySide6.QtNetwork.QNetworkAccessManager.setCache(QNetworkDiskCache)
Supported signatures:
  PySide6.QtNetwork.QNetworkAccessManager.setCache(PySide6.QtNetwork.QAbstractNetworkCache)
```

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: makepkg
Python 3.11.8, Qt 6.7.0, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sdifru** [comment]
It's a duplicate problem to this issue #13427.
