### ISSUE TITLE
CAM/Path: Adaptive Helix Max Diameter - default is too large.

### ISSUE THREAD

**Issue by Stutchbury** [FreeCAD/FreeCAD#13455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Setup example: Adaptive clearing an 8.75mm diameter by 25mm long slot with a 6mm endmill.

When the Helix Max Diameter is set to the default of 0.000mm, it appears to create a helix diameter that is greater than the slot, so the tool path cannot be generated. The error message (below) does not hint as to why but if the Helix Max Diameter is set to 2.00mm, a tool path is created.

The default value of 0.000 for Helix Max Diameter is therefore misleading as it is trying to create a helix that is greater than 0mm in diameter.

Could the default please be set to the actual default value (perhaps based on the default step over?) rather than zero?

### Full version info

```shell
[code]
OS: Debian GNU/Linux 12 (bookworm) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.22
  * BIM 2021.12.0
[/code]

And:

OS: Debian GNU/Linux 12 (bookworm) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36807 (Git) AppImage
Build type: Release
Branch: main
Hash: cc96f2718e139d670e08c4226bdea9955a102ed6
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Curves 0.6.22
  * BIM 2021.12.0
```

### Subproject(s) affected?

CAM/Path

### Anything else?

This is one of the messages:
`16:47:42  Geom.INFO: Zero working area to process. Check your selection and settings.
16:47:42  Adaptive.INFO: *** Adaptive toolpath processing started...

16:47:42  Adaptive.INFO: *** Done. Elapsed time: 0.117564 sec

16:47:46  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAYGli6U/usr/Mod/CAM/Path/Op/Gui/Base.py", line 1214, in reject
    self.cleanup(resetEdit)
  File "/tmp/.mount_FreeCAYGli6U/usr/Mod/CAM/Path/Op/Gui/Base.py", line 1227, in cleanup
    self.panelCleanup()
  File "/tmp/.mount_FreeCAYGli6U/usr/Mod/CAM/Path/Op/Gui/Base.py", line 1268, in panelCleanup
    page.pageCleanup()
  File "/tmp/.mount_FreeCAYGli6U/usr/Mod/CAM/Path/Op/Gui/Base.py", line 256, in pageCleanup
    self.cleanupPage(self.obj)
  File "/tmp/.mount_FreeCAYGli6U/usr/Mod/CAM/Path/Op/Gui/FeatureExtension.py", line 229, in cleanupPage
    self.obj.ViewObject.RootNode.removeChild(self.switch)
    ^^^^^^^^^^^^^^^^^^^
<class 'RuntimeError'>: Object has been removed from document
16:49:24  Geom.INFO: Zero working area to process. Check your selection and settings.
16:49:24  Adaptive.INFO: *** Adaptive toolpath processing started...

16:49:24  Start point not found!
16:49:24  Adaptive.INFO: *** Done. Elapsed time: 0.002577 sec
`
[test-cam-pocket.zip](https://github.com/FreeCAD/FreeCAD/files/14971291/test-cam-pocket.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Unl0gic** [comment]
I cam across this very same issues today when using a 10mm end mill for an adaptive operation. Setting the Helix Max Diameter manually as described in this issue worked as a workaround.

**Comment by freckletonj** [comment]
Confirming this is still an issue in `1.0.1`
