### ISSUE TITLE
Addon Manager missing from Tools menu

### ISSUE THREAD

**Issue by MaggieLeber** [FreeCAD/FreeCAD#13547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Believe I've searched for an existing problem correctly, but I'm a total noob with FreeCAD.

Just installed 0.21.2 on my Windows 10 machine... AddonManager isn't present on the Tools menu. Attempting to use Help 
launches this dialog: 
![image](https://github.com/FreeCAD/FreeCAD/assets/488972/8e8c25f9-0ffc-443e-abe3-2aae2c4e0ff2)

Pushing the "Open Addon Manager" button displays:

```
18:50:26  During initialization the error "No module named 'queue'" occurred in D:\FreeCAD 0.17\Mod\AddonManager\InitGui.py
18:50:26  Please look into the log file for further information
18:50:27  During initialization the error "module 'FreeCAD' has no attribute 'EndingAdd'" occurred in D:\FreeCAD 0.17\Mod\Image\InitGui.py
18:50:27  Please look into the log file for further information
18:50:28  During initialization the error "'PySide2.QtCore.qRegisterResourceData' called with wrong argument types:
  PySide2.QtCore.qRegisterResourceData(int, str, str, str)
Supported signatures:
  PySide2.QtCore.qRegisterResourceData(int, bytes, bytes, bytes)" occurred in D:\FreeCAD 0.17\Mod\Plot\InitGui.py
18:50:28  Please look into the log file for further information
18:50:28  During initialization the error "'PySide2.QtCore.qRegisterResourceData' called with wrong argument types:
  PySide2.QtCore.qRegisterResourceData(int, str, str, str)
Supported signatures:
  PySide2.QtCore.qRegisterResourceData(int, bytes, bytes, bytes)" occurred in D:\FreeCAD 0.17\Mod\Ship\InitGui.py
18:50:28  Please look into the log file for further information
18:50:31  Unknown command 'Std_AddonMgr'
```

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

Addon Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
I cannot reproduce. Is it available in the recent weekly builds for you: 
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by xtemp09** [comment]
> 18:50:26  During initialization the error "No module named 'queue'" occurred in D:\FreeCAD 0.17\Mod\AddonManager\InitGui.py
> 18:50:26  Please look into the log file for further information
> 18:50:27  During initialization the error "module 'FreeCAD' has no attribute 'EndingAdd'" occurred in D:\FreeCAD 0.17\Mod\Image\InitGui.py

0.17? Could you provide your _PATH_ environment variable and launch _FreeCAD_ with `-l `option [^1] and upload the log file?

[^1]: https://wiki.freecad.org/Debugging

**Comment by MaggieLeber** [comment]
The directory name contains the original 0.17 because the installer inserts it and I wanted to get current; I'd intended to rename it later. 

System path:
```D:\Python312\Scripts\;D:\Python312\;D:\Java\TemurinJDK20\bin;D:\Java\TemurinJDK17\bin;D:\ImageMagick-6.8.8\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;D:\Java\OpenJDK8U-jre_x64_windows_hotspot_8u202b08\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\jEdit;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;D:\apache-maven-3.6.0;D:\Go\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PowerShell\7-preview\preview;D:\PuTTY\;d:\JetBrains\IntelliJ IDEA 2018.3.2\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;D:\sbt\bin;C:\Program Files (x86)\Calibre2\;D:\scala\bin;d:\Git\cmd;D:\nodejs\;C:\ProgramData\chocolatey\bin;D:\Windows Kits\10\Windows Performance Toolkit\;D:\Windows Kits\10\Microsoft Application Virtualization\Sequencer\;D:\Pandoc\;D:\scala-cli\;```

User path
```D:\Rustup\Cargo\bin;C:\Users\maggie\.cargo\bin;d:\Ruby26-x64\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;D:\Microsoft VS Code\bin;%USERPROFILE%\go\bin;D:\JetBrains\IntelliJ IDEA 2018.3.2\plugins\maven\lib\maven3\bin;C:\Users\maggie\AppData\Roaming\npm;d:\Midnight Commander;d:\protodot;```




Ah, the log file was a merry chase. Here we go: 

```Msg: FreeCAD 0.21.2, Libs: 0.21.2R33771 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Log: Time = 2024-Apr-20 13:45:06
Log: AboutImage = freecadabout
Log: AppDataSkipVendor = true
Log: AppHomePath = D:/FreeCAD 0.17/
Log: AppIcon = freecad
Log: AppTempPath = C:\Users\maggie\AppData\Local\Temp\\
Log: BOOST_VERSION = 1_67
Log: BinPath = D:/FreeCAD 0.17/bin\
Log: BuildRepositoryURL = git://github.com/FreeCAD/FreeCAD.git releases/FreeCAD-0-21
Log: BuildRevision = 33771 (Git)
Log: BuildRevisionBranch = releases/FreeCAD-0-21
Log: BuildRevisionDate = 2023/11/14 02:33:39
Log: BuildRevisionHash = b9bfa5c5507506e4515816414cd27f4851d00489
Log: BuildVersionMajor = 0
Log: BuildVersionMinor = 21
Log: BuildVersionPoint = 2
Log: Console = 0
Log: CopyrightInfo = © Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##


Log: Debug = 0
Log: DocPath = D:/FreeCAD 0.17/doc\
Log: EIGEN_VERSION = 3.3.90
Log: ExeName = FreeCAD
Log: ExeVendor = FreeCAD
Log: ExeVersion = 0.21.2
Log: LoggingConsole = 1
Log: LoggingFile = 1
Log: LoggingFileName = C:\Users\maggie\AppData\Roaming\FreeCAD\FreeCAD.log
Log: MaintainerUrl = http://www.freecad.org/wiki/Main_Page
Log: OCC_VERSION = 7.6.3
Log: PATH = D:\Python312\Scripts\;D:\Python312\;D:\Java\TemurinJDK20\bin;D:\Java\TemurinJDK17\bin;D:\ImageMagick-6.8.8\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin;D:\Java\OpenJDK8U-jre_x64_windows_hotspot_8u202b08\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\jEdit;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;D:\apache-maven-3.6.0;D:\Go\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PowerShell\7-preview\preview;D:\PuTTY\;d:\JetBrains\IntelliJ IDEA 2018.3.2\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\sbt\bin;C:\Program Files (x86)\Calibre2\;D:\scala\bin;d:\Git\cmd;D:\nodejs\;C:\ProgramData\chocolatey\bin;D:\Windows Kits\10\Windows Performance Toolkit\;D:\Windows Kits\10\Microsoft Application Virtualization\Sequencer\;D:\Pandoc\;D:\scala-cli\;D:\Rustup\Cargo\bin;C:\Users\maggie\.cargo\bin;d:\Ruby26-x64\bin;C:\Users\maggie\AppData\Local\Microsoft\WindowsApps;D:\Microsoft VS Code\bin;C:\Users\maggie\go\bin;D:\JetBrains\IntelliJ IDEA 2018.3.2\plugins\maven\lib\maven3\bin;C:\Users\maggie\AppData\Roaming\npm;d:\Midnight Commander;d:\protodot;
Log: PYSIDE_VERSION = 5.15.0
Log: PYTHON_VERSION = 3.8.10
Log: PythonSearchPath = D:\FreeCAD 0.17\bin\python38.zip;D:\FreeCAD 0.17\bin\DLLs;D:\FreeCAD 0.17\bin\lib;D:\FreeCAD 0.17\bin
Log: QT_VERSION = 5.15.2
Log: RunMode = Gui
Log: SMESH_VERSION = 7.7.1.0
Log: SplashAlignment = Bottom|Left
Log: SplashInfoColor = #8aadf4
Log: SplashInfoPosition = 6,75
Log: SplashScreen = freecadsplash
Log: SplashTextColor = #8aadf4
Log: StartWorkbench = StartWorkbench
Log: SystemParameter = C:\Users\maggie\AppData\Roaming\FreeCAD\system.cfg
Log: UserAppData = C:\Users\maggie\AppData\Roaming\FreeCAD\
Log: UserCachePath = C:\Users\maggie\AppData\Local\Temp\FreeCAD\Cache\
Log: UserConfigPath = C:\Users\maggie\AppData\Roaming\FreeCAD\
Log: UserHomePath = C:/Users/maggie
Log: UserMacroPath = C:\Users\maggie\AppData\Roaming\FreeCAD\Macro\
Log: UserParameter = C:\Users\maggie\AppData\Roaming\FreeCAD\user.cfg
Log: Verbose = 
Log: XERCESC_VERSION = 3.2.2
Log: Create Application
Log: Run App init script
Log: Init: starting App::FreeCADInit.py
Log: Init:   Searching for modules...
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\AddonManager... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Arch... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Complete... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Draft... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Drawing... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Fem... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Idf... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Image... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Import... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Inspection... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Material... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Measure... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Mesh... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\MeshPart... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\OpenSCAD... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Part... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\PartDesign... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Path... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Plot(Init.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Points... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Raytracing... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\ReverseEngineering... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Robot... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Ship(Init.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Show(Init.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Sketcher... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Spreadsheet... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Start... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Surface... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\TechDraw... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Test... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Tux(Init.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Web... done
Log: Using D:\FreeCAD 0.17\Mod as module path!
Log: System path after init:
Log:    D:\FreeCAD 0.17\bin
Log:    D:\FreeCAD 0.17\Mod\AddonManager
Log:    D:\FreeCAD 0.17\Mod\Arch
Log:    D:\FreeCAD 0.17\Mod\Complete
Log:    D:\FreeCAD 0.17\Mod\Draft
Log:    D:\FreeCAD 0.17\Mod\Drawing
Log:    D:\FreeCAD 0.17\Mod\Fem
Log:    D:\FreeCAD 0.17\Mod\Idf
Log:    D:\FreeCAD 0.17\Mod\Image
Log:    D:\FreeCAD 0.17\Mod\Import
Log:    D:\FreeCAD 0.17\Mod\Inspection
Log:    D:\FreeCAD 0.17\Mod\Material
Log:    D:\FreeCAD 0.17\Mod\Measure
Log:    D:\FreeCAD 0.17\Mod\Mesh
Log:    D:\FreeCAD 0.17\Mod\MeshPart
Log:    D:\FreeCAD 0.17\Mod\OpenSCAD
Log:    D:\FreeCAD 0.17\Mod\Part
Log:    D:\FreeCAD 0.17\Mod\PartDesign
Log:    D:\FreeCAD 0.17\Mod\Path
Log:    D:\FreeCAD 0.17\Mod\Plot
Log:    D:\FreeCAD 0.17\Mod\Points
Log:    D:\FreeCAD 0.17\Mod\Raytracing
Log:    D:\FreeCAD 0.17\Mod\ReverseEngineering
Log:    D:\FreeCAD 0.17\Mod\Robot
Log:    D:\FreeCAD 0.17\Mod\Ship
Log:    D:\FreeCAD 0.17\Mod\Show
Log:    D:\FreeCAD 0.17\Mod\Sketcher
Log:    D:\FreeCAD 0.17\Mod\Spreadsheet
Log:    D:\FreeCAD 0.17\Mod\Start
Log:    D:\FreeCAD 0.17\Mod\Surface
Log:    D:\FreeCAD 0.17\Mod\TechDraw
Log:    D:\FreeCAD 0.17\Mod\Test
Log:    D:\FreeCAD 0.17\Mod\Tux
Log:    D:\FreeCAD 0.17\Mod\Web
Log:    D:\Python312\Scripts\
Log:    D:\Python312\
Log:    D:\Java\TemurinJDK20\bin
Log:    D:\Java\TemurinJDK17\bin
Log:    D:\ImageMagick-6.8.8\ImageMagick-7.1.0-Q16-HDRI
Log:    C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin
Log:    D:\Java\OpenJDK8U-jre_x64_windows_hotspot_8u202b08\bin
Log:    C:\Windows\system32
Log:    C:\Windows
Log:    C:\Windows\System32\Wbem
Log:    C:\Windows\System32\WindowsPowerShell\v1.0\
Log:    C:\Windows\System32\OpenSSH\
Log:    C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
Log:    D:\jEdit
Log:    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
Log:    C:\Program Files\dotnet\
Log:    D:\apache-maven-3.6.0
Log:    D:\Go\bin
Log:    C:\WINDOWS\system32
Log:    C:\WINDOWS
Log:    C:\WINDOWS\System32\Wbem
Log:    C:\WINDOWS\System32\WindowsPowerShell\v1.0\
Log:    C:\WINDOWS\System32\OpenSSH\
Log:    C:\Program Files\PowerShell\7-preview\preview
Log:    D:\PuTTY\
Log:    d:\JetBrains\IntelliJ IDEA 2018.3.2\bin
Log:    C:\WINDOWS\system32
Log:    C:\WINDOWS
Log:    C:\WINDOWS\System32\Wbem
Log:    C:\WINDOWS\System32\WindowsPowerShell\v1.0\
Log:    C:\WINDOWS\System32\OpenSSH\
Log:    D:\sbt\bin
Log:    C:\Program Files (x86)\Calibre2\
Log:    D:\scala\bin
Log:    d:\Git\cmd
Log:    D:\nodejs\
Log:    C:\ProgramData\chocolatey\bin
Log:    D:\Windows Kits\10\Windows Performance Toolkit\
Log:    D:\Windows Kits\10\Microsoft Application Virtualization\Sequencer\
Log:    D:\Pandoc\
Log:    D:\scala-cli\
Log:    D:\Rustup\Cargo\bin
Log:    C:\Users\maggie\.cargo\bin
Log:    d:\Ruby26-x64\bin
Log:    C:\Users\maggie\AppData\Local\Microsoft\WindowsApps
Log:    D:\Microsoft VS Code\bin
Log:    C:\Users\maggie\go\bin
Log:    D:\JetBrains\IntelliJ IDEA 2018.3.2\plugins\maven\lib\maven3\bin
Log:    C:\Users\maggie\AppData\Roaming\npm
Log:    d:\Midnight Commander
Log:    d:\protodot
Log:    
Log: Init: App::FreeCADInit.py done
Log: Init: Creating Gui::Application and QApplication
Log: OpenGL version is: 4.6 (4.6.0 NVIDIA 551.52)
Log: Run Gui init script
Log: Init: Running FreeCADGuiInit.py start script...
Log: Init:   Searching modules...
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\AddonManager... failed
Log: ----------------------------------------------------------------------------------------------------
Log: Traceback (most recent call last):
  File "<string>", line 136, in RunInitGuiPy
  File "<string>", line 6, in <module>
  File "D:\FreeCAD 0.17\Mod\AddonManager\AddonManager.py", line 41, in <module>
    from addonmanager_workers_startup import (
  File "D:\FreeCAD 0.17\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\FreeCAD 0.17\Mod\AddonManager\addonmanager_workers_startup.py", line 30, in <module>
    import queue
  File "D:\FreeCAD 0.17\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'queue'
Log: ----------------------------------------------------------------------------------------------------
Err: During initialization the error "No module named 'queue'" occurred in D:\FreeCAD 0.17\Mod\AddonManager\InitGui.py
Err: Please look into the log file for further information
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Arch... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Complete... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Draft... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Drawing... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Fem... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Idf(InitGui.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Image... failed
Log: ----------------------------------------------------------------------------------------------------
Log: Traceback (most recent call last):
  File "<string>", line 136, in RunInitGuiPy
  File "<string>", line 50, in <module>
AttributeError: module 'FreeCAD' has no attribute 'EndingAdd'
Log: ----------------------------------------------------------------------------------------------------
Err: During initialization the error "module 'FreeCAD' has no attribute 'EndingAdd'" occurred in D:\FreeCAD 0.17\Mod\Image\InitGui.py
Err: Please look into the log file for further information
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Import... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Inspection... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Material... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Measure(InitGui.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Mesh... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\MeshPart... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\OpenSCAD... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Part... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\PartDesign... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Path... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Plot... failed
Log: ----------------------------------------------------------------------------------------------------
Log: Traceback (most recent call last):
  File "<string>", line 136, in RunInitGuiPy
  File "<string>", line 25, in <module>
  File "<string>", line 33, in PlotWorkbench
  File "D:\FreeCAD 0.17\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\FreeCAD 0.17\Mod\Plot\PlotGui.py", line 30, in <module>
    import Plot_rc
  File "D:\FreeCAD 0.17\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\FreeCAD 0.17\Mod\Plot\Plot_rc.py", line 21, in <module>
    qInitResources()
  File "D:\FreeCAD 0.17\Mod\Plot\Plot_rc.py", line 16, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)
TypeError: 'PySide2.QtCore.qRegisterResourceData' called with wrong argument types:
  PySide2.QtCore.qRegisterResourceData(int, str, str, str)
Supported signatures:
  PySide2.QtCore.qRegisterResourceData(int, bytes, bytes, bytes)
Log: ----------------------------------------------------------------------------------------------------
Err: During initialization the error "'PySide2.QtCore.qRegisterResourceData' called with wrong argument types:
  PySide2.QtCore.qRegisterResourceData(int, str, str, str)
Supported signatures:
  PySide2.QtCore.qRegisterResourceData(int, bytes, bytes, bytes)" occurred in D:\FreeCAD 0.17\Mod\Plot\InitGui.py
Err: Please look into the log file for further information
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Points... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Raytracing... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\ReverseEngineering... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Robot... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Ship... failed
Log: ----------------------------------------------------------------------------------------------------
Log: Traceback (most recent call last):
  File "<string>", line 136, in RunInitGuiPy
  File "<string>", line 25, in <module>
  File "<string>", line 33, in ShipWorkbench
  File "D:\FreeCAD 0.17\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\FreeCAD 0.17\Mod\Ship\ShipGui.py", line 30, in <module>
    import Ship_rc
  File "D:\FreeCAD 0.17\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\FreeCAD 0.17\Mod\Ship\Ship_rc.py", line 21, in <module>
    qInitResources()
  File "D:\FreeCAD 0.17\Mod\Ship\Ship_rc.py", line 16, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)
TypeError: 'PySide2.QtCore.qRegisterResourceData' called with wrong argument types:
  PySide2.QtCore.qRegisterResourceData(int, str, str, str)
Supported signatures:
  PySide2.QtCore.qRegisterResourceData(int, bytes, bytes, bytes)
Log: ----------------------------------------------------------------------------------------------------
Err: During initialization the error "'PySide2.QtCore.qRegisterResourceData' called with wrong argument types:
  PySide2.QtCore.qRegisterResourceData(int, str, str, str)
Supported signatures:
  PySide2.QtCore.qRegisterResourceData(int, bytes, bytes, bytes)" occurred in D:\FreeCAD 0.17\Mod\Ship\InitGui.py
Err: Please look into the log file for further information
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Show(InitGui.py not found)... ignore
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Sketcher... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Spreadsheet... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Start... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Surface... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\TechDraw... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Test... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Tux... done
Log: Init:      Initializing D:\FreeCAD 0.17\Mod\Web... done
Log: All modules with GUIs using InitGui.py are now initialized
Log: All modules with GUIs initialized using pkgutil are now initialized
Log: Init: Loading FreeCAD GUI
Log: Init: Running FreeCADGuiInit.py start script... done
Log: Init: Activating default workbench StartWorkbench
Log: Loading GUI of Web module... done
Log: Loading GUI of Start module... done
Log: Loading Start module... done
Wrn: Unknown command 'Std_AddonMgr'
Log: Init: Showing main window
Log: Main window restored
Log: Show main window
Log: Toolbars restored
Log: 3Dconnexion device not attached.
Log: Init: Entering event loop
Log: Init: Executing event loop...
Log: Init: Processing command line files
Log: Hide main window
Log: Show main window
Log: Hide main window
Log: Show main window
Log: Hide main window
Log: Finish: Event loop left
Log: Destruct Gui::Application
Log: FreeCAD terminating...
Log: Saving system parameter...
Log: Saving system parameter...done
Log: Saving user parameter...
Log: Saving user parameter...done
```

**Comment by xtemp09** [comment]
The old installation messed up the new one. @MaggieLeber, delete _FreeCAD_, delete the configuration files[^1][^2], install _FreeCAD_ anew into a normal folder.


----



I'd also delete all these things in _PATH_.

One can launch a program in a “clean” environment or with a special _PATH_. The simple way to do this is to create a bat (or cmd) file and write there something like the following:

```ruby
set PATH="C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;"
FreeCAD.exe
```




[^1]: c:\Users\maggie\AppData\Local\FreeCAD
[^2]: c:\Users\maggie\AppData\Roaming\FreeCAD

**Comment by MaggieLeber** [comment]
OK, we'll wipe it all and start over. 

"All those things in path" are there for reasons, though.
 
Window programs in general do a crappy job of dealing with Users\home that aren't on the boot drive, the boot drive accumulates cruft that shouldn't be there. Pain point for SSD boot with spinny mass storage.  

OK, there were two uninstallers in the Windows apps settings, ran them both and one of them even removed the AppData stuff.
Fresh install running fine now, including Addon Manager. 

Thanks for your help, I dropped some bucks in the donation box to show my appreciation.

**Comment by xtemp09** [comment]
> Window programs in general do a crappy job of dealing with Users\home that aren't on the boot drive

If I were you, I would have used symbolic links or junctions, leaving standard paths intact.
