### ISSUE TITLE
Cannot open tools library after saving in utf directory

### ISSUE THREAD

**Issue by Krandelbord** [FreeCAD/FreeCAD#13603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In "Path" workspace I added few tools, and I saved them
No each time I try to open my toolset I get exception 
```
To update, check the 'Preferences->General->Document->Use date and FCBak extension' option.
15:42:18  Running the Python command 'Path_ToolBitLibraryOpen' failed:
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAKzLtQ4/usr/Mod/Path/Path/Tool/Gui/BitLibraryCmd.py", line 90, in Activated
    library = PathToolBitLibraryGui.ToolBitLibrary()
  File "/tmp/.mount_FreeCAKzLtQ4/usr/Mod/Path/Path/Tool/Gui/BitLibrary.py", line 494, in __init__
    checkWorkingDir()
  File "/tmp/.mount_FreeCAKzLtQ4/usr/Mod/Path/Path/Tool/Gui/BitLibrary.py", line 70, in checkWorkingDir
    if dirOK():
  File "/tmp/.mount_FreeCAKzLtQ4/usr/Mod/Path/Path/Tool/Gui/BitLibrary.py", line 68, in <lambda>
    dirOK = lambda: workingdir != defaultdir and (os.access(workingdir, os.W_OK))

'ascii' codec can't encode character '\u0119' in position 34: ordinal not in range(128)"
```

### Full version info

```shell
[code]
OS: Debian GNU/Linux trixie/sid (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
[/code]
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Krandelbord** [comment]
My path was:
```xml
            <FCText Name="LastPathToolLibrary">/home/emil/Dokumenty/projekty/narzędzia do freecad/Library</FCText>
            <FCText Name="LastFileToolLibrary">/home/emil/Dokumenty/projekty/narzędzia do freecad/Library/Default.fctl</FCText>
            <FCText Name="LastPathToolBit">/home/emil/Dokumenty/projekty/narzędzia do freecad/Bit</FCText>
```
