### ISSUE TITLE
Materials tool crashes on Arch workbench

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD#13821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps to reproduce

1. Create a new document
2. Switch to the Arch workbench
3. Click on the <kbd>Material Tools</kbd> ([Arch_MaterialTools](https://wiki.freecad.org/Arch_CompSetMaterial)) icon
4. Material tools don't load, the user is presented with this error

```python-traceback
12:00:06  pyException: Traceback (most recent call last):
  File "/usr/share/freecad-daily/Mod/Arch/ArchMaterial.py", line 481, in setEdit
    self.taskd = _ArchMaterialTaskPanel(vobj.Object)
  File "/usr/share/freecad-daily/Mod/Arch/ArchMaterial.py", line 556, in __init__
    self.fillMaterialCombo()
  File "/usr/share/freecad-daily/Mod/Arch/ArchMaterial.py", line 699, in fillMaterialCombo
    for f in os.listdir(p):
<class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/usr/share/freecad-daily//Mod/Material/StandardMaterial'
```

I can reproduce this both with the PPA and snap package builds, as well as with a local built. So it seems it's not simply a packaging issue. It can also be reproduced with the BIM workbench.

It looks like the issue surfaces in this part of the code:
https://github.com/FreeCAD/FreeCAD/blob/9bd19ff43a1c984d9d241f85c31c3d30be876d06/src/Mod/Arch/ArchMaterial.py#L689-L705

I believe the code is looking for the standard materials folder here:
`$RESOURCE_DIR/Mod/Material/StandardMaterial/`

But the new Material workbench revamp has changed that location to:
`$RESOURCE_DIR/Mod/Material/Resources/Materials/Standard/`

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37096 (Git)
Build type: Release
Branch: main
Hash: af2b8b661f711f8512d63345e4ffe321e292ddbb
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * OpenTheme 2024.4.20
  * BIM 2021.12.0
  * parts_library
```

### Subproject(s) affected?

Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@davesrocketshop FYI

**Comment by yorikvanhavre** [comment]
I'll attack this (compatibility with new Materials system) as soon as #13783 (BIM migratihn is done. |since the arch materials system is (currently) mostly self-contained, it shouldn't be much work to have it back working. Then we see about integrating things better

**Comment by furgo16** [comment]
I've submitted a draft PR that addresses this: https://github.com/FreeCAD/FreeCAD/pull/13830
