### ISSUE TITLE
[Problem] Issues with compiling FreeCAD from source on Linux（centos7）

### ISSUE THREAD

**Issue by sigurHeBin** [FreeCAD/FreeCAD#13856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hey!
I am trying to compile FreeCAD from source for Linux. I am using the following script to do that:
```
[root@iZn11er29gnfasZ build]# cmake -DQT_RCC_EXECUTABLE=/usr/local/Qt-5.12.12/bin ../
CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler: GNU, version: 7.3.1
-- Looking for GL/gl.h
-- Looking for GL/gl.h - found
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include fstream
-- Looking for C++ include fstream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for C++ include ios
-- Looking for C++ include ios - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Looking for C++ include iomanip
-- Looking for C++ include iomanip - found
-- Looking for C++ include iostream
-- Looking for C++ include iostream - found
-- Check for STD namespace
-- Check for STD namespace - found
-- prefix: /usr/local
-- bindir: bin
-- datadir: share
-- docdir: share/doc/FreeCAD
-- includedir: include
-- libdir: lib64
-- cmake: 3.28.4
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components: doxygen missing components: dot
-- Found Python3: /usr/local/bin/python3.8 (found version "3.8.17") found components: Interpreter Development Development.Module Development.Embe                               d
-- Found XercesC: /usr/lib64/libxerces-c.so (found version "3.1.1")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- PyCXX found:
--   Headers:  /app/software/FreeCAD/src
--   Sources:  /app/software/FreeCAD/src/CXX
--   Version:  6.2.8
CMake Warning (dev) at /usr/local/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OCC) does
  not match the name of the calling package (OpenCasCade).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cMake/FindOpenCasCade.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (find_package)
  CMakeLists.txt:51 (SetupOpenCasCade)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OCC: /usr/local/include/opencascade (found version "7.7.2")
-- -- Found OCE/OpenCASCADE version: 7.7.2
-- -- OCE/OpenCASCADE include directory: /usr/local/include/opencascade
-- -- OCE/OpenCASCADE shared libraries directory: /usr/local/lib
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found OpenGLU: /usr/lib64/libGLU.so
-- VTK components: vtkCommonCore;vtkCommonDataModel;vtkFiltersVerdict;vtkIOXML;vtkFiltersCore;vtkFiltersGeneral;vtkIOLegacy;vtkFiltersExtraction;                               vtkFiltersSources;vtkFiltersGeometry;vtkhdf5;vtkRenderingCore;vtkInteractionStyle;vtkRenderingFreeType
-- Check for medfile (libmed and libmedc) ...
-- Found MEDFile: /usr/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- We guess that libmed was built using hdf5-serial version
-- Checking for one of the modules 'hdf5-serial'
-- Found HDF5: /usr/lib64/libhdf5.so (found version "1.8.12")
-- Checking for one of the modules 'ompi-cxx'
CMake Warning at cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake:115 (message):
  ompi-cxx was not found.  Check for error above.
Call Stack (most recent call first):
  CMakeLists.txt:58 (SetupSalomeSMESH)


-- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found suitable version "1.75.0", minimum required is "1.55") found component                               s: filesystem program_options regex system thread date_time
-- Found SWIG: /usr/local/bin/swig (found version "4.2.1")
-- Found Eigen3: /usr/include/eigen3 (found suitable version "3.3.7", minimum required is "2.91.0")
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.8.0")
-- Checking for module 'Coin'
--   No package 'Coin' found
-- Coin3D libraries found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pivy'
-- Could NOT find Spnav (missing: SPNAV_LIBRARY SPNAV_INCLUDE_DIR)
====================
shiboken2 not found.
====================

==================
PySide2 not found.
==================

=======================
PySide2Tools not found.
=======================

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'shiboken2'
=================================
shiboken Python module not found.
=================================

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PySide2'
================================
PySide2 Python module not found.
================================

=====================================================
Matplotlib not found, Plot module won't be available.
=====================================================

-- Platform is 64-bit, set -D_OCC64
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
-- Performing Test _flag_found
-- Performing Test _flag_found - Success
CMake Warning (dev) at src/3rdParty/libE57Format/cmake/Modules/Tags.cmake:31 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  src/3rdParty/libE57Format/CMakeLists.txt:45 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Threads: TRUE
-- [E57] Revison ID: E57Format-2.2.1-x86_64-linux-gcc7
-- [E57] Building static library
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- /app/software/FreeCAD/build/src/Base/TypePy.cpp
-- /app/software/FreeCAD/build/src/Base/BaseClassPy.cpp
-- /app/software/FreeCAD/build/src/Base/BoundBoxPy.cpp
-- /app/software/FreeCAD/build/src/Base/CoordinateSystemPy.cpp
-- /app/software/FreeCAD/build/src/Base/PersistencePy.cpp
-- /app/software/FreeCAD/build/src/Base/VectorPy.cpp
-- /app/software/FreeCAD/build/src/Base/MatrixPy.cpp
-- /app/software/FreeCAD/build/src/Base/RotationPy.cpp
-- /app/software/FreeCAD/build/src/Base/PlacementPy.cpp
-- /app/software/FreeCAD/build/src/Base/AxisPy.cpp
-- /app/software/FreeCAD/build/src/Base/UnitPy.cpp
-- /app/software/FreeCAD/build/src/Base/QuantityPy.cpp
-- /app/software/FreeCAD/build/src/App/DocumentPy.cpp
-- /app/software/FreeCAD/build/src/App/DocumentObjectPy.cpp
-- /app/software/FreeCAD/build/src/App/ExtensionPy.cpp
-- /app/software/FreeCAD/build/src/App/ExtensionContainerPy.cpp
-- /app/software/FreeCAD/build/src/App/DocumentObjectExtensionPy.cpp
-- /app/software/FreeCAD/build/src/App/GroupExtensionPy.cpp
-- /app/software/FreeCAD/build/src/App/LinkBaseExtensionPy.cpp
-- /app/software/FreeCAD/build/src/App/DocumentObjectGroupPy.cpp
-- /app/software/FreeCAD/build/src/App/GeoFeaturePy.cpp
-- /app/software/FreeCAD/build/src/App/GeoFeatureGroupExtensionPy.cpp
-- /app/software/FreeCAD/build/src/App/MetadataPy.cpp
-- /app/software/FreeCAD/build/src/App/OriginGroupExtensionPy.cpp
-- /app/software/FreeCAD/build/src/App/PartPy.cpp
-- /app/software/FreeCAD/build/src/App/ComplexGeoDataPy.cpp
-- /app/software/FreeCAD/build/src/App/PropertyContainerPy.cpp
-- /app/software/FreeCAD/build/src/App/MaterialPy.cpp
CMake Error at cMake/FindPySide2Tools.cmake:78 (message):
  Qt rcc is required for generating Resources/AddonManager.qrc
Call Stack (most recent call first):
  src/Mod/AddonManager/CMakeLists.txt:2 (PYSIDE_WRAP_RC)


-- Configuring incomplete, errors occurred!

``` 

#

there is an error：
```
CMake Error at cMake/FindPySide2Tools.cmake:78 (message):
  Qt rcc is required for generating Resources/AddonManager.qrc
Call Stack (most recent call first):
  src/Mod/AddonManager/CMakeLists.txt:2 (PYSIDE_WRAP_RC)
``` 

But I have successfully installed QT RCC and have specified the path in cmake：
```
[root@iZn11er29gnfasZ build]# which rcc
/usr/local/Qt-5.12.12/bin/rcc

``` 

### Full version info

```shell
https://github.com/FreeCAD/FreeCAD/tree/0.20
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhaosky** [comment]
how your reslove this problem

**Comment by JackyhuangUp** [comment]
Is there a solution now?

**Comment by sigurHeBin** [comment]
> how your reslove this problem

version issue,i change the FreeCAD version to 0.21.2 and install a specific version of qt.
