### ISSUE TITLE
AddonManager: failing to load workbenches with Qt6 / PySide 6 

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#14083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Addon Manager cannot load the list of workbenches due to a small change in the QNetworkRequest:

```
12:11:39  Traceback (most recent call last):
12:11:39    File "/home/pieter/build-freecad-main-debug/Mod/AddonManager/addonmanager_workers_installation.py", line 92, in run
12:11:39      index = NetworkManager.AM_NETWORK_MANAGER.submit_unmonitored_get(
12:11:39              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:11:39    File "/home/pieter/build-freecad-main-debug/Mod/AddonManager/NetworkManager.py", line 338, in submit_unmonitored_get
12:11:39      current_index, self.__create_get_request(url, timeout_ms), track_progress=False
12:11:39                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:11:39    File "/home/pieter/build-freecad-main-debug/Mod/AddonManager/NetworkManager.py", line 431, in __create_get_request
12:11:39      request.setTransferTimeout(timeout_ms)
12:11:39  TypeError: 'PySide6.QtNetwork.QNetworkRequest.setTransferTimeout' called with wrong argument types:
  PySide6.QtNetwork.QNetworkRequest.setTransferTimeout(TransferTimeoutConstant)
Supported signatures:
  PySide6.QtNetwork.QNetworkRequest.setTransferTimeout(int)
  ```

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37347 (Git)
Build type: Unknown
Branch: main
Hash: 18c85a58aeb0fa9d69fae1b70de85d7fff9e0eb3
Python 3.12.3, Qt 6.7.0, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Addon Manager

### Anything else?

#13303 is related.
#13997 seems to be related as @obelisk79 reports the Addon Manager to be working.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@chennes FYI
