### ISSUE TITLE
Gui: Segfault on closing a document in Qt 6

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#14189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Qt 6, an assertion fails when closing a document causing FreeCAD to deliberately segfault.  To reproduce:
- Open FreeCAD
- Open a new empty document
- Close the document

This behavior is not present in Qt 5.

The assertion:
```
ASSERT failure in QOpenGLWidget: "Called object is not of the correct type (class destructor may have already run)", file /usr/include/qt6/QtCore/qobjectdefs_impl.h, line 129
```

Stacktrace:
```
#0  0x00007ffff04a8e44 in ??? () at /usr/lib/libc.so.6
#1  0x00007ffff0450a30 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff04384c3 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff678af93 in messageHandler (type=QtFatalMsg, context=..., msg=...) at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:1804
#4  0x00007ffff0adae34 in ??? () at /usr/lib/libQt6Core.so.6
#5  0x00007ffff0adaf80 in ??? () at /usr/lib/libQt6Core.so.6
#6  0x00007ffff0a8ce27 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/libQt6Core.so.6
#7  0x00007ffff0a8ceda in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt6Core.so.6
#8  0x00007ffff6edb9c8 in QtPrivate::assertObjectType<CustomGLWidget> (o=0x555559315dd0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:129
#9  0x00007ffff6edb3d6 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (CustomGLWidget::*)()>::call(void (CustomGLWidget::*)(), CustomGLWidget*, void**) (f=(void (CustomGLWidget::*)(CustomGLWidget * const)) 0x7ffff6ed9356 <CustomGLWidget::aboutToDestroyGLContext()>, o=0x555559315dd0, arg=0x7fffffffbf18) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:144
#10 0x00007ffff6edab82 in QtPrivate::FunctionPointer<void (CustomGLWidget::*)()>::call<QtPrivate::List<>, void>(void (CustomGLWidget::*)(), CustomGLWidget*, void**) (f=(void (CustomGLWidget::*)(CustomGLWidget * const)) 0x7ffff6ed9356 <CustomGLWidget::aboutToDestroyGLContext()>, o=0x555559315dd0, arg=0x7fffffffbf18) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#11 0x00007ffff6eda639 in QtPrivate::QCallableObject<void (CustomGLWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555555cc8f40, r=0x555559315dd0, a=0x7fffffffbf18, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:553
#12 0x00007ffff0b9b57f in ??? () at /usr/lib/libQt6Core.so.6
#13 0x00007ffff1497753 in QOpenGLContext::destroy() () at /usr/lib/libQt6Gui.so.6
#14 0x00007ffff14979bf in QOpenGLContext::~QOpenGLContext() () at /usr/lib/libQt6Gui.so.6
#15 0x00007ffff534030b in ??? () at /usr/lib/libQt6OpenGLWidgets.so.6
#16 0x00007ffff53403ad in QOpenGLWidget::~QOpenGLWidget() () at /usr/lib/libQt6OpenGLWidgets.so.6
#17 0x00007ffff6ed91be in CustomGLWidget::~CustomGLWidget (this=0x555559315dd0, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/QuarterWidget.cpp:169
#18 0x00007ffff6ed91e0 in CustomGLWidget::~CustomGLWidget (this=0x555559315dd0, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/QuarterWidget.cpp:169
#19 0x00007ffff0b8a39b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#20 0x00007ffff1b31709 in QWidget::~QWidget() () at /usr/lib/libQt6Widgets.so.6
#21 0x00007ffff6ed6284 in SIM::Coin3D::Quarter::QuarterWidget::~QuarterWidget (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/QuarterWidget.cpp:356
#22 0x00007ffff6ee1723 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::~SoQTQuarterAdaptor (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/SoQTQuarterAdaptor.cpp:182
#23 0x00007ffff6f31c6b in Gui::View3DInventorViewer::~View3DInventorViewer (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventorViewer.cpp:638
#24 0x00007ffff6f31cb4 in Gui::View3DInventorViewer::~View3DInventorViewer (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventorViewer.cpp:638
#25 0x00007ffff6f2615e in Gui::View3DInventor::~View3DInventor (this=0x555559268230, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventor.cpp:174
#26 0x00007ffff6f261d4 in Gui::View3DInventor::~View3DInventor (this=0x555559268230, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventor.cpp:175
#27 0x00007ffff0b8bf1c in QObject::event(QEvent*) () at /usr/lib/libQt6Core.so.6
#28 0x00007ffff1afc44d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#29 0x00007ffff6933112 in Gui::GUIApplication::notify (this=0x7fffffffced0, receiver=0x555559268230, event=0x555559317fe0) at /home/pieter/freecad-add-prop-varset/src/Gui/GuiApplication.cpp:83
#30 0x00007ffff0b3fe18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#31 0x00007ffff0b401d2 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
#32 0x00007ffff0d959ac in ??? () at /usr/lib/libQt6Core.so.6
#33 0x00007fffed90ea89 in ??? () at /usr/lib/libglib-2.0.so.0
#34 0x00007fffed9709b7 in ??? () at /usr/lib/libglib-2.0.so.0
#35 0x00007fffed90df95 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#36 0x00007ffff0d93389 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#37 0x00007ffff0b48350 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#38 0x00007ffff0b43c1d in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#39 0x00007ffff678be50 in (anonymous namespace)::tryRunEventLoop (mainApp=...) at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:2042
#40 0x00007ffff678c19b in (anonymous namespace)::runEventLoop (mainApp=...) at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:2062
#41 0x00007ffff678c554 in Gui::Application::runApplication () at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:2139
#42 0x000055555557a579 in main (argc=1, argv=0x7fffffffd6b8) at /home/pieter/freecad-add-prop-varset/src/Main/MainGui.cpp:278
```

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37438 (Git)
Build type: DEBUG
Branch: main
Hash: 58083879b765846daaeab4fdb125e418138e5874
Python 3.12.3, Qt 6.7.0, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.5.16
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Related: https://github.com/FreeCAD/FreeCAD/issues/13303
