### ISSUE TITLE
Flattened SVG export issues

### ISSUE THREAD

**Issue by davesrocketshop** [FreeCAD/FreeCAD#14587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The attached project file has several SVG export issues.

This is the piece modeled using Part Workbench:
![SVG Error](https://github.com/FreeCAD/FreeCAD/assets/38090157/0ad73d90-3afc-4eb6-998d-bcf6bb21ab63)

Selecting the part and exporting as a Flattened SVG produces this when imported into Inkscape:
![SVG Error - Inkscape](https://github.com/FreeCAD/FreeCAD/assets/38090157/df78fc05-1d1e-4047-897c-734e24279e21)

If you then ungroup the objects you get this:
![SVG Error - Inkscape Ungroup](https://github.com/FreeCAD/FreeCAD/assets/38090157/4a7d3f89-0a9f-46f8-b8eb-8d5a0c7ac0a2)

Ungrouping the objects again, you can hit delete twice removing duplicate layers and finally winding up with a single copy:
![SVG Error - Inkscape Extra Layers](https://github.com/FreeCAD/FreeCAD/assets/38090157/d86bf0cb-660f-4f04-8ad5-e9758ee30392)

[SVG Error.FCStd.zip](https://github.com/user-attachments/files/15768823/SVG.Error.FCStd.zip)

### Full version info

```shell
Dev version built from source:

OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37670 (Git)
Build type: Release
Branch: main
Hash: ba0ff0db5e78973cb994b82f27bdd228c7ad41bd
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * ArchTextures
  * CfdOF 1.25.11
  * fasteners 0.5.17
  * fcgear 1.0.0
  * FeedsAndSpeeds 0.5.0
  * GDML.backup1701064072.5104816 2.0.0 (Disabled)
  * kicadStepUpMod 11.1.2
  * LCInterlocking
  * MaterialTest
  * OpenTheme 2024.5.3
  * render 2023.8.18
  * Rocket 4.0.0
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Maybe related https://github.com/FreeCAD/FreeCAD/issues/13249

**Comment by Roy-043** [comment]
I get a different result. See attached SVG. There is a filled outline, and each edge of that shape is duplicated. Which does not seem to match the description. Note that I have only selected the End body for export.

![SVG Error-End-roy](https://github.com/FreeCAD/FreeCAD/assets/70520633/3f133217-0078-4334-9ff1-3b88836b98da)

```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37645 (Git)
Build type: Release
Branch: main
Hash: fc714933a7e2423d5fa4db640af549814061c42e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods: 
```

**Comment by mnesarco** [comment]
@davesrocketshop  I have opened the file SVG.Error.FCStd in FreeCAD 1.0, selected End and exported to svg using SvgWorkbench for testing, this is the result:

![Image](https://github.com/user-attachments/assets/60424996-ad3c-43f5-9c29-f19e5fbb2cbc)


In SvgWorkbench I use TechDraw+DraftWB APIs to project the svg geometry. So if there are bugs there they will leak to SvgWorkbench too.

**Comment by Roy-043** [comment]
Looking at this again I have to correct what I said before: There are 2 filled outlines and every edge is duplicated. And, as @tigert has mentioned, each edge is in fact a closed path (with duplicate points at each end).

The reason for this result is that each face of the solid gets exported, incuding faces that do not face the camera.

**Comment by Roy-043** [comment]
Still an issue:
```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.42340 (Git)
Build date: 2025/06/27 09:25:36
Build type: Release
Branch: main
Hash: 4f167b828b68b1544732881f0b2393ea873cffd1
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Free Turntable/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/86.1283/1
Installed mods:
```

**Comment by luzpaz** [comment]
* Will #24832 impact this ?

@davesrocketshop any chance you can test ?

**Comment by davesrocketshop** [comment]
> * Will [Draft: Fix duplicated curves in SVG export and add sub-selection support #24832](https://github.com/FreeCAD/FreeCAD/pull/24832) impact this ?
> 
> 
> [@davesrocketshop](https://github.com/davesrocketshop) any chance you can test ?

I'll test it today

**Comment by heiserhorn** [comment]
Not sure if this is relate to this bug but I have the following pad with fillet:

<img width="563" height="681" alt="Image" src="https://github.com/user-attachments/assets/b57b28bc-dab2-48f6-838e-1d2331a5a332" />

when exporting to flattened SVG I get this:

<img width="1303" height="1359" alt="Image" src="https://github.com/user-attachments/assets/6b253f9a-7f68-43c8-b577-2ed339b4359f" />

for comparison I have a similar shape that I created following the same process and the result is correct:

<img width="1179" height="783" alt="Image" src="https://github.com/user-attachments/assets/409ff16f-9213-4a73-9597-3bba8f91a58a" />

<img width="1047" height="741" alt="Image" src="https://github.com/user-attachments/assets/768f9da1-054b-4615-8cb4-68c514a61fab" />

I tested with the latest dev version.

using the workaround mentioned here works: [https://github.com/FreeCAD/FreeCAD/issues/14587#issuecomment-2665627260](url)

**Comment by FEA-eng** [comment]
I get this when trying to export to flattened SVG:

```
09:41:37  pyException: Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\Mod\Draft\importSVG.py", line 1430, in export
    svg.write(get_svg(ob, override=False))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\Mod\Draft\draftfunctions\svg.py", line 1095, in get_svg
    svg += get_path(
           ^^^^^^^^^
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\Mod\Draft\draftfunctions\svgshapes.py", line 409, in get_path
    _type, data = _get_path_circ_ellipse(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\Mod\Draft\draftfunctions\svgshapes.py", line 149, in _get_path_circ_ellipse
    snip = TechDraw.projectToSVG(edge, drawing_plane_normal)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\Ext\lazy_loader\lazy_loader.py", line 54, in __getattr__
    module = self._load()
             ^^^^^^^^^^^^
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\Ext\lazy_loader\lazy_loader.py", line 43, in _load
    module = importlib.import_module(self.__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\FreeCAD_weekly-2026.07.22-Windows-x86_64\bin\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with<class 'ImportError'>: DLL load failed while importing TechDraw: 
Invalid access to memory location.
```

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 26.3.0dev.20260720 (Git shallow)
Build date: 2026/07/20 16:51:42
Build type: Release
Branch: grafted,grafted
Hash: 057d51f846f535f4f0b48492e586be0a76b9efe2
Python 3.11.14, Qt 6.8.3, Coin 4.0.10 (bundled), Pivy 0.6.11 (bundled), Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , OCC 7.8.1
Locale: Polish/Poland (pl_PL) [ OS: Polish/Poland (pl_PL) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
QPA/File dialog/Color dialog: windows/via Win32/via Qt
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
OpenGL version/vendor/renderer: 4.6.0 NVIDIA 474.82/NVIDIA Corporation/Quadro K4000/PCIe/SSE2
```

**Comment by Roy-043** [comment]
That error is specific to the Windows OS AFAICT. Can't reproduce on Linux.

```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 26.3.0dev.20260720 (Git shallow)
Build date: 2026/07/20 16:51:42
Build type: Release
Branch: grafted,grafted
Hash: 057d51f846f535f4f0b48492e586be0a76b9efe2
Python 3.11.14, Qt 6.8.3, Coin 4.0.10 (bundled), Pivy 0.6.11 (bundled), Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , IfcOpenShell 0.8.0, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/
QPA/File dialog/Color dialog: xcb/non-native/via Qt
Navigation Style/Orbit Style/Rotation Mode: CAD/Trackball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/86.1283/1
OpenGL version/vendor/renderer: 4.5 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.4/AMD/KABINI (, LLVM 15.0.7, DRM 2.50, 6.8.0-134-generic)
Installed mods:
```
