### ISSUE TITLE
Testing with Qt6 misses dialog popups

### ISSUE THREAD

**Issue by Jookia** [FreeCAD/FreeCAD#14840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When running tests with Qt6 some dialogs seem to be missed and thus aren't clicked on. For example, the PartDesignTransformed test from TestPartDesignGui will hang as the second dialog to select the body will not be closed.

```
Testing moving one feature from one body to another
PartDesign::Body: Link(s) to object(s) 'Pad' go out of the allowed scope 'Body'. Instead, the linked object(s) reside within 'Body001 Body001'.
Testing refuse to move the feature with dependencies from one body to another
Testing applying MultiTransform to the Box outside the body
Traceback (most recent call last):
  File "/home/jookia/FreeCAD/build_qt6_reldeb/Mod/PartDesign/TestPartDesignGui.py", line 56, in __call__
    self.test.assertIsNone(diag, "Dialog box could not be found")
  File "/usr/lib/python3.12/unittest/case.py", line 1281, in assertIsNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.12/unittest/case.py", line 715, in fail
    raise self.failureException(msg)
AssertionError: <PySide6.QtWidgets.QDialog(0x7ffdb0dd6050, name="PartDesignGui__DlgActiveBody") at 0x74ac66342340> is not None : Dialog box could not be found
```

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37842 (Git)
Build type: Release
Branch: jookia_testing
Hash: 0f9dcefb3f8a99969117ff60167e6a8fdb26706d
Python 3.12.3, Qt 6.7.1, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.67

(Note: based on 9b547bb90fbdf5f9e6df17fee640566cbe2ab37e)
```

### Subproject(s) affected?

None

### Anything else?

Related to https://github.com/FreeCAD/FreeCAD/issues/13303

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Jookia @bgbsww is this still an issue?
