### ISSUE TITLE
Crash on closing FreeCAD with python debugging on

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#14957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FreeCAD crashes on closing the application. Note that this only occurs when a debug build of Python is used.

To reproduce:

Compile Python with debugging on: 

``` sh
./configure --with-pydebug \
   ...
```

Note that the configure flag `--enable-optimizations` is removed from the Python build.

Build FreeCAD with this Python debug version, start FreeCAD, close FreeCAD.

The output is:

```
Fatal Python error: _PyInterpreterState_GET: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Current thread 0x000076122b346a40 (most recent call first):
  <no Python frame>

Extension modules: FreeCAD, FreeCADGui, pivy._coin, shiboken6.Shiboken, PySide6.QtCore, StartGui, Materials, Part, Measure, MeasureGui, PySide6.QtGui, PySide6.QtWidgets, PySide6.QtNetwork, Sketcher, _PartDesign, MatGui, PartGui, SketcherGui, PartDesignGui (total: 19)
Aborted (core dumped)
```

The backtrace:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff08a8eb3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff0850a30 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff08384c3 in __GI_abort () at abort.c:79
#4  0x00007ffff32a9b6f in fatal_error_exit (status=status@entry=-1) at Python/pylifecycle.c:2737
#5  0x00007ffff32cc28a in fatal_error (fd=2, header=header@entry=1, prefix=prefix@entry=0x7ffff35fe670 <__func__.43.lto_priv.0> "_PyInterpreterState_GET", msg=msg@entry=0x7ffff3611fb8 "the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)", status=status@entry=-1) at Python/pylifecycle.c:2918
#6  0x00007ffff32cc302 in _Py_FatalErrorFunc (func=func@entry=0x7ffff35fe670 <__func__.43.lto_priv.0> "_PyInterpreterState_GET", msg=msg@entry=0x7ffff3611fb8 "the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)") at Python/pylifecycle.c:2934
#7  0x00007ffff32cd240 in _Py_EnsureFuncTstateNotNULL (func=0x7ffff35fe670 <__func__.43.lto_priv.0> "_PyInterpreterState_GET", tstate=<optimized out>) at ./Include/internal/pycore_pystate.h:108
#8  _PyInterpreterState_GET () at ./Include/internal/pycore_pystate.h:131
#9  0x00007ffff32cf73e in _Py_DECREF_DecRefTotal () at Objects/object.c:224
#10 0x00007ffff6c1959d in Py_DECREF (filename=0x7ffff72bad0a "/home/pieter/current/ondsel/freecad-main/src/Gui/ReportView.cpp", lineno=380, op=0x555555ce3608) at /usr/include/python3.12d/object.h:688
#11 0x00007ffff6c1a198 in Gui::DockWnd::ReportOutput::Data::~Data (this=0x555555ce35e0) at /home/pieter/current/ondsel/freecad-main/src/Gui/ReportView.cpp:380
#12 0x00007ffff6c155d6 in Gui::DockWnd::ReportOutput::~ReportOutput (this=0x555555d88e90) at /home/pieter/current/ondsel/freecad-main/src/Gui/ReportView.cpp:460
#13 0x00007ffff6c156b9 in Gui::DockWnd::ReportOutput::~ReportOutput (this=0x555555d88e90) at /home/pieter/current/ondsel/freecad-main/src/Gui/ReportView.cpp:455
#14 0x00007ffff0f8adcb in QObjectPrivate::deleteChildren (this=this@entry=0x555557a28b70) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:2222
#15 0x00007ffff1f33911 in QWidget::~QWidget (this=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidget.cpp:1559
#16 0x00007ffff2058219 in QDockWidget::~QDockWidget (this=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/widgets/widgets/qdockwidget.cpp:1360
#17 QDockWidget::~QDockWidget (this=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/widgets/widgets/qdockwidget.cpp:1360
#18 0x00007ffff0f8adcb in QObjectPrivate::deleteChildren (this=this@entry=0x555555bf6a30) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:2222
#19 0x00007ffff1f33911 in QWidget::~QWidget (this=<optimized out>, this=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidget.cpp:1559
#20 0x00007ffff70aa663 in Gui::MainWindow::~MainWindow (this=0x7fffffffc210) at /home/pieter/current/ondsel/freecad-main/src/Gui/MainWindow.cpp:530
#21 0x00007ffff66534be in Gui::Application::runApplication () at /home/pieter/current/ondsel/freecad-main/src/Gui/Application.cpp:2163
#22 0x000055555557737d in main (argc=1, argv=0x7fffffffd688) at /home/pieter/current/ondsel/freecad-main/src/Main/MainGui.cpp:300
```

Frame 11:

``` c++
375	        }
376	    }
377	    ~Data()
378	    {
379	        if (replace_stdout) {
380	--->      Py_DECREF(replace_stdout);
381	            replace_stdout = nullptr;
382	        }
383	
384	        if (replace_stderr) {
```

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37914 (Git)
Build type: DEBUG
Branch: main
Hash: 6fa8e4ccfbb7e7479521b31910d3c4ed3e6b85ea
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.5.16
```

### Subproject(s) affected?

Core

### Anything else?

The following seems to fix it:

``` diff
diff --git a/src/Gui/ReportView.cpp b/src/Gui/ReportView.cpp
index 6749855f81..d81540f79b 100644
--- a/src/Gui/ReportView.cpp
+++ b/src/Gui/ReportView.cpp
@@ -377,11 +377,13 @@ public:
     ~Data()
     {
         if (replace_stdout) {
+            Base::PyGILStateLocker lock;^M
             Py_DECREF(replace_stdout);
             replace_stdout = nullptr;
         }
 
         if (replace_stderr) {
+            Base::PyGILStateLocker lock;^M
             Py_DECREF(replace_stderr);
             replace_stderr = nullptr;
         }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pieterhijma** [comment]
@wwmayer, since the bug doesn't trigger in a Python build without debugging, I'm not sure what to do here. Should we analyze all decrefs and increfs for holding the GIL or can we simply ignore this because in a non-debug build this is somehow taken care of?

**Comment by Jookia** [comment]
Not locking when touching the interpreter state is a bug and the debug build is just pointing it out. The actual fix is to lock it properly.

**Comment by wwmayer** [comment]
> since the bug doesn't trigger in a Python build without debugging, I'm not sure what to do here

It's clearly a bug. Do you want to make a PR?

> Should we analyze all decrefs and increfs for holding the GIL

Usually the GIL handling is done properly.

> or can we simply ignore this because in a non-debug build this is somehow taken care of?

No, it shouldn't be ignored. I just wonder what's the difference between a Python release and debug in this context.

**Comment by pieterhijma** [comment]
> > since the bug doesn't trigger in a Python build without debugging, I'm not sure what to do here
> 
> It's clearly a bug. Do you want to make a PR?

@Jookia also agrees that it is a bug. One possibility with which I could see it as not being a bug is that an INCREF and DECREF are atomic and therefore not require holding the global lock (also because it seems rather expensive). 

Sure, I'll make a PR.
 
> > Should we analyze all decrefs and increfs for holding the GIL
> 
> Usually the GIL handling is done properly.

Ok.
 
> > or can we simply ignore this because in a non-debug build this is somehow taken care of?
> 
> No, it shouldn't be ignored. I just wonder what's the difference between a Python release and debug in this context.

I assume that the debug release simply has more assertions and looking at the stacktrace, Python segfaults on violating one.

**Comment by wwmayer** [comment]
> One possibility with which I could see it as not being a bug is that an INCREF and DECREF are atomic and therefore not require holding the global lock (also because it seems rather expensive).

INCREF isn't problematic because it only increments the reference counter. But DECREF may do more than decrementing the counter. If the counter reaches 0 it will destroy the object and because we don't know what happens there holding the GIL is mandatory.

**Comment by pieterhijma** [comment]
Right, got it.
