### ISSUE TITLE
Importing SVG (produced by InkScape) fails with "ordinal not in range(128)"

### ISSUE THREAD

**Issue by theosib** [FreeCAD/FreeCAD#15052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:
1. Create an empty document.
2. Select File > Import...
3. Select the attached SVG file.
4. Select to import as geometry

Expected outcome:
- The file gets imported and converted to geometry.

Actual outcome:
The following error:
```
22:13:20  (qt.qpa.fonts) Populating font family aliases took 42 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost. 
22:13:37  pyException: Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/Applications/FreeCAD 2.app/Contents/Resources/Mod/Draft/importSVG.py", line 1788, in insert
    parser.parse(pyopen(filename))
  File "/Applications/FreeCAD 2.app/Contents/Resources/lib/python3.11/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/Applications/FreeCAD 2.app/Contents/Resources/lib/python3.11/xml/sax/xmlreader.py", line 123, in parse
    buffer = file.read(self._bufsize)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/FreeCAD 2.app/Contents/Resources/lib/python3.11/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xe1 in position 2817: ordinal not in range(128)
```

![rune numbers](https://github.com/FreeCAD/FreeCAD/assets/5619995/86e1f5ea-c330-4180-ad71-40347f8a595c)

### Full version info

```shell
OS: macOS 13.6
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git)
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
```

### Subproject(s) affected?

Draft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theosib** [comment]
I'm just making sure that I attached the SVG and not the original PDF, so here is the file again.
![rune numbers](https://github.com/FreeCAD/FreeCAD/assets/5619995/edcd8a72-28b8-493b-b702-136057f37b8a)

**Comment by theosib** [comment]
I also wasn't sure InkScape had converted the text to a path, so I made sure of that. Import fails with the same error. Here's the file with the text as paths.
![rune numbers](https://github.com/FreeCAD/FreeCAD/assets/5619995/bb632770-9b74-4bd2-a2bb-0fd3e80dc3ea)

**Comment by krushia** [comment]
What is the filename? Does it (or the directory it resides in) have any funky characters?

**Comment by krushia** [comment]
Nevermind my prior comment. It is using your locale on import. First time I tried, it imported without error. Then I set LC_ALL=C and confirmed it fails to import.

GOOD:
OS: Gentoo Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git) AppImage
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
**Locale: English/United States (en_US)**



FAIL:
OS: Gentoo Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37928 (Git) AppImage
Build type: Release
Branch: main
Hash: e7699b531eba4bee262f7214699f07b96f66ba7b
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
**Locale: C/Default (C)**

**Comment by Jookia** [comment]
* Related to #9726 ?

**Comment by luzpaz** [comment]
@theosib @krushia  
Can  you try the workaround by @yorikvanhavre in  from https://github.com/FreeCAD/FreeCAD/issues/9726#issuecomment-1578677696 ?

**Comment by krushia** [comment]
`f = pyopen(filename, mode='b')` works here, but this only "fixes" SAX. The string munging (for example in `getContents()`) will still trip up. Either use SAX completely, or ask SAX what the encoding tag is for use in the other places via pyopen(filename, encoding='whateverSaxSaid') and _**hope**_ the underlying system can handle that (dangerous).

**Comment by luzpaz** [comment]
cc @yorikvanhavre :point_up_2:

**Comment by luzpaz** [comment]
@aprospero any chance you can also take a look at this ?

**Comment by FEA-eng** [comment]
For me, the second file works. The first one doesn't cause any errors but it's not visible either. A bunch of labels is created.

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42564 (Git)
Build date: 2025/07/14 18:51:42
Build type: Release
Branch: main
Hash: dc2f2374b6ab3e3381653fad125b1b619bb49f7c
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD_Stylesheet.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

**Comment by FEA-eng** [comment]
What I said above is still valid - only [this file](https://github.com/FreeCAD/FreeCAD/issues/15052#issuecomment-2198409781) works for me.

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/16 20:38:23
Build type: Release
Branch: main
Hash: bac49e465908071e7400a547eb813bc5017ae7dc
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

**Comment by luzpaz** [comment]
Anyone able to work on this (in order to improve compatibility with inkscape) ?

**Comment by ghost** [comment]
@luzpaz I really would like to help but I simply don't get the grasp on what to do here.

Running Python on an ASCII locale is generally a sure road to trouble, but in combination with parsing an svg full of unicode content (runes) it's most certainly bound to failure.

I have no trouble to import the second svg, though. (the one with the paths)

I'm not used to the dos and don'ts regarding locales on a mac, but I would first try to figure out running FreeCAD in an unicode compatible environment when it comes to handle unicode content.

Or did I miss something fundamentally here?

**Comment by luzpaz** [comment]
@aprospero per copilot about your reponse:

<details> <summary>Click to expand</summary>

Yes — that issue description is a correct diagnosis: the import fails because the SVG file contains non-ASCII bytes and the code that hands the file to the XML SAX parser is reading it using the ASCII/text decoder (locale C), which raises a UnicodeDecodeError.

Why this happens
- The stack trace shows the error comes from encodings/ascii.py while reading the file, so the file was opened in text mode with an ASCII decoder (or with a locale that resolves to ascii).
- XML parsers expect either a byte stream (so the parser can detect the XML prolog encoding like <?xml version="1.0" encoding="utf-8"?>) or a text stream opened with the correct encoding.
- The easiest robust fix is to pass a byte stream to the SAX parser (open the file in binary mode) so the expat parser can detect encoding from the XML header, or explicitly open the file with the correct encoding (utf-8).

Suggested minimal fix
Change the parser invocation so the file is opened in binary mode and passed to parser.parse(...). For example, replace:

parser.parse(pyopen(filename))

with:

with open(filename, "rb") as fh:
    parser.parse(fh)

Proposed patch snippet (file: Mod/Draft/importSVG.py)
```python name=Mod/Draft/importSVG.py url=https://github.com/FreeCAD/FreeCAD/blob/main/Mod/Draft/importSVG.py
# --- context ---
# old:
#    parser.parse(pyopen(filename))
#
# new:
    # open the SVG in binary mode so the SAX/Expat parser can detect encoding
    # from the XML prolog (and avoid ASCII decode errors on non-ASCII bytes)
    with open(filename, "rb") as _fh:
        parser.parse(_fh)
# --- end context ---
```

Notes and next steps
- This approach is robust because Expat will read the XML prolog and honor any encoding declared there, or fall back to UTF-8 per XML rules.
- An alternative is to open with encoding="utf-8" (open(filename, "r", encoding="utf-8")), but that requires being sure all SVGs you want to support are UTF-8; using binary mode lets the parser follow the XML spec for encoding detection.

</details>

**Comment by ghost** [comment]
Thank's, @luzpaz for 'let-me-copilot-that for-you'. :)

sure, one could now tackle every minor and major problem arising from using an unsuitable locale - at least it seems that's what AI would do.

Another idea: one could invest some effort and help people make the most out of the features of their favorite operating system.

No, seriously. It is certainly legitimate and honorable to deal with the arising problems individually in order to make the locale completely freely selectable - but I wouldn't be the right guy for that. I don't (want to) know enough about Python and its text conversion intricacies. 
And also I am not an OS X expert. I couldn't design or even test an OSX FreeCAD launch script that could set a user friendly locale.

Just my 2cents. :)
