### ISSUE TITLE
CAM: Helix operation is broken: "Helix: Invalid value for parameter 'direction'"

### ISSUE THREAD

**Issue by knipknap** [FreeCAD/FreeCAD#15643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Any Helix operations are currently broken in 0.22:

Steps to reproduce:
- Open any file with a helix operation that has direction set to CW or CCW.
- Try to edit the operation.
- Note the error on the Helix operation and the traceback in the logs.

Probably caused by #14314.
#15206 may also be related.

### Full version info

```shell
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38334 (Git) AppImage
Build type: Release
Branch: main
Hash: 61c964caa9a7e5bbc7a8d5f7d8914505d365113e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * DynamicData 2.62.0
  * btl 0.9.9
  * WebTools
  * toSketch
  * fasteners 0.4.62
  * lattice2 1.0.0
  * freecad.gears 1.2.0
  * sheetmetal 0.4.23
  * CycloidGearBox
  * parts_library
  * Assembly4 0.12.3
```

### Subproject(s) affected?

CAM/Path

### Anything else?

```
14:41:10  Traceback (most recent call last):
14:41:10    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Base.py", line 251, in pageGetFields
14:41:10      self.getFields(self.obj)
14:41:10    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Helix.py", line 66, in getFields
14:41:10      obj.Direction = str(self.form.direction.currentData())
14:41:10      ^^^^^^^^^^^^^
14:41:10  ValueError: {'sclassname': 'N4Base10ValueErrorE', 'sErrMsg': "'Conventional' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1722018560151/work/src/App/PropertyStandard.cpp', 'iline': 464, 'sfunction': 'virtual void App::PropertyEnumeration::setPyObject(PyObject*)', 'swhat': "'Conventional' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'btranslatable': False, 'breported': False}
14:41:17  Traceback (most recent call last):
14:41:17    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Base.py", line 251, in pageGetFields
14:41:17      self.getFields(self.obj)
14:41:17    File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Gui/Helix.py", line 66, in getFields
14:41:17      obj.Direction = str(self.form.direction.currentData())
14:41:17      ^^^^^^^^^^^^^
14:41:17  ValueError: {'sclassname': 'N4Base10ValueErrorE', 'sErrMsg': "'Climb' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1722018560151/work/src/App/PropertyStandard.cpp', 'iline': 464, 'sfunction': 'virtual void App::PropertyEnumeration::setPyObject(PyObject*)', 'swhat': "'Climb' is not part of the enumeration in ebox_sandwich_v2_3_1#Helix.Direction", 'btranslatable': False, 'breported': False}
14:41:37  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/PathScripts/PathUtils.py", line 70, in new_function
    res = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Base.py", line 826, in execute
    result = self.opExecute(obj)
             ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/CircularHoleBase.py", line 194, in opExecute
    self.circularHoleExecute(obj, holes)
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Op/Helix.py", line 221, in circularHoleExecute
    results = helix.generate(**args)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCA3k1J2v/usr/Mod/CAM/Path/Base/Generator/helix.py", line 100, in generate
    raise ValueError("Invalid value for parameter 'direction'")
<class 'ValueError'>: Invalid value for parameter 'direction'
14:41:37  Helix: Invalid value for parameter 'direction'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by knipknap** [comment]
The issue only happens in files that were created before #14364. The problem is that in these cases FreeCAD doesn't let you edit/fix the operation.

Test file:
[helix-test broken.zip](https://github.com/user-attachments/files/16402875/helix-test.broken.zip)

**Comment by knipknap** [comment]
I'm now pretty sure that this is a duplicate of #15009.
