### ISSUE TITLE
BIM: selecting vertex or an edge of a wall and then Trimex tool generates many errors, puts the program in a unstable state and then crashes at second try

### ISSUE THREAD

**Issue by markit** [FreeCAD/FreeCAD#16139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If I create a wall, select a face and use the Trimex tool (Draft_trimex), I can "extend" one face and change it's geometry.
If I instead select a vertex or an edge of the wall and I click on Trimex tool, after few seconds I have a flood of "<class 'IndexError'>" in the report view bottom window and as soon as I click with the mouse in the 3DView area.
If then I select a face of the wall and use Trimex again, seems to work fine (moving the mouse I can see the future extrusion) but when I click an Extrusion object is created in the Model view with a red exclamation point icon
The mouse cursor  becomes a cross and keeps being so, or becomes so every time I'm over the wall even if I then move away, if I press Esc several time to exit from this situation then the program crashes!
Running AppImage from the shell I have this output, since I can't have the Report View content anymore (but I'm pretty sure is the same)

```shell
./FreeCAD.AppImage 
FreeCAD 0.22.0, Libs: 0.22.0devR38553 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2024
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  XXXXX                 XXXX  XXX   XXXX  
  X                    X      X X   X   X 
  X     XX  XXXX XXXX  X     X   X  X   X 
  XXXX  X X X  X X  X  X     XXXXX  X   X 
  X     X   XXXX XXXX  X    X     X X   X 
  X     X   X    X     X    X     X X   X  XX  XX  XX
  X     X   XXXX XXXX   XXX X     X XXXX   XX  XX  XX

/home/runner/work/FreeCAD-Bundle/FreeCAD-Bundle/conda/linux/AppDir/usr/share/libdrm/amdgpu.ids: File o directory non esistente
Qt: Session management error: None of the authentication protocols specified are supported
<class 'AttributeError'>
<class 'AttributeError'>
  (above line repeated like 50 times)
<class 'AttributeError'>
<class 'AttributeError'>
<class 'RuntimeError'>
<class 'RuntimeError'>
<class 'RuntimeError'>
  (above line repeated like 20 times)
<class 'RuntimeError'>
<class 'RuntimeError'>
Extrusion001: Solids are not Processed
<class 'AttributeError'>
<class 'IndexError'>
  (above line repeated like 200 times)
<class 'IndexError'>
<class 'IndexError'>
<class 'IndexError'>
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAglTrY3/usr/Mod/Draft/draftutils/todo.py", line 140, in doTasks
    f()
TypeError: Tracker._removeSwitch() missing 1 required positional argument: 'switch'

ToDo.doTasks, Unexpected error:
<class 'TypeError'>
in <bound method Tracker._removeSwitch of <draftguitools.gui_trackers.lineTracker object at 0x78c44d104b90>>(None)
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAglTrY3/usr/Mod/Draft/draftutils/todo.py", line 140, in doTasks
    f()
TypeError: Tracker._removeSwitch() missing 1 required positional argument: 'switch'

ToDo.doTasks, Unexpected error:
<class 'TypeError'>
in <bound method Tracker._removeSwitch of <draftguitools.gui_trackers.ghostTracker object at 0x78c44e5ca990>>(None)
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAglTrY3/usr/Mod/Draft/draftutils/todo.py", line 140, in doTasks
    f()
TypeError: Tracker._removeSwitch() missing 1 required positional argument: 'switch'

ToDo.doTasks, Unexpected error:
<class 'TypeError'>
in <bound method Tracker._removeSwitch of <draftguitools.gui_trackers.lineTracker object at 0x78c44ffc49d0>>(None)
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAglTrY3/usr/Mod/Draft/draftutils/todo.py", line 140, in doTasks
    f()
TypeError: Tracker._removeSwitch() missing 1 required positional argument: 'switch'

ToDo.doTasks, Unexpected error:
<class 'TypeError'>
in <bound method Tracker._removeSwitch of <draftguitools.gui_trackers.lineTracker object at 0x78c46cd9f950>>(None)
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAglTrY3/usr/Mod/Draft/draftutils/todo.py", line 140, in doTasks
    f()
TypeError: Tracker._removeSwitch() missing 1 required positional argument: 'switch'

ToDo.doTasks, Unexpected error:
<class 'TypeError'>
in <bound method Tracker._removeSwitch of <draftguitools.gui_trackers.lineTracker object at 0x78c459b0e710>>(None)
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAglTrY3/usr/Mod/Draft/draftutils/todo.py", line 140, in doTasks
    f()
TypeError: Tracker._removeSwitch() missing 1 required positional argument: 'switch'

ToDo.doTasks, Unexpected error:
<class 'TypeError'>
in <bound method Tracker._removeSwitch of <draftguitools.gui_trackers.lineTracker object at 0x78c44d1639d0>>(None)
<class 'IndexError'>
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45250) [0x78c491c45250]
#1  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libpython3.11.so.1.0(+0x2208d7) [0x78c4946208d7]
#2  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x798d) [0x78c4945f87cd]
#3  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libpython3.11.so.1.0(+0x235664) [0x78c494635664]
#4  0x78c49534730e in Gui::View3DInventorPy::eventCallback(void*, SoEventCallback*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x140e
#5  0x78c4916c704e in SoEventCallback::handleEvent(SoHandleEventAction*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0xbe
#6  0x78c4914c5e38 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x68
#7  0x78c49167fcca in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x15a
#8  0x78c4916cfce8 in SoGroup::doAction(SoAction*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x58
#9  0x78c4916eaf8a in SoSeparator::doAction(SoAction*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x2a
#10  0x78c4914c5e38 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x68
#11  0x78c49167fcca in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x15a
#12  0x78c4916cfce8 in SoGroup::doAction(SoAction*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x58
#13  0x78c4916eaf8a in SoSeparator::doAction(SoAction*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x2a
#14  0x78c4914c5e38 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x68
#15  0x78c4914cfa2c in SoHandleEventAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0xac
#16  0x78c4914c6b1a in SoAction::apply(SoNode*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x2ea
#17  0x78c49169bdd2 in SoEventManager::actuallyProcessEvent(SoEvent const*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libCoin.so.80+0x72
#18  0x78c4952edabe in SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x1e
#19  0x78c4952f9058 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x58
#20  0x78c4952e43ed in SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x1fd
#21  0x78c4922b68bb in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Core.so.5+0x7b
#22  0x78c49317039e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Widgets.so.5+0x6e
#23  0x78c493177bdf in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Widgets.so.5+0xd1f
#24  0x78c494f3e3b9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x99
#25  0x78c4922b6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Core.so.5+0x108
#26  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Widgets.so.5(+0x1ca118) [0x78c4931ca118]
#27  0x78c4931703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#28  0x78c494f3e3b9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x99
#29  0x78c4922b6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Core.so.5+0x108
#30  0x78c4929312fb in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Gui.so.5+0xdb
#31  0x78c49290b0bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Gui.so.5+0xac
#32  /tmp/.mount_FreeCAglTrY3/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x64bea) [0x78c48ca1ebea]
#33  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x78c49090dad7]
#34  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x78c490910ac7]
#35  /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x78c4909110ce]
#36  0x78c49230aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Core.so.5+0x66
#37  0x78c4922b570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Core.so.5+0x11b
#38  0x78c4922bd212 in QCoreApplication::exec() from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libQt5Core.so.5+0x82
#39  0x78c494e9f883 in Gui::Application::runApplication() from /tmp/.mount_FreeCAglTrY3/usr/bin/../lib/libFreeCADGui.so+0x983
#40  /tmp/.mount_FreeCAglTrY3/usr/bin/freecad(+0x7620) [0x600ecc652620]
#41  /lib/x86_64-linux-gnu/libc.so.6(+0x2a3b8) [0x78c491c2a3b8]
#42  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x78c491c2a47b]
#43  /tmp/.mount_FreeCAglTrY3/usr/bin/freecad(+0x7981) [0x600ecc652981]
```

### Full version info

```shell
OS: Ubuntu Oracular Oriole (development branch) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git) AppImage
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT)
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markit** [comment]
I discussed this first in the forum, in the meantime I was then creating this issue seems there is a pull request that could fix this
[https://github.com/FreeCAD/FreeCAD/pull/16138](url)
and the forum conversation is in:
[https://forum.freecad.org/viewtopic.php?t=90159](url)
BTW, I forgot to set the "Subproject" part when I created the issue, how can I edit the issue and add it later? If I press the "Edit" button I can't change it, is "read only", no possible selections
