### ISSUE TITLE
Part: Union of 2 solids fails (`'Gui.ViewProviderLink' object has no attribute 'ShapeAppearance'`)

### ISSUE THREAD

**Issue by cropduster32** [FreeCAD/FreeCAD#16227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After creating the Archimedes Fan (by mangojelly) the final fusion of the two solids failed with the error msg "Resulting solid is invalid".
The following is shown in the report view:
```
20:07:35  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/snap/freecad/1123/usr/Mod/Part/BOPTools/BOPFeatures.py", line 88, in make_multi_fuse
    self.copy_visual_attributes(obj, obj.Shapes[0])
  File "/snap/freecad/1123/usr/Mod/Part/BOPTools/BOPFeatures.py", line 106, in copy_visual_attributes
    target.ViewObject.ShapeAppearance = source.ViewObject.ShapeAppearance
<class 'AttributeError'>: 'Gui.ViewProviderLink' object has no attribute 'ShapeAppearance'
20:07:41  Fusion: Resulting shape is invalid
```

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38577 (Git) Snap 1123
Build type: Release
Branch: main
Hash: 2a9cf9e8e6e62086948eb15e24d1e69a54f53d97
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
```

### Subproject(s) affected?

None

### Anything else?

[Archimedes-Fan (FCStd).zip](https://github.com/user-attachments/files/16998982/Archimedes-Fan.FCStd.zip)

Rename zip to FCStd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FEA-eng** [comment]
Can you share the file?

**Comment by luzpaz** [comment]
An aside, looks like the Snap isn't using latest coin 4.0.2

**Comment by cropduster32** [comment]
[Archimedes-Fan (FCStd).zip](https://github.com/user-attachments/files/16998982/Archimedes-Fan.FCStd.zip)

Is this any good? Just change the zip to FCStd

**Comment by FEA-eng** [comment]
Still relevant

**Comment by cropduster32** [comment]
The problem still exists in 1.0.1.

**Comment by luzpaz** [comment]
@cropduster32 @FEA-eng can you pls provide full [About](https://wiki.freecad.org/About) info for the version you tested on ? TIA

**Comment by FEA-eng** [comment]
> [@cropduster32](https://github.com/cropduster32) [@FEA-eng](https://github.com/FEA-eng) can you pls provide full [About](https://wiki.freecad.org/About) info for the version you tested on ? TIA

```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.42605 (Git)
Build date: 2025/07/18 16:20:04
Build type: Release
Branch: main
Hash: da5e18f5d8e7eb4df89c86c9562599435b5c5187
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
```

**Comment by FEA-eng** [comment]
Still relevant

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20260127 (Git shallow)
Build date: 2026/01/27 15:33:30
Build type: Release
Branch: (HEAD detached at 7bcaa76)
Hash: 7bcaa766de101b10c03b4a6f4fd09292068d5ef6
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

**Comment by FEA-eng** [comment]
Still relevant

```
OS: Windows 11 build 26200
Architecture: x86_64
Version: 26.3.0dev.20260804 (Git shallow)
Build date: 2026/08/04 21:26:11
Build type: Release
Branch: (HEAD detached at 80923ab1b)
Hash: 80923ab1be1f31fff0a54db956177d582a658bab
Python 3.11.14, Qt 6.8.3, Coin 4.0.10 (bundled), Pivy 0.6.11 (bundled), Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL) [ OS: Polish/Poland (pl_PL) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
QPA/File dialog/Color dialog: windows/via Win32/via Qt
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
OpenGL version/vendor/renderer: 4.6.0 NVIDIA 610.88/NVIDIA Corporation/NVIDIA GeForce RTX 5080/PCIe/SSE2
```
