### ISSUE TITLE
[Regression] Crash on deleting a feature of a particular file (v1.0RC)

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#16384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

On revision 1.0.0RC1.38643 and 38553, FreeCAD crashes when trying to delete one of the three last items in the tree of the attached file. 
The file was created with Part Design and then "complemented" with Assembly3 objects. The object doesn't show up either in this revisions. Oddly enough it appears as is and doesn't crash on revisions 35966, 37543 and release 0.21.1.

[Bateria.zip](https://github.com/user-attachments/files/16923461/Bateria.zip)

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git) AppImage
Build type: Release
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Installed mods: 
  * fasteners 0.5.27
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xtemp09** [comment]
Here are the backtraces.

<details><summary> Backtraces</summary>


<details><summary>gdb</summary>


```cpp
Thread 1 "FreeCAD" received signal SIGSEGV, Segmentation fault.
App::LinkBaseExtension::getLinkCopyOnChangeValue (this=0x0)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/App/Link.h:246
246         BOOST_PP_SEQ_FOR_EACH(LINK_PROP_GET,_,LINK_PARAMS)
(gdb) bt
#0  App::LinkBaseExtension::getLinkCopyOnChangeValue (this=0x0)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/App/Link.h:246
#1  0x00007ffff535f919 in App::LinkBaseExtension::isLinkMutated (this=this@entry=0x0)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/App/Link.cpp:2233
#2  0x00007ffff7ce5c74 in Gui::ViewProviderLink::onDelete (this=this@entry=0x55555a367bc0)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/ViewProviderLink.cpp:2387
#3  0x00007ffff7cfb1ae in Gui::ViewProviderFeaturePythonT<Gui::ViewProviderLink>::onDelete (this=0x55555a367bc0, sub=std::vector of length 0, capacity 0)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/ViewProviderFeaturePython.h:306
#4  0x00007ffff7962174 in StdCmdDelete::activated (this=<optimized out>, iMsg=<optimized out>)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/CommandDoc.cpp:1409
#5  0x00007ffff7952d4c in Gui::Command::_invoke (this=this@entry=0x555555c4a980, id=id@entry=0, 
    disablelog=<optimized out>) at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/Command.cpp:444
#6  0x00007ffff79533bc in Gui::Command::invoke (this=0x555555c4a980, i=i@entry=0, 
    trigger=trigger@entry=Gui::Command::TriggerAction)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/Command.cpp:408
#7  0x00007ffff793e361 in Gui::Action::onActivated (this=<optimized out>)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/Action.cpp:111
#8  0x00007ffff7947e9a in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**) (f=<optimized out>, o=<optimized out>, arg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#9  0x00007ffff7947ed8 in QtPrivate::FunctionPointer<void (Gui::Action::*)()>::call<QtPrivate::List<>, void>(void (Gui::Action::*)(), Gui::Action*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#10 QtPrivate::QSlotObject<void (Gui::Action::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#11 0x00007ffff2b12e16 in QtPrivate::QSlotObjectBase::call (a=0x7fffffffc520, r=0x555557a9d240, 
    this=0x555557a9d150) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#12 doActivate<false> (sender=0x55555784d170, signal_index=4, argv=0x7fffffffc520) at kernel/qobject.cpp:3925
#13 0x00007ffff2b0b697 in QMetaObject::activate (sender=sender@entry=0x55555784d170, 
    m=m@entry=0x7ffff3c8bc80 <QAction::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fffffffc520) at kernel/qobject.cpp:3985
#14 0x00007ffff3764f94 in QAction::triggered (this=this@entry=0x55555784d170, _t1=<optimized out>)
    at .moc/moc_qaction.cpp:376
#15 0x00007ffff3767eab in QAction::activate (this=0x55555784d170, event=<optimized out>)
    at kernel/qaction.cpp:1161
#16 0x00007ffff799d3ec in Gui::ShortcutManager::onTimer (this=this@entry=0x555555ed1330)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/ShortcutManager.cpp:428
#17 0x00007ffff799e07e in Gui::ShortcutManager::checkShortcut (this=0x555555ed1330, o=<optimized out>, 
    key=...) at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/ShortcutManager.cpp:239
#18 0x00007ffff799e88b in Gui::ShortcutManager::eventFilter (this=0x555555ed1330, o=<optimized out>, 
    ev=<optimized out>) at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/ShortcutManager.cpp:284
#19 0x00007ffff2ad7d5e in QCoreApplicationPrivate::sendThroughApplicationEventFilters (
    this=this@entry=0x5555558c3210, receiver=receiver@entry=0x55555784d170, event=event@entry=0x7fffffffcae0)
    at kernel/qcoreapplication.cpp:1172
#20 0x00007ffff376bd80 in QApplicationPrivate::notify_helper (this=this@entry=0x5555558c3210, 
    receiver=0x55555784d170, e=0x7fffffffcae0, e@entry=0xff7d5857eb72a800) at kernel/qapplication.cpp:3611
#21 0x00007ffff3773547 in QApplication::notify (this=<optimized out>, receiver=<optimized out>, 
    e=0xff7d5857eb72a800, e@entry=0x7fffffffcae0) at kernel/qapplication.cpp:3386
#22 0x00007ffff7915c5c in Gui::GUIApplication::notify (this=0x7fffffffd410, receiver=0x55555784d170, 
    event=0x7fffffffcae0) at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/GuiApplication.cpp:83
#23 0x00007ffff2ad8118 in QCoreApplication::notifyInternal2 (receiver=0x55555784d170, event=0x7fffffffcae0)
    at kernel/qcoreapplication.cpp:1064
#24 0x00007ffff2ad8332 in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
    at kernel/qcoreapplication.cpp:1462
#25 0x00007ffff2f77b3c in QShortcutMap::dispatchEvent (this=<optimized out>, e=<optimized out>)
    at kernel/qshortcutmap.cpp:675
#26 0x00007ffff2f787b3 in QShortcutMap::tryShortcut (this=this@entry=0x5555558c32d8, 
    e=e@entry=0x7fffffffcbb0) at kernel/qshortcutmap.cpp:343
#27 0x00007ffff2f1b512 in QWindowSystemInterface::handleShortcutEvent (window=<optimized out>, 
    window@entry=0x555556fc9590, timestamp=0, keyCode=16777223, modifiers=..., nativeScanCode=119, 
    nativeVirtualKey=65535, nativeModifiers=0, text=..., autorepeat=false, count=1)
    at kernel/qwindowsysteminterface.cpp:477
#28 0x00007ffff2f414d5 in QGuiApplicationPrivate::processKeyEvent (e=0x55555a6f8eb0)
    at kernel/qguiapplication.cpp:2391
#29 0x00007ffff2f17bfc in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...)
    at kernel/qwindowsysteminterface.cpp:1169
#30 0x00007fffeccfcd06 in xcbSourceDispatch (source=source@entry=0x5555557e10e0)
    at qxcbeventdispatcher.cpp:105
#31 0x00007ffff0d145b5 in g_main_dispatch (context=0x7fffe4000ed0) at ../../../glib/gmain.c:3344
#32 0x00007ffff0d73717 in g_main_context_dispatch_unlocked (context=0x7fffe4000ed0)
    at ../../../glib/gmain.c:4152
#33 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffe4000ed0, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4217
#34 0x00007ffff0d13a53 in g_main_context_iteration (context=0x7fffe4000ed0, may_block=1)
    at ../../../glib/gmain.c:4282
#35 0x00007ffff2b35279 in QEventDispatcherGlib::processEvents (this=0x5555557e79f0, flags=...)
    at kernel/qeventdispatcher_glib.cpp:423
#36 0x00007ffff2ad6a7b in QEventLoop::exec (this=this@entry=0x7fffffffcf20, flags=..., flags@entry=...)
    at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#37 0x00007ffff2adf3e8 in QCoreApplication::exec ()
    at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#38 0x00007ffff2f38ecd in QGuiApplication::exec () at kernel/qguiapplication.cpp:1863
#39 0x00007ffff376bcb9 in QApplication::exec () at kernel/qapplication.cpp:2832
#40 0x00007ffff78460b7 in (anonymous namespace)::tryRunEventLoop (mainApp=...)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/Application.cpp:2172
#41 0x00007ffff7846380 in (anonymous namespace)::runEventLoop (mainApp=...)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/Application.cpp:2192
#42 0x00007ffff784a20c in Gui::Application::runApplication ()
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Gui/Application.cpp:2269
#43 0x0000555555571152 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/fyr/Downloads/FreeCAD/freecad-source/src/Main/MainGui.cpp:301
(gdb)
```

</details>


<details><summary>lldb</summary>



```cpp
Process 20064 stopped
* thread #1, name = 'FreeCAD', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x210)
    frame #0: 0x00007ffff7cf3108 libFreeCADGui.so`App::LinkBaseExtension::getLinkCopyOnChangeValue() const + 4
libFreeCADGui.so`App::LinkBaseExtension::getLinkCopyOnChangeValue:
->  0x7ffff7cf3108 <+4>:  movq   0x210(%rdi), %rax
    0x7ffff7cf310f <+11>: movq   0x80(%rax), %rdi
    0x7ffff7cf3116 <+18>: testq  %rdi, %rdi
    0x7ffff7cf3119 <+21>: je     0x7ffff7cf3126 ; <+34>
(lldb) bt
* thread #1, name = 'FreeCAD', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x210)
  * frame #0: 0x00007ffff7cf3108 libFreeCADGui.so`App::LinkBaseExtension::getLinkCopyOnChangeValue() const + 4
    frame #1: 0x00007ffff535f919 libFreeCADApp.so`App::LinkBaseExtension::isLinkMutated() const + 19
    frame #2: 0x00007ffff7ce5c74 libFreeCADGui.so`Gui::ViewProviderLink::onDelete(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&) + 92
    frame #3: 0x00007ffff7cfb1ae libFreeCADGui.so`Gui::ViewProviderFeaturePythonT<Gui::ViewProviderLink>::onDelete(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&) + 50
    frame #4: 0x00007ffff7962174 libFreeCADGui.so`StdCmdDelete::activated(int) + 1726
    frame #5: 0x00007ffff7952d4c libFreeCADGui.so`Gui::Command::_invoke(int, bool) + 424
    frame #6: 0x00007ffff79533bc libFreeCADGui.so`Gui::Command::invoke(int, Gui::Command::TriggerSource) + 198
    frame #7: 0x00007ffff793e361 libFreeCADGui.so`Gui::Action::onActivated() + 27
    frame #8: 0x00007ffff7947e9a libFreeCADGui.so`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**) + 32
    frame #9: 0x00007ffff7947ed8 libFreeCADGui.so`QtPrivate::QSlotObject<void (Gui::Action::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) + 60
    frame #10: 0x00007ffff2b12e16 libQt5Core.so.5`void doActivate<false>(QObject*, int, void**) at qobjectdefs_impl.h:398:57
    frame #11: 0x00007ffff3764f94 libQt5Widgets.so.5`QAction::triggered(bool) at moc_qaction.cpp:376:26
    frame #12: 0x00007ffff3767eab libQt5Widgets.so.5`QAction::activate(QAction::ActionEvent) at qaction.cpp:1161:27
    frame #13: 0x00007ffff799d3ec libFreeCADGui.so`Gui::ShortcutManager::onTimer() + 218
    frame #14: 0x00007ffff799e07e libFreeCADGui.so`Gui::ShortcutManager::checkShortcut(QObject*, QKeySequence const&) + 526
    frame #15: 0x00007ffff799e88b libFreeCADGui.so`Gui::ShortcutManager::eventFilter(QObject*, QEvent*) + 155
    frame #16: 0x00007ffff2ad7d5e libQt5Core.so.5`QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) at qcoreapplication.cpp:1172:33
    frame #17: 0x00007ffff376bd80 libQt5Widgets.so.5`QApplicationPrivate::notify_helper(QObject*, QEvent*) at qapplication.cpp:3611:46
    frame #18: 0x00007ffff7915c5c libFreeCADGui.so`Gui::GUIApplication::notify(QObject*, QEvent*) + 180
    frame #19: 0x00007ffff2ad8118 libQt5Core.so.5`QCoreApplication::notifyInternal2(QObject*, QEvent*) at qcoreapplication.cpp:1064:24
    frame #20: 0x00007ffff2f77b3c libQt5Gui.so.5`QShortcutMap::dispatchEvent(QKeyEvent*) + 428
    frame #21: 0x00007ffff2f787b3 libQt5Gui.so.5`QShortcutMap::tryShortcut(QKeyEvent*) + 131
    frame #22: 0x00007ffff2f1b512 libQt5Gui.so.5`QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) + 402
    frame #23: 0x00007ffff2f414d5 libQt5Gui.so.5`QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) + 149
    frame #24: 0x00007ffff2f17bfc libQt5Gui.so.5`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 172
    frame #25: 0x00007fffeccfcd06 libQt5XcbQpa.so.5`xcbSourceDispatch(_GSource*, int (*)(void*), void*) + 38
    frame #26: 0x00007ffff0d145b5 libglib-2.0.so.0`g_main_dispatch.lto_priv.0 + 501
    frame #27: 0x00007ffff0d73717 libglib-2.0.so.0`g_main_context_iterate_unlocked.isra.0 + 567
    frame #28: 0x00007ffff0d13a53 libglib-2.0.so.0`g_main_context_iteration + 51
    frame #29: 0x00007ffff2b35279 libQt5Core.so.5`QEventDispatcherGlib::processEvents(this=0x00005555557d85b0, flags=<unavailable>) at qeventdispatcher_glib.cpp:423:43
    frame #30: 0x00007ffff2ad6a7b libQt5Core.so.5`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) at qeventloop.cpp:235:22
    frame #31: 0x00007ffff2adf3e8 libQt5Core.so.5`QCoreApplication::exec() at qcoreapplication.cpp:1375:36
    frame #32: 0x00007ffff78460b7 libFreeCADGui.so`(anonymous namespace)::tryRunEventLoop(Gui::GUISingleApplication&) + 383
    frame #33: 0x00007ffff7846380 libFreeCADGui.so`(anonymous namespace)::runEventLoop(Gui::GUISingleApplication&) + 31
    frame #34: 0x00007ffff784a20c libFreeCADGui.so`Gui::Application::runApplication() + 496
    frame #35: 0x0000555555571152 FreeCAD`main + 1747
    frame #36: 0x00007ffff202a1ca libc.so.6`__libc_start_call_main(main=(FreeCAD`main), argc=1, argv=0x00007fffffffda08) at libc_start_call_main.h:58:16
    frame #37: 0x00007ffff202a28b libc.so.6`__libc_start_main_impl(main=(FreeCAD`main), argc=1, argv=0x00007fffffffda08, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffd9f8) at libc-start.c:360:3
    frame #38: 0x0000555555570995 FreeCAD`_start + 37
(lldb)
```


</details>



</details>


```ruby
OS: Ubuntu 24.04.1 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38694 (Git)
Build type: Debug
Branch: master
Hash: 614a14fe87af6ea0a978ee6312b298e4033f1839
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk , OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: //
```

**Comment by chennes** [comment]
I can't run a recompute on this file, it looks like it has some kind of old element map in it? Was this originally an LS3 file?

**Comment by MiqCG** [comment]
I cannot remember precisely with which version it was created. All I know for sure is that at some point it was definitely involved in an Assembly 3 file (it has already the assembly elements).

If I open the file with 0.21.1 and delete the Assembly3 elements (outside the Body), then the file can be opened and recognized in RC1 and RC2.

**Comment by maxwxyz** [comment]
I'll remove the blocker tag then

**Comment by FlachyJoe** [comment]
I can not reproduce (but the given document is broken). Can you please try with current dev?
