### ISSUE TITLE
BIM: It is not possible to add a new wall section if a segment is added to a sketch.

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD#17087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It is impossible to add a new wall section if the wall is built using the wall tool. This problem depends on the direction of building the new section.

1. (Problem) We build a wall and add a segment to the sketch from the bottom up.
2. (Works) We build a wall and add a segment from the top down.
3. (Works) We build a sketch. We make a wall out of it. Further editing does not cause problems for any directions of new sketch segments.
Video demonstration.

https://github.com/user-attachments/assets/d025f819-cabc-4294-85fd-64d07777aef9

UPD/
If the wall is located slightly at an angle to the main axes, then the problem arises in any direction of the new section.

https://github.com/user-attachments/assets/db63df2d-7375-4c15-b08b-edcd156560aa

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38898 (Git) AppImage
Build type: Release
Branch: main
Hash: 32e09d9554db26414697ed19e0189ccab4ea9029
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * lattice2 1.0.0
  * PitchedRoof
  * OpenTheme 2024.9.1
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorikvanhavre** [comment]
Ok confirmed...
The weird thing is, if I edit the sketch again, and move the coincident point, then after that it works...

**Comment by kaiwas** [comment]
> I'm also unable to reproduce that each time. Sometimes yes, sometimes no

I don't know how to help.
But if you have any ideas on how I can perform additional tests, please let me know.

**Comment by semhustej** [comment]
I can confirm the issue too.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38871 (Git)
Build type: Release
Branch: main
Hash: 813ee36cb80e0d29c2c9b991a7b2fee2c61f5cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default

```

**Comment by maxwxyz** [comment]
Is this a regression from 0.21.2 stable?

**Comment by kaiwas** [comment]
> The problem only occurs if the new segment is almost perfectly vertical

probably another example is the roof cutting theme, because there are also a lot of vertical and horizontal lines in the sketcher.

ps. I will be able to test version 0.21.1, but a little later. my computer was taken away by the kids )

**Comment by semhustej** [comment]
I confirm that I am not able to reproduce the issue in 0.21.2 in my quick test.


```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: C/Default (C) [ OS: English/United States (en_US) ]

```

**Comment by paullee0** [comment]
@yorikvanhavre 

Something related to your earlier finding and remark in ArchWall.py ? -

https://github.com/FreeCAD/FreeCAD/blob/a9bff78974f301100134a13c636e23aa91be5bcf/src/Mod/BIM/ArchWall.py#L539

**Comment by paullee0** [comment]
> This is primarily a Sketcher problem. If no new wall segment is added there is a small gap in the sketch. You can verify this by using [Sketcher_ValidateSketch](https://wiki.freecad.org/Sketcher_ValidateSketch).
> 
> The problem only occurs if the new segment is almost perfectly vertical. If you start from the endpoint of the existing segment and hold down Ctrl (angle snap) while creating the vertical segment it happens every time. If you don't snap you need a steady hand to reproduce consistently.
> 
> Creating a perfectly vertical segment in the other direction is less likely, which explains why the problem does not, or very rarely, occurs then.
> 
> Of course it is contradictory that there is a gap at a corner with a coincident constraint. But we see this 'failure to converge' in other cases as well: perfectly horizontal slot and geometry created on top of external geometry are two recent examples that come to mind. I get the idea that the solver sometimes 'thinks' some geometry is already OK and simply stops too early.
> 
> #16239 #16178 https://forum.freecad.org/viewtopic.php?t=91147


I read a few time but do not fully understand :)

But ArchWall should not fail

**Comment by kaiwas** [comment]
> @kaiwas Can you post the 'perfectly' wrong model file, thanks :)

It wasn't difficult )

To check, I opened this file in version 0.21.1 and the wall is also destroyed there.
Remove the zip extension.
[Break_Wall.FCStd.zip](https://github.com/user-attachments/files/17316737/Break_Wall.FCStd.zip)

**Comment by paullee0** [comment]
It happens I created one, finding with below codes:-
```

>>> s=Gui.Selection.getSelection()[0]
>>> s.Shape
<Compound object at 0x55ee6732b130>
>>> s.Shape.Wires
[<Wire object at 0x55ee640c81c0>, <Wire object at 0x55ee6743aaa0>]
>>> s.Shape.Edges
[<Edge object at 0x55ee697f5c70>, <Edge object at 0x55ee67545940>]
>>> cs=Part.getSortedClusters(s.Shape.Edges)
>>> cs
[[<Edge object at 0x55ee6753b6b0>, <Edge object at 0x55ee67357ca0>]]

>>> for e in s.Shape.Edges:
...   print( e.Vertexes[0].Point)
...   print( e.Vertexes[1].Point)
... 
Vector (-74.00718688964844, 7.443048000335693, 0.0)
Vector (850.7616577148438, 41.05305480957031, 0.0)
Vector (699.930176, 878.611023, 0.0)
Vector (850.761658, 41.05305499999997, 0.0)
>>> 
```

Sketch return 2 Edges (as expected), 2 Wires (Unexpected, expected 1 wire), 

Part.getSortedClusters return 1 group of Edges (the 2 edges are connected)

Print the X,Y,Z of the 2 edges, note the 2 end points are slightly off !

Vector (-74.00718688964844, 7.443048000335693, 0.0)
Vector (**850.761657**7148438, **41.0530548**0957031, 0.0)
Vector (699.930176, 878.611023, 0.0)
Vector (**850.761658**, **41.0530549**9999997, 0.0)

**Comment by kaiwas** [comment]
Maybe the sketcher needs a fix like this? To remove the excessive precision.
https://github.com/FreeCAD/FreeCAD/pull/17119

Why doesn't this happen in 0.21? Were there no gaps or was the construction less precise?

**Comment by yorikvanhavre** [comment]
Indeed we can reproduce the problem without BIM so it's a sketcher issue. I'm not sure it has to do with precision, because in @paullee0's example above:

```python
Vector (-74.00718688964844, 7.443048000335693, 0.0)
Vector (850.7616577148438, 41.05305480957031, 0.0)
Vector (699.930176, 878.611023, 0.0)
Vector (850.761658, 41.05305499999997, 0.0)
```
The gap does not seem to be caused by a difference of precision between p1 and p2, but really a different position in space.

I have no idea how to debug this further.. Maybe @AjinkyaDahale or @PaddleStroke have an idea?

**Comment by paullee0** [comment]
@yorikvanhavre  Part maybe part of the problem, as it was shown Part.getSortedClusters() reported the seemingly disconnected edges connected (code and result repeated below).

Maybe I should also check the Sketch.Geometry in the Sketcher if they agreed with the Shape output of the Sketch.Shape.Edges.

```
>>> cs=Part.getSortedClusters(s.Shape.Edges)
>>> cs
[[<Edge object at 0x55ee6753b6b0>, <Edge object at 0x55ee67357ca0>]]

```

**Comment by yorikvanhavre** [comment]
> Maybe I should also check the Sketch.Geometry in the Sketcher if they agreed with the Shape output of the Sketch.Shape.Edges.

The question is if we're able to build a wire from that cluster. If yes, then we could implement a workaround here...

**Comment by paullee0** [comment]
OK, tested.  To answer Yorik's question :
- No, not able to build a wire from cluster
- either by Part.getsortedClusters(s.Shape.Edges)
- nor by Part.getsortedClusters(s.Geometry[0].toShape(), s.Geometry[1].toShape()]
- both return message as ArchWall.py do : "Part.OCCError: BRep_API: command not done"
- both the geometry and edges output by wire indicates they 2 edges are disconnected

So, it seems to me:-
- Sketcher 'end' the coincident constraints algorithm 'too soon' that the 2 ends not yet meet
- Part.getsortedClusters() mistakenly considered those 2 edges as connected
- (But Sketch.Wires return 2 Wires instead of 1 - so 'it' know the coincident constraint is not done yet)


Details of the test -

```
>>> s.Shape.Edges
[<Edge object at 0x564bb59835e0>, <Edge object at 0x564bb6983ea0>]
>>> s.Shape.Wires
[<Wire object at 0x564bb59f34a0>, <Wire object at 0x564bb6974b90>]
>>> cs=Part.getSortedClusters(s.Shape.Edges)
>>> cs
[[<Edge object at 0x564bb59835e0>, <Edge object at 0x564bb59a7ad0>]]
>>> for e in s.Shape.Edges:
...    print( e.Vertexes[0].Point)
...    print( e.Vertexes[1].Point)
... 
Vector (-74.00718688964844, 7.443048000335693, 0.0)
Vector (850.7616577148438, 41.05305480957031, 0.0)
Vector (699.930176, 878.611023, 0.0)
Vector (850.761658, 41.05305499999997, 0.0)
>>> Part.Wire(cs[0])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
Part.OCCError: BRep_API: command not done


>>> s.Geometry
[<Line segment (-74.0072,7.44305,0) (850.762,41.0531,0) >, <Line segment (699.93,878.611,0) (850.762,41.0531,0) >]
>>> sg0=s.Geometry[0]
>>> sg0.StartPoint
Vector (-74.00718688964844, 7.443048000335693, 0.0)
>>> sg0.EndPoint
Vector (850.7616577148438, 41.05305480957031, 0.0)
>>> sg1=s.Geometry[1]
>>> sg1.StartPoint
Vector (699.930176, 878.611023, 0.0)
>>> sg1.EndPoint
Vector (850.761658, 41.05305499999997, 0.0)
>>> 
>>> e0=sg0.toShape()
>>> e1=sg1.toShape()
>>> Part.Wire([e0,e1])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
Part.OCCError: BRep_API: command not done

```

**Comment by yorikvanhavre** [comment]
I think we need the help of a Sketcher specialist. I don't see clearly how easily fixable that is, of if we need to start on a workaround

**Comment by AjinkyaDahale** [comment]
Looks like it's related to #16904.

**Comment by kaiwas** [comment]
I checked the wall construction on the wizard build and it seems the problem is more apparent. (made about 10 attempts)

```
OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git) AppImage
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * lattice2 1.0.0
  * PitchedRoof
  * OpenTheme 2024.9.1

```

**Comment by kaiwas** [comment]
Why does the problem only appear if the wall was created with the wall tool?
If you create a sketch first, and only then a wall - there is no problem. I made more than 10 attempts, but could not get the error.

But as soon as I make a wall, and then correct the sketch - the problem occurs on the first try.


https://github.com/user-attachments/assets/d1e3a198-3cd3-4d0e-8f8a-8bdd29adf3eb

**Comment by paullee0** [comment]
> Why does the problem only appear if the wall was created with the wall tool? If you create a sketch first, and only then a wall - there is no problem. I made more than 10 attempts, but could not get the error.
> 
> But as soon as I make a wall, and then correct the sketch - the problem occurs on the first try.
> vokoscreenNG-2024-10-13_11-36-04.mp4
> 
> Maybe somewhere in the code of the wall tool the order of actions should be changed?

At 16s, could you try not moving the 1st edge before you add the 2nd one?  I think moving the any point in the Sketch 'cure' the problem.  Thanks.

**Comment by kaiwas** [comment]
> At 16s, could you try not moving the 1st edge before you add the 2nd one? I think moving the any point in the Sketch 'cure' the problem. Thanks.

Yes. I just increased the length of the segment because then the wall would be too short.

Okay. Here are 5 more attempts without moving the sketch (I'm sure if there were 20+ of them, everything would be similar)

The 6th attempt I use the wall tool (the problem immediately arises)


https://github.com/user-attachments/assets/bccb8b21-1fba-49a0-a342-d873263226cc

**Comment by paullee0** [comment]
> > At 16s, could you try not moving the 1st edge before you add the 2nd one? I think moving the any point in the Sketch 'cure' the problem. Thanks.
> 
> Yes. I just increased the length of the segment because then the wall would be too short.
> 
> Okay. Here are 5 more attempts without moving the sketch (I'm sure if there were 20+ of them, everything would be similar)
> 
> The 6th attempt I use the wall tool (the problem immediately arises)
> vokoscreenNG-2024-10-13_12-00-25.mp4

Thanks, interesting, though still a Sketcher's problem because under the hood the code just ask Sketcher to add the line.  But your test probably narrow down which code may bring the problem.

@yorikvanhavre, see if this shed some light on this problem.

Thanks all :)

**Comment by kaiwas** [comment]
> I never use the ArchWall intuitive tool to draw Wall, just directLY build a (Arch)Sketch to represent a Arch layout with all the constraints then Wall, CurtainWall, Slab etc. so never experience this problem :LOL

In version 0.21 this problem did not occur.
I also always build a sketch first, and in fact I stumbled upon the problem by accident when we were discussing on the forum "Arch_Remove - is this a toponaming problem?"

**Comment by yorikvanhavre** [comment]
> @yorikvanhavre, see if this shed some light on this problem.

Not really... If you create a wall with the wall tool, then a sketch with only one line, I can't see any difference between the two sketches. I don't know what we should do different here...

As for the way to "cure" the sketch, I see that too, but it just looks to me this forces a recalculation of the entire sketch, and I can't find a way to trigger that from the outside...

**Comment by Roy-043** [comment]
May be solved by #17273?

**Comment by kaiwas** [comment]
> May be solved by #17273?

Checked in weekly build 38991 (October 19th). The issue is not resolved.

**Comment by paullee0** [comment]
Checked git 38991 also, on Fedora 40, not fixed unfortunately :)

```
OS: Fedora Linux 40 (Workstation Edition) (GNOME/gnome/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38991 (Git) AppImage
Build type: Release
Branch: main
Hash: ef2156d0f6d116b1642a5531a2d44fc6b7d17042
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Link to SketchArchLite

```

**Comment by yorikvanhavre** [comment]
I cannot reproduce the problem anymore with current main branch code.

**Comment by luzpaz** [comment]
@yorikvanhavre About info for posterity ?

**Comment by kaiwas** [comment]
I confirm. The issue is not detected in today's build.


https://github.com/user-attachments/assets/ff7796fd-3922-408b-aee0-b16271ca215b



BUT! If I use SketchArch, the issue still reproduces. @paullee0 

https://github.com/user-attachments/assets/c55478d2-6cc2-4f50-89ac-9547e911407e

```
OS: Manjaro Linux (KDE/plasma/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git) AppImage
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Fusion
Installed mods: 
  * lattice2 1.0.0
  * PitchedRoof
  * OpenTheme 2024.9.1
```

**Comment by yorikvanhavre** [comment]
Closing then as it's confirmed fixed by 2 people :)

**Comment by paullee0** [comment]
> I confirm. The issue is not detected in today's build.
> vokoscreenNG-2024-10-22_08-45-25.mp4
> 
> BUT! If I use SketchArch, the issue still reproduces. @paullee0
> vokoscreenNG-2024-10-22_08-43-02.mp4
> 

Unfortunately here, not ok even without SketchArch add-on :)

```
OS: Fedora Linux 40 (Workstation Edition) (GNOME/gnome/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git) AppImage
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

![Screenshot from 2024-10-22 21-55-16](https://github.com/user-attachments/assets/4884f038-0d5e-49dd-90d1-e757b32f3e75)

**Comment by semhustej** [comment]
I can reproduce the issue too. But only if the second segment is **not** perpendicular to the first one. When second segment is perpendicular, everything is OK.


https://github.com/user-attachments/assets/f03ee536-40a3-453c-80f6-a7ea4b13186a


```
18:05:01  pyException: Traceback (most recent call last):
  File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-39024-conda-Windows-x86_64-py311\Mod\BIM\ArchWall.py", line 289, in execute
    extdata = self.getExtrusionData(obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-39024-conda-Windows-x86_64-py311\Mod\BIM\ArchWall.py", line 1042, in getExtrusionData
    w2 = DraftGeomUtils.offsetWire(wire, dvec,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-39024-conda-Windows-x86_64-py311\Mod\Draft\draftgeoutils\offsets.py", line 214, in offsetWire
    wire = Part.Wire(edges)
           ^^^^^^^^^^^^^^^^
<class 'Part.OCCError'>: BRep_API: command not done
18:05:01  Wall: BRep_API: command not done
18:05:01  pyException: Traceback (most recent call last):
  File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-39024-conda-Windows-x86_64-py311\Mod\BIM\ArchWall.py", line 289, in execute
    extdata = self.getExtrusionData(obj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-39024-conda-Windows-x86_64-py311\Mod\BIM\ArchWall.py", line 1042, in getExtrusionData
    w2 = DraftGeomUtils.offsetWire(wire, dvec,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semhu\Documents\tyo\BF\FreeCAD\FC_daily\FreeCAD_weekly-builds-39024-conda-Windows-x86_64-py311\Mod\Draft\draftgeoutils\offsets.py", line 214, in offsetWire
    wire = Part.Wire(edges)
           ^^^^^^^^^^^^^^^^
<class 'Part.OCCError'>: BRep_API: command not done
18:05:01  Wall: BRep_API: command not done

```


```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default

```

**Comment by maxwxyz** [comment]
reopening.
@yorikvanhavre your about info is at an older state than the latest two and the current weekly.

**Comment by kaiwas** [comment]
> Unfortunately here, not ok even without SketchArch add-on :)

This is really true (I confirm). I didn't even have time to rejoice (((

**Comment by Roy-043** [comment]
I can also still reproduce the error.
Note that you should not snap to the grid when testing.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39024 (Git)
Build type: Release
Branch: main
Hash: cf8ad6637351819dfa07d49cfd65d511fe14a084
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

**Comment by yorikvanhavre** [comment]
I still cannot reproduce anymore, snapping to the grid or not...

```
OS: Debian GNU/Linux trixie/sid (GNOME/gnome/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39029 (Git)
Build type: Unknown
Branch: main
Hash: 0b0bb183236b40476bbb5f71dc66561f4ee56f01
Python 3.12.6, Qt 5.15.13, Coin 4.0.2, Vtk 9.3.0, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * dxf-library
  * OpenTheme 2024.7.3
  * parts_library
  * freecad.gears 1.3.0
  * OpenDark 2024.3.13
  * CADExchanger
  * BIM021 2021.12.0
  * ExtremeProDark 2.9.0
```

**Comment by kaiwas** [comment]
> 39029
> Build type: Unknown

We will wait for this version for testing. Thanks for the news.

**Comment by paullee0** [comment]
Same in latest git, AppImage on Fedora 40

```
OS: Fedora Linux 40 (Workstation Edition) (GNOME/gnome/xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git) AppImage
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default

```

![image](https://github.com/user-attachments/assets/cec1c347-d0e2-4aeb-b7eb-86e0df534b2e)

**Comment by semhustej** [comment]
I can also reproduce 100% of time with the second segment not being 90 degrees to the first one.

```
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git)
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default

```

**Comment by yorikvanhavre** [comment]
Ok I could reproduce it too indeed when the base wall's endpoints are not round values (in line with @Roy-043's comment about not snapping).

The crazy thing is, if you create a copy of the "bad" shape with: `Part.show(myWall.Base.Shape.Wires[0])` the copy is a valid wire and making a wall from it works.

**Comment by yorikvanhavre** [comment]
That special case is there for @paullee0 's archsketch... Maybe we can treat that differently?

**Comment by paullee0** [comment]
I am not sure I understand.

Both Sketch and ArchSketch are treated equally.

Do you mean obj.Base.GeometryFacadeList, or Part.getSortedClusters(), is problematic?

If there is a gap between 2 edges, Part.getSortedClusters() still sort them in a cluster for unknown reason, the latter have inherent problem?

**Comment by Roy-043** [comment]
Open the attached file (remove the .zip extension).
Run this code:
```python
sketch = App.ActiveDocument.WallTrace
edges = [geom.Geometry.toShape() for geom in obj.GeometryFacadeList]
for edge in edges:
   [v.Point for v in edge.Vertexes]
```

Result:
```
[Vector (-8.93274016024598, 4.284031046131648, 0.0), Vector (780.8034614747439, 4.284031046131648, 0.0)]
[Vector (780.803461, 4.284031, 0.0), Vector (780.803461, 372.784374, 0.0)]

```

As you can see there is a small gap between the end of the first edge and the start of the second. But the (outward) shape of the sketch is a single wire.

[wall-trace-gap.FCStd.zip](https://github.com/user-attachments/files/18721977/wall-trace-gap.FCStd.zip)

**Comment by paullee0** [comment]
Thanks, there seems to be associated Sketcher and Part.getSortedCluster() problem, random output cases (see details in https://github.com/FreeCAD/FreeCAD/issues/17087#issuecomment-2402994709).

The two (2) edges in Sketch geometry should be **connected with Coincident constraint**. However, in Sketch.Geometry, there is **still gap in the 2 'coincident' vertexes in Geometry**, then :-
 
1. Sketch.Shape.Wires return **2 Wires**
- Wires[0]/[1].Edges return seemingly 'coincident' Vertexes but **with gap**
- But Part.**getSortedCluster() return 1 cluster** (i.e. suggesting 1 wire)
3. Sketch.Shape.Wires return **1 Wire**
- Wires[0].Edges return seemingly 'coincident' Vertexes **but with No gap**
- But Part.**getSortedCluster() return 1 cluster** (i.e. suggesting 1 wire) 

Not sure if any expert in Sketcher and Part.getSortedCluster() is dealing with this.

On our side, we can test the above irregularity and do something.

**Comment by paullee0** [comment]
Add occasion raised up by @psommerfeld on FC Forum -
https://forum.freecad.org/viewtopic.php?p=816741#p816741

**Comment by paullee0** [comment]
After all these cases, I still believe this is Sketcher solver + Part (Part.getSortedCluster() particularly) problem : 
- https://github.com/FreeCAD/FreeCAD/issues/17087#issuecomment-2646047996
- https://github.com/FreeCAD/FreeCAD/issues/17087#issuecomment-2402994709


@PaddleStroke, seems you are on a lot of Sketcher issues, any view?  Or anybody you may suggest?


Thanks in advance.

**Comment by psommerfeld** [comment]
One more project with the same failure, in case it's helpful, at https://forum.freecad.org/viewtopic.php?p=817689#p817689

**Comment by Roy-043** [comment]
For reference: forum topic about using `Part.ShapeFix` to maybe address this issue:
https://forum.freecad.org/viewtopic.php?t=97846

**Comment by paullee0** [comment]
> For reference: forum topic about using `Part.ShapeFix` to maybe address this issue: https://forum.freecad.org/viewtopic.php?t=97846

Interesting, hopefully this be possibly fixed within Sketcher in the first place :)

**Comment by kaiwas** [comment]
@Roy-043 By the way, I had this thought.
If we build a single wall along the X or Y axis, the sketch line will not have horizontal/vertical constraints. If we accidentally click on its top, we can accidentally knock down the orientation along the axis.

What do you think - maybe we should create a separate issue on this topic? (offtopic before bed)

I accidentally broke the horizontal several times when adding new segments

https://github.com/user-attachments/assets/6427531c-b936-4065-948b-cc3e11a943fe

**Comment by Roy-043** [comment]
I don't have a strong opinion about adding hor or ver constraints to WallTrace sketches. If a sketch contains a single unconstrained line it can be manipulated with Draft_Edit. Adding hor or ver constraints would prevent that.

**Comment by Roy-043** [comment]
In the file I have previously posted, https://github.com/FreeCAD/FreeCAD/issues/17087#issuecomment-2645920009, the gap problem can be fixed with this code (in v1.1/v1.2):
```python
doc = App.ActiveDocument
sketch = doc.WallTrace
sketch.touch()
sketch.solve()
doc.recompute()
```
I also get the impression that the gap problem is less likely to occur in v1.1/v1.2.
```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0rc1.20251125 (Git shallow) AppImage
Build date: 2025/11/25 17:53:08
Build type: Release
Branch: (HEAD detached at 5376760)
Hash: 53767601ea65de7cd9f6590e7d5856afc0841635
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/86.1283/1
Installed mods:
```
```
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20251118 (Git shallow)
Build date: 2025/11/18 21:54:51
Build type: Release
Branch: main
Hash: be7d41dea75f7f2966d7b431d24f7060c6907339
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.4, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Turntable/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/86.1283/1
Installed mods:
```

**Comment by kaiwas** [comment]
> I also get the impression that the gap problem is less likely to occur in v1.1/v1.2.

I confirm. I've created a dozen walls using the method described at the beginning, and they all work correctly.

**Comment by Roy-043** [comment]
I think this can be closed then.
