### ISSUE TITLE
CAM: Operation Panel doesn't work when Expression is used for Base or ToolController

### ISSUE THREAD

**Issue by jffmichi** [FreeCAD/FreeCAD#17217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When you use an expression to specify the Base geometry or the ToolController of an operation, the panel to edit the operation fails open correctly.

Steps to reproduce:
open attached file  [operation_expression_issue.zip](https://github.com/user-attachments/files/17351411/operation_expression_issue.zip)
double-click Profile001 or Profile002

Profile001 specifies `<<Profile>>.Base` as Base geometry. Profile002 specifies `<<Profile>>.ToolController` as ToolController. Here is the error log:

```
22:26:51  pyException: Traceback (most recent call last):
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 107, in setEdit
    self.setupTaskPanel(
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 120, in setupTaskPanel
    panel.setupUi()
  File "/usr/lib/freecad/Mod/CAM/Path/Op/Gui/Base.py", line 1245, in setupUi
    val = FreeCAD.Units.Quantity(self.obj.evalExpression(expr))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'TypeError'>: Either quantity, float with units or string expected
```

### Full version info

```shell
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git)
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.12.7, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.2.dev
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Stylesheet/Theme/QtStyle: unset/Classic/breeze
Installed mods: 
  * kicadStepUpMod 11.2.7
  * dodo 1.0.1
  * sheetmetal 0.4.24
  * fcgear 1.0.0
  * fasteners 0.5.27
  * Assembly4 0.50.15
  * Curves 0.6.45
  * lattice2 1.0.0
```

### Subproject(s) affected?

CAM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jffmichi** [comment]
no change, bug still exists

**Comment by jffmichi** [comment]
why do I have to tell that to a machine?... -.-'

**Comment by tarman3** [comment]
Please check #22955
