### ISSUE TITLE
Core: Segfault on Python Console autocompletion

### ISSUE THREAD

**Issue by pieterhijma** [FreeCAD/FreeCAD#17299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Typing a '.' in the Python console opens up a tooltip with the members of an object. When doing that a second time on a specifc object, FreeCAD crashes.

To reproduce:
- Open the Python Console
- Execute the command: `e = OSError()`
- Type 'e' '.' 'm' 'backspace' 'backspace' '.'

<details>
<summary>stacktrace:</summary>
<pre>
#0  PyModule_GetDict (m=0x0) at Objects/moduleobject.c:503
#1  0x00007ffff5d7a95c in Py::Module::getDict (this=0x7fffffffb620) at /home/pieter/current/ondsel/freecad-main/src/CXX/Python3/Objects.hxx:3355
#2  0x00007ffff5d75685 in Gui::CallTipsList::extractTips (this=0x555555e56c60, context=...) at /home/pieter/current/ondsel/freecad-main/src/Gui/CallTips.cpp:208
#3  0x00007ffff5d78542 in Gui::CallTipsList::showTips (this=0x555555e56c60, line=...) at /home/pieter/current/ondsel/freecad-main/src/Gui/CallTips.cpp:513
#4  0x00007ffff5d8aa81 in Gui::PythonConsole::keyPressEvent (this=0x555555e81dc0, e=0x7fffffffc420) at /home/pieter/current/ondsel/freecad-main/src/Gui/PythonConsole.cpp:675
#5  0x00007ffff0d4e444 in QWidget::event (this=0x555555e81dc0, event=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidget.cpp:9076
#6  0x00007ffff0de5d28 in QFrame::event (this=0x555555e81dc0, e=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/widgets/widgets/qframe.cpp:521
#7  0x00007ffff0cfd9cc in QApplicationPrivate::notify_helper (this=this@entry=0x5555559eadd0, receiver=receiver@entry=0x555555e81dc0, e=e@entry=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3287
#8  0x00007ffff0d031f2 in QApplication::notify (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:2706
#9  0x00007ffff5964306 in Gui::GUIApplication::notify (this=0x7fffffffcd20, receiver=0x555555e81dc0, event=0x7fffffffc420) at /home/pieter/current/ondsel/freecad-main/src/Gui/GuiApplication.cpp:93
#10 0x00007fffefd45be8 in QCoreApplication::notifyInternal2 (receiver=0x555555e81dc0, event=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1152
#11 0x00007fffefd45c1a in QCoreApplication::forwardEvent (receiver=<optimized out>, event=<optimized out>, originatingEvent=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1167
#12 0x00007ffff0d66126 in QWidgetWindow::handleGestureEvent (this=<optimized out>, e=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidgetwindow.cpp:1133
#13 QWidgetWindow::event (this=0x55555a4d9ff0, event=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidgetwindow.cpp:337
#14 0x00007ffff0cfd9cc in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x55555a4d9ff0, e=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3287
#15 0x00007ffff5964306 in Gui::GUIApplication::notify (this=0x7fffffffcd20, receiver=0x55555a4d9ff0, event=0x7fffffffc420) at /home/pieter/current/ondsel/freecad-main/src/Gui/GuiApplication.cpp:93
#16 0x00007fffefd45be8 in QCoreApplication::notifyInternal2 (receiver=0x55555a4d9ff0, event=0x7fffffffc420) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1152
#17 0x00007fffefd45c3d in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1607
#18 0x00007ffff0379fc4 in QGuiApplicationPrivate::processKeyEvent (e=0x55555b4e8220) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qguiapplication.cpp:2515
#19 0x00007ffff03e7d24 in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1114
#20 0x00007fffeb2afac7 in xcbSourceDispatch (source=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:57
#21 0x00007fffec90d559 in g_main_dispatch (context=0x7fffe4000f00) at ../glib/glib/gmain.c:3357
#22 0x00007fffec970157 in g_main_context_dispatch_unlocked (context=0x7fffe4000f00) at ../glib/glib/gmain.c:4208
#23 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffe4000f00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4273
#24 0x00007fffec90ca55 in g_main_context_iteration (context=0x7fffe4000f00, may_block=1) at ../glib/glib/gmain.c:4338
#25 0x00007fffeffa985d in QEventDispatcherGlib::processEvents (this=0x5555557fe930, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:394
#26 0x00007fffefd50106 in QEventLoop::processEvents (this=0x7fffffffc7a0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:100
#27 QEventLoop::exec (this=0x7fffffffc7a0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:182
#28 0x00007fffefd4a27d in QCoreApplication::exec () at /usr/src/debug/qt6-base/qtbase/src/corelib/global/qflags.h:74
#29 0x00007ffff57bff01 in (anonymous namespace)::tryRunEventLoop (mainApp=...) at /home/pieter/current/ondsel/freecad-main/src/Gui/Application.cpp:2196
#30 0x00007ffff57c024c in (anonymous namespace)::runEventLoop (mainApp=...) at /home/pieter/current/ondsel/freecad-main/src/Gui/Application.cpp:2216
#31 0x00007ffff57c0604 in Gui::Application::runApplication () at /home/pieter/current/ondsel/freecad-main/src/Gui/Application.cpp:2293
#32 0x00005555555795eb in main (argc=1, argv=0x7fffffffd518) at /home/pieter/current/ondsel/freecad-main/src/Main/MainGui.cpp:295
</pre>
</details>

### Full version info

```shell
OS: Arch Linux (xcb)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38984 (Git)
Build type: Release
Branch: main
Hash: 9806a463246f5a0daf5d87b323ab8c06a97feba2
Python 3.12.7, Qt 6.7.3, Coin 4.0.3, Vtk , OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * OpenTheme 2024.5.16
  * osh-autodoc-workbench 0.2.3
  * Ondsel-Lens 2024.9.13.02
  * fasteners 0.5.29
```

### Subproject(s) affected?

Core

### Anything else?

Reminds me of https://github.com/FreeCAD/FreeCAD/issues/14101 but on first glance it seems unrelated although it is almost the same code.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Is this also happening in the stable 0.21.2?

**Comment by pieterhijma** [comment]
I can't get 0.21.2 to work on my machine anymore (cannot build, package manager only ships release candidates and appimage also doesn't work), so it's difficult for me to check.

**Comment by Roy-043** [comment]
Also occurs in V0.21.2.

**Comment by xtemp09** [comment]
I've failed to reproduce the crash. Is it reproducible with newer bundles?

**Comment by pieterhijma** [comment]
Thanks for bringing this back to my attention. This was fixed by #17302.
