### ISSUE TITLE
Core: Error when typing equation into properties of an object (the syntax isn't interpretted explicitly)

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#17603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

- Open new file
- Create Draft_Circle
- Type '10/2' to the Radius property of the circle and hit 'Enter' 
- FreeCAD shows error after the '/' is typed
```
09:58:28  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'ArithmeticError'>: Not matching Unit!
```

- the value from the equation is calculated properly

See behavior in video:

https://github.com/user-attachments/assets/43716f23-1811-4006-a313-16f250aebff3

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.39057 (Git)
Build type: Release
Branch: main
Hash: 3be681ef62bf82d32eb1f1935d99e83c48e48da3
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

### Subproject(s) affected?

Draft

### Anything else?

I am able to reproduce the issue in FC 0.21.2

I am able to reproduce the issue with other types of objects and different properties (Draft_Rectangle, Arch_Wall)

The error does not limit the functionality of FreeCAD.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
@Roy-043 FYI

**Comment by Roy-043** [comment]
This has nothing to do with Draft. It is a Core issue. Entering `5/2 mm` is interpreted as `5/(2 mm)`. Hence the error message. We see the same issue in the handling of expressions.

**Comment by semhustej** [comment]
The issue is still valid.

**Comment by FlachyJoe** [comment]
> Entering `5/2 mm` is interpreted as `5/(2 mm)`

No, at the end of the video the result is computed correctly. The error appears when the property value is `5/ mm` which give `1/mm` unit. This unit is correctly interpreted by the unit system but isn't valid for a length.

<img width="360" height="183" alt="Image" src="https://github.com/user-attachments/assets/c5d7f6e1-8478-4483-81cd-7326391ecf2d" />

**Comment by semhustej** [comment]
The issue is still valid. 

Note that the original issue is not about the calculation result. It is correct. The issue is about the error message in the report box, which should not pop up in the middle of user typing expression.

The error message:
```

08:31:51  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'ArithmeticError'>: Not matching Unit!
```

```
OS: Debian GNU/Linux 13 (trixie) (GNOME/gnome-xorg/xcb)
Architecture: x86_64
Version: 1.2.0dev.20260429 (Git shallow) AppImage
Build date: 2026/04/29 07:07:16
Build type: Release
Branch: grafted,grafted
Hash: a785d40ac4c37f559b0b82fbaf9bf7dc68a468e4
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/Ireland (en_IE)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: Revit/Turntable/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/158.196/1

```
