### ISSUE TITLE
Segfault when hiding X, Y, or Z axis in Part Design in 1.0.0rc2

### ISSUE THREAD

**Issue by epsilam** [FreeCAD/FreeCAD#17667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to recreate:
1. Create new parametric part
2. In "Model" tab, go to Body > Origin and click hide buttons for X-axis, Y-axis, or Z-axis.
A segfault immediately occurs. 

Below is the terminal output. 
```
$ ./FreeCAD_1.0.0RC2-conda-Linux-x86_64-py311_ee294836a7efe88526646e05db5902b9.AppImage
FreeCAD 1.0.0, Libs: 1.0.0RC2R38806 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

/home/runner/work/FreeCAD-Bundle/FreeCAD-Bundle/conda/linux/AppDir/usr/share/libdrm/amdgpu.ids: No such file or directory
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x71adb9842520]
#1  0x71ad88151fc6 in BRep_Tool::Curve(TopoDS_Edge const&, TopLoc_Location&, double&, double&) from /tmp/.mount_FreeCAr1YmgW/usr/lib/./libTKBRep.so.7.7+0x26
#2  0x71ad88163b21 in BRepAdaptor_Curve::Initialize(TopoDS_Edge const&) from /tmp/.mount_FreeCAr1YmgW/usr/lib/./libTKBRep.so.7.7+0xd1
#3  0x71ad88164d35 in BRepAdaptor_Curve::BRepAdaptor_Curve(TopoDS_Edge const&) from /tmp/.mount_FreeCAr1YmgW/usr/lib/./libTKBRep.so.7.7+0xd5
#4  0x71ad9ced8dce in Measure::Measurement::length() const from /tmp/.mount_FreeCAr1YmgW/usr/lib/Measure.so+0x15e
#5  0x71ad896d0de7 in MeasureGui::QuickMeasure::printResult() from /tmp/.mount_FreeCAr1YmgW/usr/lib/MeasureGui.so+0x947
#6  0x71ad896d19ee in MeasureGui::QuickMeasure::processSelection() from /tmp/.mount_FreeCAr1YmgW/usr/lib/MeasureGui.so+0x1e
#7  /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5(+0x2eb6f2) [0x71adb9eeb6f2]
#8  0x71adb9eef34a in QTimer::timeout(QTimer::QPrivateSignal) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x2a
#9  0x71adb9ee064d in QObject::event(QEvent*) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x7d
#10  0x71adbad703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#11  0x71adbcb69079 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libFreeCADGui.so+0x99
#12  0x71adb9eb6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x108
#13  0x71adb9f09f51 in QTimerInfoList::activateTimers() from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x381
#14  /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5(+0x30a75c) [0x71adb9f0a75c]
#15  /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x71adb8510ad7]
#16  /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x71adb8513ac7]
#17  /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x71adb85140ce]
#18  0x71adb9f0aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x66
#19  0x71adb9eb570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x11b
#20  0x71adb9ebd212 in QCoreApplication::exec() from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libQt5Core.so.5+0x82
#21  0x71adbcac84e1 in Gui::Application::runApplication() from /tmp/.mount_FreeCAr1YmgW/usr/bin/../lib/libFreeCADGui.so+0xa41
#22  /tmp/.mount_FreeCAr1YmgW/usr/bin/freecad(+0x789f) [0x56447d49589f]
#23  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x71adb9829d90]
#24  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x71adb9829e40]
#25  /tmp/.mount_FreeCAr1YmgW/usr/bin/freecad(+0x7c12) [0x56447d495c12]

```

### Full version info

```shell
OS: Pop!_OS 22.04 LTS (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
```

### Subproject(s) affected?

PartDesign

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwxyz** [comment]
Sounds similar to https://github.com/FreeCAD/FreeCAD/issues/17517 can you please try it on the latest weekly if this is already fixed? https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
