### ISSUE TITLE
Freecad hangs on startup

### ISSUE THREAD

**Issue by X-Ryl669** [FreeCAD/FreeCAD#17806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using weekly build 39141, Freecad isn't able to start completely on Mac OS 10.15. 
It loads its GUI and then doesn't respond (round rainbow wheel). It worked fine with previous versions, it's somehow a new issue (previous version I've used was still showing pre 1.0)

I've tried to start it with safe mode (--safe-mode) and it loads but not completely, I can switch workbench, toolbars are updating, but the menu bar is hanging (impossible to quit it them except by force closing).

In the console I have this:
```
During initialization the error "'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)" occurred in freecad.estimateWB
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cyril/Library/Application Support/FreeCAD/Mod/Estimate/./freecad/estimateWB/tools.py", line 99, in __init__
    self.language = json.loads(jsonfile.read().replace('\n', ''))
                               ^^^^^^^^^^^^^^^
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.11/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 235, in InitApplications
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/cyril/Library/Application Support/FreeCAD/Mod/Estimate/./freecad/estimateWB/init_gui.py", line 4, in <module>
    from . import ICONPATH, tools
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.11/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/FreeCAD/Mod/Estimate/./freecad/estimateWB/tools.py", line 105, in <module>
    LANG=language()
         ^^^^^^^^^^
  File "/Users/cyril/Library/Application Support/FreeCAD/Mod/Estimate/./freecad/estimateWB/tools.py", line 102, in __init__
    self.language = json.loads(jsonfile.read().replace('\n', ''))
                               ^^^^^^^^^^^^^^^
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.11/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)
--------------------------------------------------------------------------------
```
 

### Full version info

```shell
Since Freecad doesn't load, I can't get this dialog.
```

### Subproject(s) affected?

Core

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by X-Ryl669** [comment]
Nevermind. The issue was in the Estimate module, I've removed it and it starts up. I don't know if I downloaded this addon and when. Hope it's not required.
