### ISSUE TITLE
Assembly: trying to create BOM results in: `module 'FreeCADGui' has no attribute 'doCommandEval'` (works on weekly therefore missing backport)

### ISSUE THREAD

**Issue by josegs1974** [FreeCAD/FreeCAD#17882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When i try to create a BOM in the assembly workbench this error occurred:
```python
15:23:58  Running the Python command 'Assembly_CreateBom' failed:
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAOOlfbL/usr/Mod/Assembly/CommandCreateBom.py", line 94, in Activated
    self.panel = TaskAssemblyCreateBom()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAOOlfbL/usr/Mod/Assembly/CommandCreateBom.py", line 146, in __init__
    self.createBomObject()
  File "/tmp/.mount_FreeCAOOlfbL/usr/Mod/Assembly/CommandCreateBom.py", line 337, in createBomObject
    self.bomObj = Gui.doCommandEval("bomObj")
                  ^^^^^^^^^^^^^^^^^

module 'FreeCADGui' has no attribute 'doCommandEval'
```
In version 1.0 RC2 i don't have this issue.

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Portuguese/Portugal (pt_PT)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * CurvedShapes 1.0.13
  * fasteners 0.5.29
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Assembly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Can you share a file (zip it and drag-drop into github textbox, please) TIA!

**Comment by luzpaz** [comment]
@PaddleStroke have you see this before ?

**Comment by MansourMohamedAli** [comment]
I see the same Issue on RC4.

**Comment by luzpaz** [comment]
@MansourMohamedAli please update your post with full [About](https://wiki.freecad.org/About) info. TIA

**Comment by PaddleStroke** [comment]
I can't replicate this issue. But I have not tested RC4
Can someone replicate in the current main branch?
This could be a backport issue

**Comment by FEA-eng** [comment]
Also reported here: https://forum.freecad.org/viewtopic.php?t=92063&start=10#p791859

**Comment by luzpaz** [comment]
@josegs1974 can you test on weekly ? https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by josegs1974** [comment]
On latest weekly build the issue is not present.

**Comment by luzpaz** [comment]
> This could be a backport issue

It is @PaddleStroke what needs to be backported ?
