### ISSUE TITLE
CAM: Changing fillet radius messes up CAM operations (Toponaming bug)

### ISSUE THREAD

**Issue by chaotix-** [FreeCAD/FreeCAD#17924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When changing the radius of a fillet I get a lot of errors (see below for the first one). Afterwards the the features are missing from CAM operations and I cannot add them again. Also the tool controller drop down list is empty and I cannot select a tool controller for this CAM operation anymore. Furthermore the undo operation does not recover from this problem. All I can do is delete the affected CAM operations and readd them.

To reproduce:
 1. Open this file: [Garderobe-prefillet.zip](https://github.com/user-attachments/files/17790120/Garderobe-prefillet.zip)
 2. Select "Fillet" in the model tree and change the fillet radius to 5mm.

Afterwards most of my CAM operations are affected and I have to delete them and redo everything:
![messedupcam](https://github.com/user-attachments/assets/bedacf76-2d21-4912-a486-3fe181fa2e87)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (xcb)
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.30
  * A2plus 0.4.68
  * Assembly4 0.50.15
```

### Subproject(s) affected?

CAM

### Anything else?

```
12:03:50  <PropertyLinks> PropertyLinks.cpp(447): Garderobe_prefillet#Profile002.Base missing element reference Garderobe_prefillet#Clone ;Face1;:H51b,F;:H4f3:8,F.Face1
12:03:50  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAfIHjno/usr/Mod/CAM/Path/Op/Base.py", line 527, in onChanged
    if prop == "Base" and self.sanitizeBase(obj):
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAfIHjno/usr/Mod/CAM/Path/Op/Base.py", line 709, in sanitizeBase
    o.Shape.getElement(sub)
<class 'ValueError'>: {'sclassname': 'N4Base10ValueErrorE', 'sErrMsg': 'Invalid shape name ?Face1', 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1731546400676/work/src/Mod/Part/App/TopoShapeExpansion.cpp', 'iline': 2019, 'sfunction': 'Part::TopoShape Part::TopoShape::getSubTopoShape(const char*, bool) const', 'swhat': 'Invalid shape name ?Face1', 'btranslatable': False, 'breported': False}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Hi @jbaehr can you reproduce this ?

**Comment by J-Dunn** [comment]
Yes. This is not specific to fillets but fillets add new faces and edges and removing them renumbers everything in sight and destroys all path ops'  Base Geometry settings. 

Classic Topo cluster bomb.

**Comment by J-Dunn** [comment]
Of course this bug still applies since the underlying issue has not been resolved. 

I just tested on recent master. I had cylindrical hole with a helical path on base geom  Model-Body.Face7 which corresponds to Body.Pocket.Face7 in the actual model. 
I added a 1mm fillet to intersection of the cylinder and the plate, this seemed OK.
After adding the first fillet to the cylinder the hole inner face gets renamed: cylinder_test.Body.Fillet.Face7

Helix path geom is  Model-Body.Face7
At this point the Helix path still works.

I then I added a fillet to top edge of the hole. It crapped out with a ton of errors on the helix path. 
Adding a 1mm fillet to this edge makes a mess in report window as shown. 

Now the top edge of the cylindrical hole is called: cylinder_test.Body.Fillet.Edge6

Inspection shows that cylinder_test.Body.Fillet.Face7 got renamed as  cylinder_test.Body.Fillet001.Face8
The fillet is created but paths in model were broken during the automatic re-computation due to the same topo instability problem.

Examining the base geom in the path editor shows it is now empty. 

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/6c4017f3-586e-42c9-a75e-101324ad8a64" />

**Comment by tarman3** [comment]
I have solution which not resolve the toponaming problem, but at least exclude Python errors and do Task panel usable
So user can remove from base list incorrect shapes and set new 
- #27559
