### ISSUE TITLE
CAM: Problems with deburr path / Wrong section of circle is cut.

### ISSUE THREAD

**Issue by chaotix-** [FreeCAD/FreeCAD#17925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I want to deburr a couple of edges. If I select all of them I get a traceback (see below). If I select a specific subsection of the edges the generated path cuts along the wrong section of the circle.

Steps to reproduce the error message:
Open the following file: [Garderobe-deburr.zip](https://github.com/user-attachments/files/17790159/Garderobe-deburr.zip)

To generate the error message below select the following edges and generate a deburr operation:
![deburr-complete](https://github.com/user-attachments/assets/00919daa-f7c1-4fbf-a57b-7312b71d7cf2)

To generate the wrong path section of a round edge select the following edges and generate a deburr operation:
![deburr-wrongcircleselection](https://github.com/user-attachments/assets/9bdbe3c1-9473-404f-8c65-27350edafa10)
This generates the following path:
![deburr-wrongcircleresult](https://github.com/user-attachments/assets/f973d97b-fb22-41ec-a326-a2d80a622c9e)

With the following edges the path is correct (except the not selected edge is missing):
![deburr-ok](https://github.com/user-attachments/assets/fa1c270c-51b0-4236-8721-52ef7f976465)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (xcb)
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.30
  * A2plus 0.4.68
  * Assembly4 0.50.15
```

### Subproject(s) affected?

CAM

### Anything else?

12:29:11  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAfIHjno/usr/Mod/CAM/PathScripts/PathUtils.py", line 70, in new_function
    res = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAfIHjno/usr/Mod/CAM/Path/Op/Base.py", line 788, in execute
    result = self.opExecute(obj)
             ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAfIHjno/usr/Mod/CAM/Path/Op/Deburr.py", line 380, in opExecute
    wire = PathOpUtil.offsetWire(w, base.Shape, offset, True, side)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAfIHjno/usr/Mod/CAM/Path/Op/Util.py", line 287, in offsetWire
    owire = orientWire(wire.makeOffset2D(offset), True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'ValueError'>: {'sclassname': 'N4Part18NullShapeExceptionE', 'sErrMsg': 'makeOffset2D: result of offsetting is null!', 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1731546400676/work/src/Mod/Part/App/TopoShapeExpansion.cpp', 'iline': 2773, 'sfunction': 'Part::TopoShape& Part::TopoShape::makeElementOffset2D(const Part::TopoShape&, double, Part::JoinType, Part::FillType, Part::OpenResult, bool, const char*)', 'swhat': 'makeOffset2D: result of offsetting is null!', 'btranslatable': False, 'breported': False}
12:29:11  Deburr002: {'sclassname': 'N4Part18NullShapeExceptionE', 'sErrMsg': 'makeOffset2D: result of offsetting is null!', 'sfile': '/home/conda/feedstock_root/build_artifacts/freecad_1731546400676/work/src/Mod/Part/App/TopoShapeExpansion.cpp', 'iline': 2773, 'sfunction': 'Part::TopoShape& Part::TopoShape::makeElementOffset2D(const Part::TopoShape&, double, Part::JoinType, Part::FillType, Part::OpenResult, bool, const char*)', 'swhat': 'makeOffset2D: result of offsetting is null!', 'btranslatable': False, 'breported': False}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
~Probably can be fixed by #23331~

<img width="466" height="264" alt="Image" src="https://github.com/user-attachments/assets/48ef9b4d-496a-4de4-b30c-7b122495844d" />

**Comment by chaotix-** [comment]
Problem is still there with FreeCAD_weekly-2025.08.27-Linux-x86_64-py311.AppImage.

Although the error message from the first case is slightly different and it FreeCAD stalls for about 30 seconds while trying to generate the deburr operation.

```
20:54:27  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAdfODfl/usr/Mod/CAM/PathScripts/PathUtils.py", line 70, in new_function
    res = function(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAdfODfl/usr/Mod/CAM/Path/Op/Base.py", line 790, in execute
    result = self.opExecute(obj)
             ^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAdfODfl/usr/Mod/CAM/Path/Op/Deburr.py", line 380, in opExecute
    wire = PathOpUtil.offsetWire(w, base.Shape, offset, True, side)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAdfODfl/usr/Mod/CAM/Path/Op/Util.py", line 287, in offsetWire
    owire = orientWire(wire.makeOffset2D(offset), True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'ValueError'>: makeOffset2D: result of offsetting is null!
20:54:27  Deburr: makeOffset2D: result of offsetting is null!
```

**Comment by tarman3** [comment]
PR https://github.com/FreeCAD/FreeCAD/pull/23331 not merged and probably will not be, because this is too dirty
So probably the problem will be present at least next several month

For your own test you can try this [experimental build](https://github.com/tarman3/FreeCAD/releases)

**Comment by FEA-eng** [comment]
@tarman3 So the issue is still relevant, right?

**Comment by tarman3** [comment]
Yes, still relevant
I don't want to get into this problem right now and near future
This rabbit hole is to deep ))

**Comment by FEA-eng** [comment]
I assume it's still relevant

**Comment by tarman3** [comment]
`makeOffset2D()` can not create offset for this wire

> <class 'ValueError'>: makeOffset2D: result of offsetting is null!

[open_profile_test (1).zip](https://github.com/user-attachments/files/25032341/open_profile_test.1.zip)

<img width="725" height="325" alt="Image" src="https://github.com/user-attachments/assets/0b27778e-6df7-4820-a67e-a1c0f348d446" />

```
import FreeCAD
import Part

obj = FreeCAD.ActiveDocument.getObject("Body")
names = ("Edge1", "Edge5", "Edge7")
edges = obj.getSubObject(names)
wire = Part.Wire(edges)
Part.show(wire)
offsetWire = wire.makeOffset2D(offset=2, join=0, openResult=False)
Part.show(offsetWire)
```
