### ISSUE TITLE
Assembly: deleting a flexible sub-assembly doesn't delete the connecting joint with parent assembly

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#17929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Since pull request [15798](https://github.com/FreeCAD/FreeCAD/pull/15798 ) related joints of an assembly are deleted at the same time that a component is deleted.
Looks like this is not happening with subassemblies.

https://github.com/user-attachments/assets/e181991e-d68f-4587-88a5-0cd69deff32a

When trying to edit the orphan joint, this error appears in the report view:
```
19:29:25  42526 Selection.cpp(1522): Sub-object Assembly#Assembly.SubAssembly2._10_003.Edge50 not found
19:29:25  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAcogaME/usr/Mod/Assembly/JointObject.py", line 921, in doubleClicked
    panel = TaskAssemblyCreateJoint(0, vobj.Object)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAcogaME/usr/Mod/Assembly/JointObject.py", line 1226, in __init__
    self.updateTaskboxFromJoint()
  File "/tmp/.mount_FreeCAcogaME/usr/Mod/Assembly/JointObject.py", line 1593, in updateTaskboxFromJoint
    self.updateJointList()
  File "/tmp/.mount_FreeCAcogaME/usr/Mod/Assembly/JointObject.py", line 1607, in updateJointList
    sname = UtilsAssembly.getObject(ref).Label
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'NoneType' object has no attribute 'Label'
```

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.0.0RC4.39104 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc4)
Hash: 83646753e051eaf438c0d5e9351cb57bd27377ab
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Assembly

### Anything else?

[Subassemblies.zip](https://github.com/user-attachments/files/17791898/Subassemblies.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaddleStroke** [comment]
Happens only for flexible subassemblies
