### ISSUE TITLE
Assembly: Access Violation error when undo while setting up joint

### ISSUE THREAD

**Issue by Fabi019** [FreeCAD/FreeCAD#18128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

It is possible to trigger an Access Violation error while in the Assembly workbench, that prevents saving from working (also alot of other things stop working) and requires a restart of FreeCAD to get rid of the errors.
To reproduce: While in the configuration menu of a joint (doesn't matter which type) and two faces have been selected, instead of OK or cancel Undo must be pressed. This closes the configuration menu but also causes the error for every following operation.

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion

---

OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.39287 (Git) Conda
Build type: Release
Branch: main
Hash: b5a43eb2208b91feb76b2cc363e3956922c3ad75
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Assembly

### Anything else?

Possibly releated: https://forum.freecad.org/viewtopic.php?p=792934

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiqCG** [comment]
Hi, @Fabi019 ,
I was trying to reproduce the bug you found but I couldn't. I have tried the Undo and Ctrl-z while editing an already existing Fixed joint. Would it have to be triggered in this situation?

Can you provide a simple test file or more details for reproducing it?


```
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.1.0dev.39287 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: b5a43eb2208b91feb76b2cc363e3956922c3ad75
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion

```

**Comment by Fabi019** [comment]
Hi @MiqCG,
Thanks for testing out, it seems to only trigger the bug when configuring a new joint that doesn't exist yet. Here is a video of how it looks on my side:

https://github.com/user-attachments/assets/cc38532e-4841-4194-9242-dda048adc639

**Comment by MiqCG** [comment]
Yes, I can confirm that the bug exists in revision 39287 (with the output below) **but not with** revision 39315. Give a try to the new Appimage.


Report view
```
21:38:08  <Exception> invalid container
21:38:08  <App> Transactions.cpp(196): Exception on undo 'Create Fixed Joint':invalid container
21:38:08  pyException: Traceback (most recent call last):
  File "/tmp/.mount_FreeCAChbpBe/usr/Mod/Assembly/JointObject.py", line 1335, in autoClosedOnTransactionChange
    self.reject()
  File "/tmp/.mount_FreeCAChbpBe/usr/Mod/Assembly/JointObject.py", line 1328, in reject
    self.deactivate()
  File "/tmp/.mount_FreeCAChbpBe/usr/Mod/Assembly/JointObject.py", line 1352, in deactivate
    UtilsAssembly.setJointsPickableState(self.doc, True)
  File "/tmp/.mount_FreeCAChbpBe/usr/Mod/Assembly/UtilsAssembly.py", line 822, in setJointsPickableState
    setPickableState(obj, state)
  File "/tmp/.mount_FreeCAChbpBe/usr/Mod/Assembly/UtilsAssembly.py", line 811, in setPickableState
    vobj = obj.ViewObject
           ^^^^^^^^^^^^^^
<class 'RuntimeError'>: Object has been removed from document
```

```
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

**Comment by Fabi019** [comment]
> Yes, I can confirm that the bug exists in revision 39287 (with the output below) **but not with** revision 39315. Give a try to the new Appimage.

👍 Looks like it was fixed in the newest dev build

**Comment by Benbarian** [comment]
Same issue here. Access Violation after undoing while Assembly WB using the Fixed Joint tool. Have closed adn opened the file multiple times, happens every time after a few joint procedures. 
Can't save to share the file because Access Violation. 


> OS: Windows 11 build 22631
> Architecture: x86_64
> Version: 1.0.0.39109 (Git) Conda
> Build type: Release
> Branch: (HEAD detached at 1.0.0)
> Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
> Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
> Locale: English/South Africa (en_ZA)
> Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
> Installed mods: 
>   * 3D_Printing_Tools
>   * fasteners 0.5.38
>   * OpenTheme 2024.9



`16:16:35  You need to select 2 elements from 2 separate parts.<Exception> invalid container
16:30:34  <App> Transactions.cpp(187): Exception on undo 'Create Fixed Joint':invalid container
16:30:34  pyException: Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1333, in autoClosedOnTransactionChange
    self.reject()
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1326, in reject
    self.deactivate()
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1350, in deactivate
    UtilsAssembly.setJointsPickableState(self.doc, True)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\UtilsAssembly.py", line 822, in setJointsPickableState
    setPickableState(obj, state)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\UtilsAssembly.py", line 811, in setPickableState
    vobj = obj.ViewObject
           ^^^^^^^^^^^^^^
<class 'RuntimeError'>: Object has been removed from document
16:30:36  <Exception> invalid container
16:30:36  <App> Transactions.cpp(187): Exception on undo 'Insert Component':invalid container
16:32:03  Running the Python command 'Assembly_CreateJointFixed' failed:
Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 103, in Activated
    activateJoint(0)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 61, in activateJoint
    panel = TaskAssemblyCreateJoint(index)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1289, in __init__
    UtilsAssembly.setJointsPickableState(self.doc, False)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\UtilsAssembly.py", line 822, in setJointsPickableState
    setPickableState(obj, state)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\UtilsAssembly.py", line 811, in setPickableState
    vobj = obj.ViewObject
           ^^^^^^^^^^^^^^

Object has been removed from documentRunning the Python command 'Assembly_CreateJointFixed' failed:
Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 103, in Activated
    activateJoint(0)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 59, in activateJoint
    JointObject.activeTask.reject()
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1326, in reject
    self.deactivate()
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1348, in deactivate
    self.view.removeEventCallback("SoLocation2Event", self.callbackMove)
                                                      ^^^^^^^^^^^^^^^^^

'TaskAssemblyCreateJoint' object has no attribute 'callbackMove'Running the Python command 'Assembly_CreateJointFixed' failed:
Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 103, in Activated
    activateJoint(0)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 61, in activateJoint
    panel = TaskAssemblyCreateJoint(index)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1289, in __init__
    UtilsAssembly.setJointsPickableState(self.doc, False)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\UtilsAssembly.py", line 822, in setJointsPickableState
    setPickableState(obj, state)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\UtilsAssembly.py", line 811, in setPickableState
    vobj = obj.ViewObject
           ^^^^^^^^^^^^^^

Object has been removed from documentRunning the Python command 'Assembly_CreateJointFixed' failed:
Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 103, in Activated
    activateJoint(0)
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\CommandCreateJoint.py", line 59, in activateJoint
    JointObject.activeTask.reject()
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1326, in reject
    self.deactivate()
  File "C:\Program Files\FreeCAD 1.0\Mod\Assembly\JointObject.py", line 1348, in deactivate
    self.view.removeEventCallback("SoLocation2Event", self.callbackMove)
                                                      ^^^^^^^^^^^^^^^^^

'TaskAssemblyCreateJoint' object has no attribute 'callbackMove'pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: Access violation
16:32:25  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: Access violation
16:32:27  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: Access violation
16:34:40  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'OSError'>: Access violation
`
