### ISSUE TITLE
Assembly: crash when dragging Rack and Pinion joint

### ISSUE THREAD

**Issue by MiqCG** [FreeCAD/FreeCAD#18163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Trying to confirm issue #16547 , I get into a crash when dragging a Rack and Pinion joint in Assembly WB. 
See screencast, attached assembly file and terminal output below. Maybe the test file is wrongly executed but anyway I guess it wouldn't have to provoke a crash. It crashes if you drag from the slider, too.
Tested with 1.0.0.39109 and 1.1.0dev.39315 appimages, with newly deleted .config .cache and .local/share FreeCAD folders.
I suspect that crashes occur with Gear/Belt joint too; I will try later and open a different issue.

```
./FreeCAD_1.0.0-conda-Linux-x86_64-py311.AppImage 
FreeCAD 1.0.0, Libs: 1.0.0R39109 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

1.07e-07 <Assembly> AssemblyObject.cpp(176): Solve failed: Rack pinion radius is zero.
0.0287631 <Assembly> AssemblyObject.cpp(176): Solve failed: Rack pinion radius is zero.
0.0288627 <App> Document.cpp(2903): Rack_negative#Joint still touched after recompute
0.0289362 <App> Document.cpp(2903): Rack_negative#Joint001 still touched after recompute
0.0289941 <App> Document.cpp(2903): Rack_negative#Joint002 still touched after recompute
43.4667 <Assembly> AssemblyObject.cpp(176): Solve failed: Rack pinion radius is zero.
43.4818 <Assembly> AssemblyObject.cpp(176): Solve failed: Rack pinion radius is zero.
43.4819 <App> Document.cpp(2903): Rack_negative#Joint still touched after recompute
43.482 <App> Document.cpp(2903): Rack_negative#Joint001 still touched after recompute
43.482 <App> Document.cpp(2903): Rack_negative#Joint002 still touched after recompute
49.8546 <Assembly> AssemblyObject.cpp(176): Solve failed: Rack pinion radius is zero.
Unhandled std exception in ViewProvider::eventCallback: Rack pinion radius is zero.
(Event type: SoLocation2Event, object type: AssemblyGui::ViewProviderAssembly)
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f39ede5b050]
#1  0x7f3986400339 in MbD::ConstraintSet::constraintsDo(std::function<void (std::shared_ptr<MbD::Constraint>)> const&) from /tmp/.mount_FreeCAhAGfCM/usr/lib/./libOndselSolver.so.1+0x59
#2  0x7f39864cb8ca in MbD::Joint::jointForceI() from /tmp/.mount_FreeCAhAGfCM/usr/lib/./libOndselSolver.so.1+0xea
#3  0x7f39864cb93e in MbD::Joint::aFX() from /tmp/.mount_FreeCAhAGfCM/usr/lib/./libOndselSolver.so.1+0x1e
#4  0x7f3986386fa2 in MbD::ASMTConstraintSet::updateFromMbD() from /tmp/.mount_FreeCAhAGfCM/usr/lib/./libOndselSolver.so.1+0x72
#5  0x7f39863777cd in MbD::ASMTAssembly::updateFromMbD() from /tmp/.mount_FreeCAhAGfCM/usr/lib/./libOndselSolver.so.1+0xdd
#6  0x7f398637f8b7 in MbD::ASMTAssembly::runDragStep(std::shared_ptr<std::vector<std::shared_ptr<MbD::ASMTPart>, std::allocator<std::shared_ptr<MbD::ASMTPart> > > >) from /tmp/.mount_FreeCAhAGfCM/usr/lib/./libOndselSolver.so.1+0x517
#7  0x7f39ad0cece5 in Assembly::AssemblyObject::doDragStep() from /tmp/.mount_FreeCAhAGfCM/usr/lib/AssemblyApp.so+0x465
#8  0x7f39acb45ced in AssemblyGui::ViewProviderAssembly::tryMouseMove(SbVec2s const&, Gui::View3DInventorViewer*) from /tmp/.mount_FreeCAhAGfCM/usr/lib/AssemblyGui.so+0x35d
#9  0x7f39acb466ec in AssemblyGui::ViewProviderAssembly::mouseMove(SbVec2s const&, Gui::View3DInventorViewer*) from /tmp/.mount_FreeCAhAGfCM/usr/lib/AssemblyGui.so+0x1c
#10  0x7f39f13b46a0 in Gui::ViewProvider::eventCallback(void*, SoEventCallback*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x400
#11  0x7f39ed8d346e in SoEventCallback::handleEvent(SoHandleEventAction*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0xbe
#12  0x7f39ed6d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x68
#13  0x7f39ed88cb9a in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0xea
#14  0x7f39ed8dc348 in SoGroup::doAction(SoAction*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x58
#15  0x7f39ed8f713a in SoSeparator::doAction(SoAction*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x2a
#16  0x7f39ed6d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x68
#17  0x7f39ed88cb9a in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0xea
#18  0x7f39ed8dc348 in SoGroup::doAction(SoAction*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x58
#19  0x7f39ed8f713a in SoSeparator::doAction(SoAction*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x2a
#20  0x7f39ed6d54e8 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x68
#21  0x7f39ed6df26c in SoHandleEventAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0xac
#22  0x7f39ed6d61ba in SoAction::apply(SoNode*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x2ea
#23  0x7f39ed8a8ad2 in SoEventManager::actuallyProcessEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libCoin.so.80+0x72
#24  0x7f39f133714e in SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x1e
#25  0x7f39f1342618 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x58
#26  0x7f39f134c360 in Gui::NavigationStyle::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x40
#27  0x7f39f135147b in Gui::RevitNavigationStyle::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x3bb
#28  0x7f39f134e265 in Gui::NavigationStyle::processEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x65
#29  0x7f39f1377c3b in Gui::View3DInventorViewer::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x6b
#30  0x7f39f132d9e5 in SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x1a5
#31  0x7f39ee2b68bb in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Core.so.5+0x7b
#32  0x7f39ef17039e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Widgets.so.5+0x6e
#33  0x7f39ef1778f9 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Widgets.so.5+0xa39
#34  0x7f39f0f69559 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0xc9
#35  0x7f39ee2b6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Core.so.5+0x108
#36  0x7f39ef1763eb in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Widgets.so.5+0x1ab
#37  /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Widgets.so.5(+0x1c6e6f) [0x7f39ef1c6e6f]
#38  /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Widgets.so.5(+0x1ca0c9) [0x7f39ef1ca0c9]
#39  0x7f39ef1703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#40  0x7f39f0f69559 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0xc9
#41  0x7f39ee2b6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Core.so.5+0x108
#42  0x7f39ee9353ec in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Gui.so.5+0x84c
#43  0x7f39ee90b0bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Gui.so.5+0xac
#44  /tmp/.mount_FreeCAhAGfCM/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x64bea) [0x7f39e8e56bea]
#45  /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libglib-2.0.so.0(+0x5bad7) [0x7f39ecde6ad7]
#46  /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libglib-2.0.so.0(+0x5eac7) [0x7f39ecde9ac7]
#47  /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f39ecdea0ce]
#48  0x7f39ee30aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Core.so.5+0x66
#49  0x7f39ee2b570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Core.so.5+0x11b
#50  0x7f39ee2bd212 in QCoreApplication::exec() from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libQt5Core.so.5+0x82
#51  0x7f39f0ec8744 in Gui::Application::runApplication() from /tmp/.mount_FreeCAhAGfCM/usr/bin/../lib/libFreeCADGui.so+0x8a4
#52  /tmp/.mount_FreeCAhAGfCM/usr/bin/freecad(+0x78b7) [0x559bea1d08b7]
#53  /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f39ede4624a]
#54  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f39ede46305]
#55  /tmp/.mount_FreeCAhAGfCM/usr/bin/freecad(+0x7c2a) [0x559bea1d0c2a]
```

### Full version info

```shell
OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion


OS: Devuan GNU/Linux 5 (daedalus) (XFCE/xfce/xcb)
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Catalan/Spain (ca_ES)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Assembly

### Anything else?

[Rack_negative.FCStd.zip](https://github.com/user-attachments/files/17946490/Rack_negative.FCStd.zip)

https://github.com/user-attachments/assets/9c9268d9-e66b-4d1b-b3b6-1adc81c08352

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oficinerobotica** [comment]
I can confirm the crash with Gears joint also. Try dragging anything in the viewport in the attached file
Tested with FC 1.0 and 

`OS: KDE neon 6.2 (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39380 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 797c1180b012a8aee1d67de62880df0f835a731e
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Fusion
Installed mods: 
  * fasteners 0.5.33
  * PieMenu 1.10.1
  * OpenTheme 2024.9.1
  * sheetmetal.backup1729482375.2960367 0.5.1 (Disabled)
  * sheetmetal 0.5.10
  * Curves 0.6.51
  * Gridfinity 0.6.0
  * ArchTextures
  * Assembly4 0.50.15
  * CurvedShapes 1.0.13
`
[HydraulicPump.FCStd.zip](https://github.com/user-attachments/files/18003712/HydraulicPump.FCStd.zip)

**Comment by oficinerobotica** [comment]
Edit to my last comment. 
When created , the gear joint is created wit a 1:1 mm ratio in the spin boxes, if this values are changed and not left as they are, the program doesn't crash anymore and the joint works as expected
