### ISSUE TITLE
BIM: Errors show when switching to strict IFC mode on the start page

### ISSUE THREAD

**Issue by semhustej** [FreeCAD/FreeCAD#18191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

- Start FreeCAD
- Select BIM WB
- Stay on the Start page
- Click on 'Strict IFC mode' button
- Error shows up
```
15:09:09  Traceback (most recent call last):
15:09:09    File "C:\Program Files\FreeCAD 1.0\Mod\BIM\nativeifc\ifc_status.py", line 70, in on_toggle_lock
15:09:09      lock_document()
15:09:09    File "C:\Program Files\FreeCAD 1.0\Mod\BIM\nativeifc\ifc_status.py", line 197, in lock_document
15:09:09      if "IfcFilePath" not in doc.PropertiesList:
15:09:09                              ^^^^^^^^^^^^^^^^^^
15:09:09  AttributeError: 'NoneType' object has no attribute 'PropertiesList'

```

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

BIM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
```
16:24:33  Traceback (most recent call last):
16:24:33    File "/tmp/.mount_FreeCANMfFlo/usr/Mod/BIM/nativeifc/ifc_status.py", line 70, in on_toggle_lock
16:24:33      lock_document()
16:24:33    File "/tmp/.mount_FreeCANMfFlo/usr/Mod/BIM/nativeifc/ifc_status.py", line 197, in lock_document
16:24:33      if "IfcFilePath" not in doc.PropertiesList:
16:24:33                              ^^^^^^^^^^^^^^^^^^
16:24:33  AttributeError: 'NoneType' object has no attribute 'PropertiesList'
```

<details>
  <summary>FreeCAD 1.1.0dev.39315 (Git) Conda AppImage, Arch Linux (KDE/plasma/xcb)</summary>

```
OS: Arch Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39315 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 710542d121c2cabce05561591cfb00ef3b6e745c
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: lattice2 1.0.0; CurvedShapes 1.0.13; MeshRemodel 1.10.34; freecad.gears 1.3.0; fasteners 0.5.32; sheetmetal 0.5.10; Silk 0.1.5; Curves 0.6.51

```
</details>

**Comment by maxwxyz** [comment]
@yorikvanhavre FYI

**Comment by yorikvanhavre** [comment]
Good catch! Will fix ASAP
