### ISSUE TITLE
Part_Cut: copy_visual_attributes problem with link arrays

### ISSUE THREAD

**Issue by Roy-043** [FreeCAD/FreeCAD#18760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When using Part_Cut to cut from a link array there is an error:
```
17:40:09  pyException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\BKG_Tmp\FreeCAD_1.1\Mod\Part\BOPTools\BOPFeatures.py", line 50, in make_cut
    self.copy_visual_attributes(obj, obj.Base)
  File "D:\BKG_Tmp\FreeCAD_1.1\Mod\Part\BOPTools\BOPFeatures.py", line 111, in copy_visual_attributes
    src = src.LinkedObject
          ^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'LinkedObject'
```
May be related to #16541.

Steps to reproduce:

1. Open the file inside the attached ZIP: [Link_Array_Boolean.zip](https://github.com/FreeCAD/FreeCAD/files/10200400/Link_Array_Boolean.zip)
1. Select the Array object (Draft link array).
2. Add Cube004 to the selection.
3. Call Part_Cut.

### Full version info

```shell
OS: Windows 8 build 9600
Architecture: x86_64
Version: 1.1.0dev.39708 (Git) Conda
Build type: Release
Branch: main
Hash: 173ff4da1ef4f075d56c0dc617d1bf00d5f49d4b
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods:
```

### Subproject(s) affected?

Part

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarman3** [comment]
Pop up message did not show, but objects is disappeared.

https://github.com/user-attachments/assets/b7c725a2-7873-4089-a41e-d28e07b88a1e

<details>
  <summary>FreeCAD 1.1.0dev.39741 (Git) Conda AppImage, Arch Linux (KDE/plasma/xcb)</summary>

```
OS: Arch Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39741 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 0d128517dedd154bbecfbabe67094ad56c8d46f5
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: lattice2 1.0.0; CurvedShapes 1.0.13; MeshRemodel 1.10.35; freecad.gears 1.3.0; fasteners 0.5.33; sheetmetal 0.6.12; Silk 0.1.5; Curves 0.6.52
```

</details>
