### ISSUE TITLE
PartDesign: Duplicate body creates a mess in Graphviz because it's placed outside of the Part container

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5720]
Issue imported from https://tracker.freecad.org/view.php?id=3149

* **Reporter:** @ickby
* **Date submitted:** 8/7/2017
* **FreeCAD version:** 0.17
* **Category:** Bug
* **Status:** assigned
* **Tags:** 

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=3&t=15949

While experimenting on how Part-o-magic withstands object duplication, I found a bug in PartDesign.
1. New Part, New body
2. New sketch. Draw rectangle. Close.
3. Pad the sketch.
4. Select Body and menu Edit->Duplicate... When asked whether to duplicate dependencies, click Yes.
The body is duplicated.
But.
Problem No.1. Body is not added to active Part. OK, that can be fixed manually...
Problem No.2. and all looks fine, until one dives into dependency graph. There, a total mess can be seen.

Graph problem No.1: Duplicates of Sketch and Pad were added to original body, as well as to the copy of body.
Graph problem No.2: Pad001 references Pad (that is, gets fused to it).

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by @wwmayer 2017-10-01 21:01
With the implementation of scoped links the issue has been fixed. There is only a minor issue left because when duplicating the body this error comes up:
```
Exception (Sun Oct 01 22:51:58 2017): Object can only be in a single GeoFeatureGroup  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'Base.FreeCADError'>: Object can only be in a single GeoFeatureGroup
```

The question is if it can be avoided to raise the error message.

---

### Comment by @DeepSOIC 2017-11-20 10:29
IMO the bug is still very big.

a) when I duplicate a body, a message pops up, if FreeCAD should duplicate dependencies. 
If I answer No, the contents of the body is not duplicated; errors in report view, and the new Body shares an Origin object with the old body. This is a mess.

b) the original  Body (which I deactivated before copying) got activated back. I expect that the active object should not change.

c) the action of the "copy dependencies" question applies the old logic of isolated PartDesign of 0.16, which partly explains point a). What I expect: "No" = body should be copied with all its contents duplicated, but none of the objects outside of the body should be duplicated. "Yes" - same, but with all dependencies not in body too (e.g. master sketches). This might get really tricky if for example there is a shapebinder of a partdesign feature from another body.

---

### Comment by Bicycle Repair Man 2019-05-09 18:30
I can verify, that this bug is still present in some form in the 0.19 daily build from today (May 9th 2019).

1. Please open "Duplicate_Part.FCStd" - This design has one master spreadheet to parameterize all parts.
2. Select Part "Rahmen"
3. Edit -> Duplicate Selection
4a. Answer "No" to "copy dependencies"
- In this case only the Part itself without any content is duplicated. To me, this is an unneeded state and I fully agree with DeepSOIC's suggestion c) to solve this.
4b. Answer "Yes" to "copy dependencies"
- The Part and its contained objects are duplicated, BUT
the duplicate references the original spreadsheet: Reference in Rahmen001 -> Rahmen_vorne001 -> Position.x now points to "Spreadsheet.w_rahmen" which is the original Spreadsheet. This should be "param001" (or "Spreadsheet001" if neccessary).
Similar to Rahmen001 -> Rahmen_vorne001 -> Length that points to "param.h_nut" which is also the original spreadsheet

In any case, my suggestions are
- The original part should stay unaltered
- Independent of saying "Yes" or "No" to copy dependencies, I expect that all objects within the selection (also recursively) appear in the resulting object tree. Anything else is not a duplicate.
- If saying "No" only objects within the selection tree should be duplicated (but still recursively). That would mean, that the duplicate references the master spreadsheet exactly the same way like the original.
- If saying "Yes" also dependecies outside the selection tree (e.g. master spreadsheet) should be copied and correctly referenced by the duplicate objects (again, also recursively through the tree)

Many thanks for bringing this great tool to us!
Best Regards,
Stephan

OS: Linux Mint 19.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Python version: 3.6.7
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

---

### Comment by SimonLitt 2020-01-06 06:19
Hi!
When I mirror a pad,the body of the part becomes empty. 
When I delete a copy, I cannot return the pad back to the body.
Error message is: Object can only be in a single GeoFeatureGroup

Sometimes when creating a sketch, the message drawing during migration appears, and when choosing automatic, an empty body is created, and everything settles as before.

When I make a mirror copy of the body - everything is fine. But so far I have understood it, I made a lot of mistakes in the drawings. Now, in order to change something, I need to make copies of the sketch and create the parts again.

[youtube screen record](https://youtu.be/aRHqHNmfftc )
Full console output

```
$ freecad
FreeCAD 0.18, Libs: 0.18RUnknown
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

'ascii' codec can't encode characters in position 13-17: ordinal not in range(128)
Part::Mirroring / Part__Mirroring: Links go out of the allowed scope
Part::Mirroring / Part__Mirroring: Links go out of the allowed scope
Part::Mirroring / Part__Mirroring: Links go out of the allowed scope
Exception (Mon Jan  6 08:34:06 2020): Object can only be in a single GeoFeatureGroup  
Exception (Mon Jan  6 08:34:07 2020): Object can only be in a single GeoFeatureGroup  
Exception (Mon Jan  6 08:34:48 2020): Object can only be in a single GeoFeatureGroup  
Exception ignored in: <bound method WebView.__del__ of <__main__.WebView object at 0x7fa1c5e362b0>>
Traceback (most recent call last):
  File "<string>", line 18, in __del__
AttributeError: 'WebView' object has no attribute 'webPage'
Sketcher::SketchObject / Sketch: Links go out of the allowed scope
Exception (Mon Jan  6 08:34:57 2020): Object can only be in a single GeoFeatureGroup  
Exception (Mon Jan  6 08:35:00 2020): Object can only be in a single GeoFeatureGroup  
Exception (Mon Jan  6 08:35:04 2020): Object can only be in a single GeoFeatureGroup  
Exception (Mon Jan  6 08:35:08 2020): Object can only be in a single GeoFeatureGroup  
Sketcher::SketchObject / Sketch001: Links go out of the allowed scope
$
```

---

### Comment by @abdullahtahiriyo  2020-07-08 15:07
There is a new "copy dialog" in FC 0.19. 

If all dependencies are selected, the body is copied. It is not copied within the part (one has to move it in manually), but the dependency graph shows an independent object.

The error message Werner indicates is still there.

**Comment by luzpaz** [comment]
What's the status of this ticket?

**Comment by Roy-043** [comment]
The error message is still there.
```
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.21.0.33492 (Git)
Build type: Release
Branch: master
Hash: 6e235a4809e14674aa2cd23e68630b68998a53d4
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

**Comment by maxwxyz** [comment]
@PaddleStroke could be solved with your copy/paste efforts?

**Comment by luzpaz** [comment]
Needs to be retested

**Comment by FEA-eng** [comment]
I can confirm that the duplicated Body is placed outside of the Part container. I also wanted to check the dependency graph but I keep getting this:

<img width="298" height="142" alt="Image" src="https://github.com/user-attachments/assets/208239a2-a01d-409e-9d21-bf087e6135cb" />

**Comment by luzpaz** [comment]
@ickby is this still on your radar ?

**Comment by FEA-eng** [comment]
[This](https://github.com/FreeCAD/FreeCAD/issues/5720#issuecomment-3207997613) is still relevant

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20260609 (Git shallow)
Build date: 2026/06/09 14:33:40
Build type: Release
Branch: grafted,grafted
Hash: 9cb82b95e9f52f3ac2edc9d42525b39a1d77532a
Python 3.11.15, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, Clipper2 , IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL) [ OS: Polish/Poland (pl_PL) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```
