### ISSUE TITLE
FC crashes when try to make wall from segment (reason: faulty DXF file)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5979]
Issue imported from https://tracker.freecad.org/view.php?id=4099

* **Reporter:** ph.andronov
* **Date submitted:** 8/27/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** feedback
* **Tags:** #pending-forum

# Original report text

Crash during wall creation:
```
FreeCAD 0.18, Libs: 0.18R16131 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##


(freecad:24592): Gtk-WARNING **: 10:07:25.573: Theme parsing error: gtk.css:2:116: Failed to import: Error opening file /home/andrphi/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet.css: No such file or directory

(freecad:24592): Gtk-WARNING **: 10:07:25.573: Theme parsing error: gtk.css:3:122: Failed to import: Error opening file /home/andrphi/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet-tiled.css: No such file or directory
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4960909.62788767, 1000671.647867698, 0.0)   Vector (4960909.62788767, 1000681.647867698, 0.0)
<Line object>   Vector (4960709.62788767, 1000681.647867698, 0.0)   Vector (4960709.62788767, 1000441.647867698, 0.0)
<Line object>   Vector (4960709.62788767, 1000441.647867698, 0.0)   Vector (4961049.62788767, 1000441.647867698, 0.0)
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4960709.62788767, 1000671.647867698, 0.0)   Vector (4960709.62788767, 1000681.647867698, 0.0)
<Line object>   Vector (4960909.62788767, 1000681.647867698, 0.0)   Vector (4960909.62788767, 1000641.647867698, 0.0)
<Line object>   Vector (4960909.62788767, 1000641.647867698, 0.0)   Vector (4961049.62788767, 1000641.647867698, 0.0)
DraftGeomUtils: unable to bind wires
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4961029.627887671, 1000671.647867698, 0.0)   Vector (4961029.627887671, 1000681.647867698, 0.0)
<Line object>   Vector (4960829.627887671, 1000681.647867698, 0.0)   Vector (4960829.627887671, 1000541.647867698, 0.0)
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4960829.627887671, 1000671.647867698, 0.0)   Vector (4960829.627887671, 1000681.647867698, 0.0)
<Line object>   Vector (4961029.627887671, 1000681.647867698, 0.0)   Vector (4961029.627887671, 1000541.647867698, 0.0)
DraftGeomUtils: unable to bind wires
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4960829.627887671, 1000801.647867698, 0.0)   Vector (4960829.627887671, 1000791.647867698, 0.0)
<Line object>   Vector (4961029.627887671, 1000791.647867698, 0.0)   Vector (4961029.627887671, 1000931.647867698, 0.0)
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4961029.627887671, 1000801.647867698, 0.0)   Vector (4961029.627887671, 1000791.647867698, 0.0)
<Line object>   Vector (4960829.627887671, 1000791.647867698, 0.0)   Vector (4960829.627887671, 1000931.647867698, 0.0)
DraftGeomUtils: unable to bind wires
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4968449.627887669, 1002001.647867698, 0.0)   Vector (4968449.627887669, 1001991.647867698, 0.0)
<Line object>   Vector (4968649.627887669, 1001991.647867698, 0.0)   Vector (4968649.627887669, 1002131.647867698, 0.0)
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4968649.627887669, 1002001.647867698, 0.0)   Vector (4968649.627887669, 1001991.647867698, 0.0)
<Line object>   Vector (4968449.627887669, 1001991.647867698, 0.0)   Vector (4968449.627887669, 1002131.647867698, 0.0)
DraftGeomUtils: unable to bind wires
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4969359.62788767, 1006881.647867699, 0.0)   Vector (4969214.342010461, 1006881.647867699, 0.0)
<Line object>   Vector (4969214.342010461, 1006881.647867699, 0.0)   Vector (4968097.047477968, 1005548.0008129562, 0.0)
<Line object>   Vector (4968097.047477968, 1005548.0008129562, 0.0)   Vector (4968097.047477968, 1005411.647867698, 0.0)
<Line object>   Vector (4968097.047477968, 1005411.647867698, 0.0)   Vector (4967539.627887675, 1005411.647867698, 0.0)
<Line object>   Vector (4967539.627887675, 1005411.647867698, 0.0)   Vector (4967539.627887669, 1004661.647867698, 0.0)
<Line object>   Vector (4967539.627887669, 1004661.647867698, 0.0)   Vector (4968329.62788767, 1004661.647867698, 0.0)
<Line object>   Vector (4968329.62788767, 1004661.647867698, 0.0)   Vector (4968329.62788767, 994461.6478676982, 0.0)
<Line object>   Vector (4968329.62788767, 994461.6478676982, 0.0)   Vector (4967719.62788767, 994461.6478676982, 0.0)
<Line object>   Vector (4967719.62788767, 994461.6478676982, 0.0)   Vector (4967719.62788767, 993711.6478676982, 0.0)
<Line object>   Vector (4967719.62788767, 993711.6478676982, 0.0)   Vector (4968069.62788767, 993711.6478676982, 0.0)
<Line object>   Vector (4968069.62788767, 993711.6478676982, 0.0)   Vector (4968069.627887673, 992261.6478676983, 0.0)
<Line object>   Vector (4968069.627887673, 992261.6478676983, 0.0)   Vector (4969359.62788767, 992261.6478676982, 0.0)
<Line object>   Vector (4969359.62788767, 992461.6478676982, 0.0)   Vector (4968719.62788767, 992461.6478676982, 0.0)
DraftGeomUtils.connect: unable to connect edges
<Line object>   Vector (4969359.62788767, 1006681.647867699, 0.0)   Vector (4969307.698343353, 1006681.647867699, 0.0)
<Line object>   Vector (4969307.698343353, 1006681.647867699, 0.0)   Vector (4968297.047477968, 1005475.2949224397, 0.0)
<Line object>   Vector (4968297.047477968, 1005475.2949224397, 0.0)   Vector (4968297.047477968, 1005211.647867698, 0.0)
<Line object>   Vector (4968297.047477968, 1005211.647867698, 0.0)   Vector (4967739.627887673, 1005211.647867698, 0.0)
<Line object>   Vector (4967739.627887673, 1005211.647867698, 0.0)   Vector (4967739.627887671, 1004861.647867698, 0.0)
<Line object>   Vector (4967739.627887671, 1004861.647867698, 0.0)   Vector (4968529.62788767, 1004861.647867698, 0.0)
<Line object>   Vector (4968529.62788767, 1004861.647867698, 0.0)   Vector (4968529.62788767, 994261.6478676982, 0.0)
<Line object>   Vector (4968529.62788767, 994261.6478676982, 0.0)   Vector (4967919.62788767, 994261.6478676982, 0.0)
<Line object>   Vector (4967919.62788767, 994261.6478676982, 0.0)   Vector (4967919.62788767, 993911.6478676982, 0.0)
<Line object>   Vector (4967919.62788767, 993911.6478676982, 0.0)   Vector (4968269.62788767, 993911.6478676982, 0.0)
<Line object>   Vector (4968269.62788767, 993911.6478676982, 0.0)   Vector (4968269.627887673, 992461.6478676983, 0.0)
<Line object>   Vector (4968269.627887673, 992461.6478676983, 0.0)   Vector (4969359.62788767, 992461.6478676982, 0.0)
<Line object>   Vector (4969359.62788767, 992261.6478676982, 0.0)   Vector (4968719.62788767, 992261.6478676982, 0.0)
DraftGeomUtils: unable to bind wires
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3a7e0) [0x7f0a75e8e7e0]
#1  0x7f0a04b7f798 in Geom_TrimmedCurve::Geom_TrimmedCurve(opencascade::handle<Geom_Curve> const&, double, double, bool, bool) from /usr/lib/libTKG3d.so.7+0x1b8
#2  0x7f09fb92c7db in GC_MakeSegment::GC_MakeSegment(gp_Pnt const&, gp_Pnt const&) from /usr/lib/libTKGeomBase.so.7+0xeb
#3  0x7f0a01d8fcc4 in Part::LineSegmentPy::PyInit(_object*, _object*) from /usr/lib/freecad/lib/Part.so+0x984
#4  /usr/lib/libpython3.7m.so.1.0(_PyObject_FastCallKeywords+0x11a) [0x7f0a76ef2f5a]
#5  /usr/lib/libpython3.7m.so.1.0(+0x138362) [0x7f0a76ef4362]
#6  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x4fda) [0x7f0a76f2e40a]
#7  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x2f8) [0x7f0a76ee2768]
#8  /usr/lib/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x2a3) [0x7f0a76ee37d3]
#9  /usr/lib/libpython3.7m.so.1.0(+0x1381d0) [0x7f0a76ef41d0]
#10  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1748) [0x7f0a76f2ab78]
#11  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x2f8) [0x7f0a76ee2768]
#12  /usr/lib/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x2a3) [0x7f0a76ee37d3]
#13  /usr/lib/libpython3.7m.so.1.0(+0x1381d0) [0x7f0a76ef41d0]
#14  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x4fda) [0x7f0a76f2e40a]
#15  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x2f8) [0x7f0a76ee2768]
#16  /usr/lib/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x2a3) [0x7f0a76ee37d3]
#17  /usr/lib/libpython3.7m.so.1.0(+0x1381d0) [0x7f0a76ef41d0]
#18  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0xb40) [0x7f0a76f29f70]
#19  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x2f8) [0x7f0a76ee2768]
#20  /usr/lib/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x2ef) [0x7f0a76ee3e7f]
#21  /usr/lib/libpython3.7m.so.1.0(_PyObject_Call_Prepend+0x68) [0x7f0a76eb7ce8]
#22  /usr/lib/libpython3.7m.so.1.0(PyObject_Call+0x7e) [0x7f0a76ee43be]
#23  0x7f0a77548f80 in App::FeaturePythonImp::execute() from /usr/lib/freecad/lib/libFreeCADApp.so+0x5d0
#24  0x7f0a01d49fa7 in App::FeaturePythonT<Part::Feature>::execute() from /usr/lib/freecad/lib/Part.so+0x17
#25  0x7f0a774f9589 in App::DocumentObject::recompute() from /usr/lib/freecad/lib/libFreeCADApp.so+0xb9
#26  0x7f0a01d481ba in Part::Feature::recompute() from /usr/lib/freecad/lib/Part.so+0xa
#27  0x7f0a774ac2b5 in App::Document::_recomputeFeature(App::DocumentObject*) from /usr/lib/freecad/lib/libFreeCADApp.so+0x55
#28  0x7f0a774b589b in App::Document::recompute() from /usr/lib/freecad/lib/libFreeCADApp.so+0x19b
#29  0x7f0a77528ef5 in App::DocumentPy::recompute(_object*) from /usr/lib/freecad/lib/libFreeCADApp.so+0x45
#30  0x7f0a77528feb in App::DocumentPy::staticCallback_recompute(_object*, _object*) from /usr/lib/freecad/lib/libFreeCADApp.so+0x3b
#31  /usr/lib/libpython3.7m.so.1.0(_PyMethodDef_RawFastCallKeywords+0x25f) [0x7f0a76ec25df]
#32  /usr/lib/libpython3.7m.so.1.0(_PyCFunction_FastCallKeywords+0x24) [0x7f0a76ec2714]
#33  /usr/lib/libpython3.7m.so.1.0(+0x1382ec) [0x7f0a76ef42ec]
#34  /usr/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x4fda) [0x7f0a76f2e40a]
#35  /usr/lib/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x11b) [0x7f0a76ee3cab]
#36  /usr/lib/libpython3.7m.so.1.0(_PyObject_Call_Prepend+0x68) [0x7f0a76eb7ce8]
#37  /usr/lib/libpython3.7m.so.1.0(PyObject_Call+0x7e) [0x7f0a76ee43be]
#38  /usr/lib/freecad/lib/libFreeCADBase.so(PP_Run_Method+0xec) [0x7f0a772c0e0c]
#39  0x7f0a77252bfc in Base::InterpreterSingleton::runMethodVoid(_object*, char const*) from /usr/lib/freecad/lib/libFreeCADBase.so+0x2c
#40  0x7f0a77b0925a in Gui::PythonCommand::activated(int) from /usr/lib/freecad/lib/libFreeCADGui.so+0xaa
#41  0x7f0a77b0cb2c in Gui::Command::invoke(int) from /usr/lib/freecad/lib/libFreeCADGui.so+0x5c
#42  0x7f0a764d6a11 in QMetaObject::activate(QObject*, int, int, void**) from /usr/lib/libQt5Core.so.5+0x7c1
#43  0x7f0a76877e93 in QAction::triggered(bool) from /usr/lib/libQt5Widgets.so.5+0x43
#44  0x7f0a7687a624 in QAction::activate(QAction::ActionEvent) from /usr/lib/libQt5Widgets.so.5+0x104
#45  /usr/lib/libQt5Widgets.so.5(+0x253c2d) [0x7f0a76978c2d]
#46  0x7f0a76978e56 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /usr/lib/libQt5Widgets.so.5+0xe6
#47  0x7f0a76a6dceb in QToolButton::mouseReleaseEvent(QMouseEvent*) from /usr/lib/libQt5Widgets.so.5+0xb
#48  0x7f0a768c1cb6 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x256
#49  0x7f0a76a6dd95 in QToolButton::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x35
#50  0x7f0a7687e4d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x85
#51  0x7f0a76887c6c in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x57c
#52  0x7f0a77adac39 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#53  0x7f0a764aa9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x182
#54  0x7f0a76886d4b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /usr/lib/libQt5Widgets.so.5+0x1bb
#55  /usr/lib/libQt5Widgets.so.5(+0x1b9211) [0x7f0a768de211]
#56  /usr/lib/libQt5Widgets.so.5(+0x1bc154) [0x7f0a768e1154]
#57  0x7f0a7687e4d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x85
#58  0x7f0a76887a21 in QApplication::notify(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x331
#59  0x7f0a77adac39 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#60  0x7f0a764aa9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x182
#61  0x7f0a74693789 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /usr/lib/libQt5Gui.so.5+0x709
#62  0x7f0a7469505b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /usr/lib/libQt5Gui.so.5+0x27b
#63  0x7f0a7466d37c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Gui.so.5+0xbc
#64  /usr/lib/libQt5XcbQpa.so.5(+0x6bfec) [0x7f0a70198fec]
#65  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x294) [0x7f0a73a11cf4]
#66  /usr/lib/libglib-2.0.so.0(+0x6ab11) [0x7f0a73a13b11]
#67  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f0a73a13b51]
#68  0x7f0a765029a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x63
#69  0x7f0a764a95ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x12c
#70  0x7f0a764b1326 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x96
#71  0x7f0a77a674c3 in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x1753
#72  freecad(main+0x6e7) [0x562892a60407]
#73  /usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f0a75e7aee3]
#74  freecad(_start+0x2e) [0x562892a6071e]
```

# Additional information

OS: Arch Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16131 (Git)
Build type: Release
Branch: makepkg
Hash: 3129ae4296e40ed20e7b3d460b86e6969acbe1c3
Python version: 3.7.4
Qt version: 5.13.0
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

# Steps to reproduce

- Open attached file
- Try to make a wall from any segment on the basement floor plan

Note: It is still possible to create wall from SOME segments, but I've failed to figure out any pattern

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **OS: arch linux **
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by openBrain 2019-08-27 18:47
ph.andronov : thanks for reporting. However, according guidelines (big yellow banner), could you please first open a forum topic so the community can help validate and identify ? Thanks

---

### Comment by ph.andronov 2019-09-02 10:50
After community review it seems that crash caused by bad DXF (added to attach)

However I guess issue still valid as no matter how bad result DXF import produced, FC shouldn't be crashed during operations with a model

---

### Comment by Kunda1 2019-12-17 04:09
ph.andronov [s]please link to the forum thread[/s]  
https://forum.freecadweb.org/viewtopic.php?f=3&t=38897

---

### Comment by Kunda1 2019-12-17 04:15
Moved to 'File Formats' category. 
Workaround in the meantime: https://forum.freecadweb.org/viewtopic.php?f=3&t=38897&p=329930#p330256

---

### Comment by abdullah 2020-06-13 15:09
I cannot reproduce the crash anymore with:
OS: Ubuntu 18.04.4 LTS (MATE/mate)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Branch: unknown
Hash: 8ed90c858645e7562d9534265b6025d39ab4ffd6
Python version: 3.6.9
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0

I have posted to the forum.

---

### Comment by abdullah 2020-06-13 15:30
Could you please check if this is reproducible (the crash), with a current version of FC?

---

### Comment by Kunda1 2020-12-01 11:37
ph.andronov please try to reproduce on latest v0.19 and report back

**Comment by luzpaz** [comment]
Closing ticket
