### ISSUE TITLE
When running FC 0.19 on Windows 7, it returns errors in the Report window

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6110]
Issue imported from https://tracker.freecad.org/view.php?id=4450

* **Reporter:** mozarelo
* **Date submitted:** 10/3/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** #pending-forum

# Original report text

Each time it starts, it outputs:

[color=blue]23:00:50  OpenGL version is: 4.5 (4.5.0 NVIDIA 347.52)
23:00:50  Run Gui init script
23:00:51  Init: Running FreeCADGuiInit.py start script...
23:00:51  Init:   Searching modules...
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\AddonManager... done
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Arch... done
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Complete... done
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Draft... done
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Drawing... done
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Fem... done
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Idf(InitGui.py not found)... ignore
23:00:51  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Image... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Import... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Inspection... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Material... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Measure(InitGui.py not found)... ignore
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Mesh... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\MeshPart... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\OpenSCAD... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Part... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\PartDesign... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Path... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Points... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Raytracing... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\ReverseEngineering... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Robot... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Show(InitGui.py not found)... ignore
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Sketcher... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Spreadsheet... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Start... done
23:00:52  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Surface... done
23:00:53  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\TechDraw... done
23:00:53  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Test... done
23:00:53  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Tux... done
23:00:53  Init:      Initializing C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Web... done
23:00:53  Module: Part
23:00:53  Loading Part module... done
23:00:53  Init:      Initializing C:\Users\Ultranemo\AppData\Roaming\FreeCAD\Mod\A2plus... failed
23:00:53  ----------------------------------------------------------------------------------------------------
23:00:53  Traceback (most recent call last):
  File "<string>", line 127, in InitApplications
  File "<string>", line 233, in <module>
  File "<string>", line 47, in __init__
  File "C:\Users\Ultranemo\AppData\Roaming\FreeCAD\Mod\A2plus\a2plib.py", line 35, in <module>
    import numpy
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _internal
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\_internal.py", line 14, in <module>
    import ctypes
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 468, in <module>
    GetLastError = windll.kernel32.GetLastError
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] Параметр задан неверно
23:00:53  ----------------------------------------------------------------------------------------------------[/color]
[color=red]23:00:53  During initialization the error "[WinError 87] Параметр задан неверно" occurred in C:\Users\Ultranemo\AppData\Roaming\FreeCAD\Mod\A2plus\InitGui.py
23:00:53  Please look into the log file for further information[/color]
23:00:53  Init: Initializing freecad.asm3
[color=red]23:00:54  During initialization the error "[WinError 87] Параметр задан неверно" occurred in freecad.asm3
23:00:54  --------------------------------------------------------------------------------
23:00:54  Traceback (most recent call last):
  File "<string>", line 152, in InitApplications
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\freecad\asm3\init_gui.py", line 3, in <module>
    from .utils import mainlogger as logger
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\freecad\asm3\utils.py", line 11, in <module>
    import numpy as np
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _internal
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\_internal.py", line 14, in <module>
    import ctypes
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 468, in <module>
    GetLastError = windll.kernel32.GetLastError
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] Параметр задан неверно
23:00:54  --------------------------------------------------------------------------------[/color]
[color=blue]23:00:54  Init:      Initializing freecad.asm3... failed
23:00:54  --------------------------------------------------------------------------------
23:00:54  Traceback (most recent call last):
  File "<string>", line 152, in InitApplications
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\freecad\asm3\init_gui.py", line 3, in <module>
    from .utils import mainlogger as logger
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\freecad\asm3\utils.py", line 11, in <module>
    import numpy as np
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _internal
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\_internal.py", line 14, in <module>
    import ctypes
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 468, in <module>
    GetLastError = windll.kernel32.GetLastError
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] Параметр задан неверно
23:00:54  --------------------------------------------------------------------------------
23:00:54  Init: Loading FreeCAD GUI
23:00:54  Init: Running FreeCADGuiInit.py start script... done
23:00:56  Init: Activating default workbench StartWorkbench
23:00:56  Loading GUI of Web module... done
23:00:56  Loading GUI of Start module... done
23:00:56  Loading Start module... done
23:00:56  Installed Qt WebEngine locales directory not found at location C:/FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64/translations\qtwebengine_locales. Trying application directory...
23:00:56  Qt WebEngine locales directory not found at location C:/FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64/bin\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
23:00:56  Init: Showing main window
23:00:56  Main window restored
23:00:56  Show main window
23:00:56  Toolbars restored
23:00:56  3Dconnexion device not attached.
23:00:56  Init: Entering event loop
23:00:56  Init: Processing command line files[/color]

The Part Design and Path workbenches do not work and also give errors. And Part Design at each choice, and Path only the first time, then it writes that the workbench Path activated, but also does not work.

This gives out Part Design:

[color=blue]23:04:22  Hide main window
23:04:41  Show main window
23:04:51  Hide main window
23:05:11  Show main window
23:05:15  Hide main window
23:05:51  Show main window
23:06:01  Hide main window
23:06:31  Show main window
23:10:44  Loading Sketcher module... done
23:10:44  Loading PartDesign module... done[/color]
[color=red]23:10:44  [WinError 87] Параметр задан неверно
23:10:44  Traceback (most recent call last):
  File "<string>", line 42, in Initialize
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\PartDesign\WizardShaft\WizardShaft.py", line 27, in <module>
    from .Shaft import Shaft
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\PartDesign\WizardShaft\Shaft.py", line 25, in <module>
    from .SegmentFunction import SegmentFunction,  IntervalFunction,  StressFunction,  TranslationFunction
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\PartDesign\WizardShaft\SegmentFunction.py", line 25, in <module>
    import numpy as np
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _internal
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\_internal.py", line 14, in <module>
    import ctypes
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 468, in <module>
    GetLastError = windll.kernel32.GetLastError
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)[/color]

This outputs Path for the first time:

[color=blue]23:14:17  Loading Path module... done
23:14:17  Loading PathStock... done
23:14:17  Loading GUI of Part module... done
23:14:17  Loading GUI of Path module... done
23:14:17  Loading PathToolControllerGui... done
23:14:17  Loading PathToolController... done
23:14:17  Loading PathJobCmd... done
23:14:17  Loading PathToolBitCmd... done
23:14:17  Loading PathToolBitLibraryCmd... done[/color]
[color=red]23:14:17  [WinError 87] Параметр задан неверно
23:14:17  Traceback (most recent call last):
  File "<string>", line 86, in Initialize
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Path\PathCommands.py", line 29, in <module>
    from PathScripts.PathUtils import loopdetect
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\Mod\Path\PathScripts\PathUtils.py", line 30, in <module>
    import numpy
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _internal
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\site-packages\numpy\core\_internal.py", line 14, in <module>
    import ctypes
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 468, in <module>
    GetLastError = windll.kernel32.GetLastError
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 443, in __getattr__
    dll = self._dlltype(name)
  File "C:\FreeCAD_0.19.22522-Win-Conda_vc14.x-x86_64\bin\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)[/color]

And then when you re-enable it, Path returns:

23:15:12  Path workbench activated

In addition, there is a debug.log file in the Bin folder. Each time i run FC, two identical lines appear there:

[1003/221915.977:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 
[1003/221916.618:WARNING:resource_bundle_qt.cpp(116)] locale_file_path.empty() for locale 

# FreeCAD Info

```
OS: Windows 7 SP 1 (6.1)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22522 (Git)
Build type: Release
Branch: master
Hash: d8e476ef428017900dfe0f9359ba448503c216f9
Python version: 3.8.5
Qt version: 5.12.6
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Russian/Russia (ru_RU)
```

# Other bug information

* **Priority:** normal
* **Severity:** major
* **Category:** Bug
* **Updated:** 2/7/2022

# Discussion from Mantis ticket

### Comment by openBrain 2020-10-09 21:15
mozarelo : please address your issue according [our reporting guidelines](https://forum.freecadweb.org/viewtopic.php?f=3&t=5236) by opening a new topic on [our forum](https://forum.freecadweb.org/index.php). Thx
Also consider using 'code' tags to insert tracebacks.

---

### Comment by Kunda1 2020-10-15 14:12
mozarelo can you still reproduce this on latest 0.19 ?

---

### Comment by Kunda1 2020-10-15 14:13
Discussion thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=51188

---

### Comment by Kunda1 2020-10-15 16:01
mozarelo please follow this advice: https://forum.freecadweb.org/viewtopic.php?f=8&t=51188#p439657

---

### Comment by Kunda1 2020-10-15 18:43
mozarelo please make sure all your addons are up to date and try again. This includes A2+

---

### Comment by Kunda1 2021-03-28 16:24
mozarelo ping

---

### Comment by Kunda1 2021-03-28 16:27
Looks like these issues occur for mozarelo on win-conda and not on Win-LP
https://forum.freecadweb.org/viewtopic.php?f=8&t=51188#p439902

**Comment by luzpaz** [comment]
bumped [forum thread](https://forum.freecadweb.org/viewtopic.php?p=585314#p585314)

**Comment by adrianinsaval** [comment]
This looks like it's a python 3.8 incompatibility issue either with an older version of win7 (python 3.8 required that a specific windows update be applied to work) or with the processor they are using.

**Comment by luzpaz** [comment]
GeneFC hasn't encountered the issue or incompatibility and thinks it may be a locale issue (russian). Anyway, closing ticket unless there are any changes (feel free to re-open)
