### ISSUE TITLE
Doubleclick when drawing a polygon seems to results in an unresolvable double point.

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6142]
Issue imported from https://tracker.freecad.org/view.php?id=4520

* **Reporter:** DrC
* **Date submitted:** 12/24/2020
* **FreeCAD version:** 
* **Category:** Bug
* **Status:** feedback
* **Tags:** #post-to-forum, 0.19, Poly-line, UI

# Original report text

When drawing a polygon to complete a closed shape that starts with an arc:

1. A gratuitous tangent is added in some circumstances.  This is minor and easily deleted.  I plan to open a new bug on this later.

2. A double click (a previous way of terminating a polygon) resulted in an intractable double point, possibly because it inadvertently coincided with a construction line.  I have  prioritised reporting it over finding out how to deal with it as I suspect I will have to redo a chunk of drawing and forget how it happened!

```
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:26  Updating geometry: Error build geometry(8): Both points are equal
13:12:26  Invalid solution from DogLeg solver.
13:12:41  Delete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelements
```

# Additional information

```
12:23:06  Delete: Selection not restricted to one sketch and its subelementsTraceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'ValueError'>: Datum 17.50 mm for the constraint with index 11 is invalid
12:35:35  App.getDocument('Unnamed').getObject('Sketch002').setDatum(11,App.Units.Quantity('17.500000 mm'))
12:36:08  Traceback (most recent call last):
  File "<string>", line 1, in <module>
<class 'ValueError'>: Datum 11.91 mm for the constraint with index 11 is invalid
12:36:08  App.getDocument('Unnamed').getObject('Sketch002').setDatum(11,App.Units.Quantity('11.910000 mm'))
12:41:39  Delete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsUpdating geometry: Error build geometry(9): Both points are equal
13:04:47  Invalid solution from DogLeg solver.
13:04:47  Updating geometry: Error build geometry(9): Both points are equal
13:04:47  Invalid solution from LevenbergMarquardt solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:01  Updating geometry: Error build geometry(9): Both points are equal
13:05:01  Invalid solution from DogLeg solver.
13:05:03  Updating geometry: Error build geometry(9): Both points are equal
13:05:03  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:11  Updating geometry: Error build geometry(9): Both points are equal
13:05:11  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:12  Updating geometry: Error build geometry(9): Both points are equal
13:05:12  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:05:13  Updating geometry: Error build geometry(9): Both points are equal
13:05:13  Invalid solution from DogLeg solver.
13:11:20  Updating geometry: Error build geometry(9): Both points are equal
13:11:20  Invalid solution from DogLeg solver.
13:11:20  Updating geometry: Error build geometry(9): Both points are equal
13:11:20  Invalid solution from DogLeg solver.
13:11:20  Updating geometry: Error build geometry(9): Both points are equal
13:11:20  Invalid solution from DogLeg solver.
13:11:21  Updating geometry: Error build geometry(9): Both points are equal
13:11:21  Invalid solution from DogLeg solver.
13:11:21  Updating geometry: Error build geometry(9): Both points are equal
13:11:21  Invalid solution from DogLeg solver.
13:11:21  Updating geometry: Error build geometry(9): Both points are equal
13:11:21  Invalid solution from DogLeg solver.
13:11:21  Updating geometry: Error build geometry(9): Both points are equal
13:11:21  Invalid solution from DogLeg solver.
13:11:22  Updating geometry: Error build geometry(9): Both points are equal
13:11:22  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:03  Updating geometry: Error build geometry(8): Both points are equal
13:12:03  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:04  Updating geometry: Error build geometry(8): Both points are equal
13:12:04  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:05  Updating geometry: Error build geometry(8): Both points are equal
13:12:05  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:06  Updating geometry: Error build geometry(8): Both points are equal
13:12:06  Invalid solution from DogLeg solver.
13:12:07  Updating geometry: Error build geometry(8): Both points are equal
13:12:07  Invalid solution from DogLeg solver.
13:12:22  Updating geometry: Error build geometry(8): Both points are equal
13:12:22  Invalid solution from DogLeg solver.
13:12:22  Updating geometry: Error build geometry(8): Both points are equal
13:12:22  Invalid solution from DogLeg solver.
13:12:22  Updating geometry: Error build geometry(8): Both points are equal
13:12:22  Invalid solution from DogLeg solver.
13:12:22  Updating geometry: Error build geometry(8): Both points are equal
13:12:22  Invalid solution from DogLeg solver.
13:12:22  Updating geometry: Error build geometry(8): Both points are equal
13:12:22  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:23  Updating geometry: Error build geometry(8): Both points are equal
13:12:23  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:24  Updating geometry: Error build geometry(8): Both points are equal
13:12:24  Invalid solution from DogLeg solver.
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:25  Updating geometry: Error build geometry(8): Both points are equal
13:12:25  Invalid solution from DogLeg solver.
13:12:26  Updating geometry: Error build geometry(8): Both points are equal
13:12:26  Invalid solution from DogLeg solver.
13:12:41  Delete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelementsDelete: Selection not restricted to one sketch and its subelements
```

# Steps to reproduce

The attached part is to become a split cable bush.  So far it is a pair of hinged semicircular cylinders with a reduced diameter section added at one end.  The next step is to add a rim at the original diameter with cut-outs for lugs on the parent body to enter the groove left by the reduced diameter.  It will be installed by push and twist.

For the time being it is a solid plug.  The cableway will come later.

The rim design starts with two arcs at the full size, but they do not come down to the base line.  They stop 2mm above at the construction line.  The task now to is to add four straight sides to each arc making two closed shapes.  The bottom edge would be on the base line, the connections to the arc are to be at 45 degrees to facilitate 3D printing.

Select the polygon tool, start at one end of one of the arcs and try to draw it.  The tangent appears.  Draw a polygon in the other direction to edit later and stop by double clicking accidentally on the construction line.

# FreeCAD Info

```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23141 (Git)
Build type: Release
Branch: master
Hash: 0eba78d40096720f7a637a9a73c382a08b820bca
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)

```

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Windows 10 **
* **Platform:** HP laptop
* **Updated:** 12/29/2021

# Discussion from Mantis ticket

### Comment by Kunda1 2021-01-31 12:07
Forum thread?

---

### Comment by DrC 2021-02-05 05:37
Sorry - there was no thread to attach this to.  I had a bug mid-job and needed to get it down while I could still remember how it happened.

I probably shouldn't even be here because I'm not a developer and not a professional bug fixer (any more) but merely trying to use FreeCad.  Trouble is I feel an obligation to tell you about as bug when I see it even when (as it always will be) it's mid job and I'm doing something new.

A section headed 'report all bugs here' in the forum might help me - but would it help you?

I really need it to be a one step process unless you can't replicate it.

---

### Comment by DrC 2021-02-05 06:29
https://forum.freecadweb.org/viewtopic.php?f=3&t=5236&p=474546#p474546

---

### Comment by chennes 2021-02-07 03:25
I can reproduce in:
OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23935 (Git)
Build type: Debug
Branch: master
Hash: d5b68febbb4989b290b9af36bb2cb21d61a87a2e
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

It is not limited to polygons, or to double-clicks on the construction line. I can achieve the same error state with all shapes I tried as long as they began at one end of those arcs. I can't replicate it on a new sketch with an arbitrary arc, however.

---

### Comment by DrC 2021-02-07 12:08
Thanks for looking at this.  Apologies for the stress-generated errors and omissions in my description of the process.  I really appreciate the effort you must have put in to work out what I meant.

DrC

---

### Comment by @chennes 2021-08-26 17:32
I revisited this today -- setting aside the tangent behavior (which hasn't changed), I think the current double-click behavior is correct. When I "accidentally" double-click, FreeCAD refuses to create the second (identical) point. I have no problems deleting the line segment I did create, and no longer get the "Selection not restricted to one sketch and its subelements" error. This is with:

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.25552 +1 (Git)
Build type: Debug
Branch: hiddenPrefToLockToolbars
Hash: c1f7407b255d7e4a5e63e37f69b5c0190519f95e
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

(Pay no attention to the branch, it's just what I had handy)

---

### Comment by @chennes 2021-12-29 04:02
DrC I believe this has been resolved and plan on closing out this bug -- can you re-test in a recent development build to confirm?

**Comment by luzpaz** [comment]
Should we close this ticket then?
