### ISSUE TITLE
Crash after starting new file (RPI4)

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#6171]
Issue imported from https://tracker.freecad.org/view.php?id=4587

* **Reporter:** PainTER4711
* **Date submitted:** 3/5/2021
* **FreeCAD version:** 0.19
* **Category:** Bug
* **Status:** new
* **Tags:** #pending-forum, 0.19, appimage

# Original report text

When i try to start a new drawing and use the Field "new", Freecad crashes.

# Additional information

A crash after trying to create a new file: 

```$ ./FreeCAD_0.19-24267-Linux-Conda_glibc2.12-x86_64.AppImage 
FreeCAD 0.19, Libs: 0.19R24267 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2021
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f40025b3210]
#1  /lib/x86_64-linux-gnu/libdrm_nouveau.so.2(+0x4c0c) [0x7f3ffcc85c0c]
#2  /lib/x86_64-linux-gnu/libdrm_nouveau.so.2(+0x5291) [0x7f3ffcc86291]
#3  /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xa7ff43) [0x7f3ff7323f43]
#4  /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0xa8003b) [0x7f3ff732403b]
#5  /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x9ca3c8) [0x7f3ff726e3c8]
#6  /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so(+0x15bc79) [0x7f3ff69ffc79]
#7  0x7f4002fc2a91 in QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, bool) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Gui.so.5+0x46f
#8  /tmp/.mount_FreeCAR4zAIv/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x54ca4) [0x7f3ffe56dca4]
#9  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5(+0x17ccec) [0x7f40032dccec]
#10  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5(+0x17de6a) [0x7f40032dde6a]
#11  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5(+0x17ed2b) [0x7f40032ded2b]
#12  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5(+0x17efaf) [0x7f40032defaf]
#13  0x7f40032efdd4 in QWidgetPrivate::syncBackingStore() from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0x66
#14  0x7f40032ffcd9 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0x91f
#15  0x7f40033aa34f in QMainWindow::event(QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0xdd
#16  0x7f40051cafcc in Gui::MainWindow::event(QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libFreeCADGui.so+0x7c
#17  0x7f40032d47f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#18  0x7f40032da31d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#19  0x7f4004dbf169 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libFreeCADGui.so+0x89
#20  0x7f4002aae606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x86
#21  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5(+0x17f695) [0x7f40032df695]
#22  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5(+0x17fd53) [0x7f40032dfd53]
#23  0x7f40033013a3 in void QWidgetPrivate::repaint<QRect>(QRect) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0x7d
#24  0x7f40032f3270 in QWidget::repaint() from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0x24
#25  0x7f40033d0df3 in QProgressBar::setValue(int) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0xe5
#26  /tmp/.mount_FreeCAR4zAIv/usr/lib/WebGui.so(+0x2639c) [0x7f3f684d839c]
#27  0x7f4002ac4a18 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x6c0
#28  0x7f3fd2ac4cdd in QWebEngineView::loadProgress(int) from /tmp/.mount_FreeCAR4zAIv/usr/plugins/designer/../../lib/libQt5WebEngineWidgets.so.5+0x31
#29  0x7f4002ac494d in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x5f5
#30  0x7f3fd2abc181 in QWebEnginePage::loadProgress(int) from /tmp/.mount_FreeCAR4zAIv/usr/plugins/designer/../../lib/libQt5WebEngineWidgets.so.5+0x31
#31  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5(+0x1ca9ba) [0x7f4002acb9ba]
#32  0x7f4002ac3533 in QObject::event(QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x5b
#33  0x7f40032d47f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#34  0x7f40032da31d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#35  0x7f4004dbf169 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libFreeCADGui.so+0x89
#36  0x7f4002aae606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x86
#37  0x7f4002adc8a4 in QTimerInfoList::activateTimers() from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x24c
#38  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5(+0x1dbf54) [0x7f4002adcf54]
#39  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f3fff9fb98d]
#40  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/./libglib-2.0.so.0(+0x54c21) [0x7f3fff9fbc21]
#41  /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f3fff9fbcc1]
#42  0x7f4002add0e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x5e
#43  0x7f4002aab019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0x187
#44  0x7f4002aaee8f in QCoreApplication::exec() from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libQt5Core.so.5+0xfd
#45  0x7f4004d356b1 in Gui::Application::runApplication() from /tmp/.mount_FreeCAR4zAIv/usr/bin/../lib/libFreeCADGui.so+0x1631
#46  /tmp/.mount_FreeCAR4zAIv/usr/bin/freecad(+0x37cd) [0x55af7532c7cd]
#47  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f40025940b3]
#48  /tmp/.mount_FreeCAR4zAIv/usr/bin/freecad(+0x4559) [0x55af7532d559]
```

# Steps to reproduce

Start Freecad
Click "New ..."

![image](https://user-images.githubusercontent.com/4140247/157747956-7ad3aeb9-2cdf-4145-bc85-1eca19e0d4e8.png)

# FreeCAD Info

```
OS: Ubuntu 20.04.2 LTS (MATE/mate)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24267 (Git) AppImage
Build type: Release
Branch: master
Hash: b2ca86d8d72b636011a73394bf9bcdedb3b109b7
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: German/Germany (de_DE)

```

# Other bug information

* **Priority:** normal
* **Severity:** crash
* **Category:** Bug
* **OS: Ubuntu 20.10 20.1**
* **Platform:** PC
* **Updated:** 3/7/2021

# Discussion from Mantis ticket

### Comment by chennes 2021-03-05 18:20
Have you posted about this in the forums? Based on the location of the crash (inside libdrm_noeveau) this has the smell of a graphics card driver problem. What card and driver are you using?

---

### Comment by PainTER4711 2021-03-07 09:12
Hi, 
No, i didn't post in the Forum. Somehow i overlooked the first point - sorry. 
I was confused because the 0.18 is working fine.

Should i do this instead or additional to this issue? 

```
$ lspci -nnk | grep "VGA\|'Kern'\|3D\|Display" -A2
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM206 [GeForce GTX 960] [10de:1401] (rev a1)
	Subsystem: ASUSTeK Computer Inc. GM206 [GeForce GTX 960] [1043:8528]
	Kernel driver in use: nouveau
```
Thank you, 
Stephan

---

### Comment by chennes 2021-03-07 17:18
It looks like there is at least one other person experiencing this, why don't you add your info to this forum discussion:
https://forum.freecadweb.org/viewtopic.php?f=4&t=56394

If we can find out what you have in common that will give devs a chance to debug.

**Comment by luzpaz** [comment]
Closing as this seems like a screencard hardware issue.
