### ISSUE TITLE
[Bug] testSchemeTranslation fails on aarch64

### ISSUE THREAD

**Issue by ggardet** [FreeCAD/FreeCAD#6334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

Not sure in which category of the forum to open a new thread

### Version

0.19 (Release)

### Full version info

```shell
0.19.3 from openSUSE Tumbleweed aarch64
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

While running UnitTest on aarch64, I get the following error:
```
[  393s] Running: UnitTests
[  393s] ....E....
[  393s] ======================================================================
[  393s] ERROR: testSchemeTranslation (UnitTests.UnitBasicCases)
[  393s] ----------------------------------------------------------------------
[  393s] Traceback (most recent call last):
[  393s]   File "/usr/lib64/FreeCAD/Mod/Test/UnitTests.py", line 126, in testSchemeTranslation
[  393s]     q2 = FreeCAD.Units.Quantity(t[0])
[  393s] ValueError: syntax error
[  393s] 
[  393s] During handling of the above exception, another exception occurred:
[  393s] 
[  393s] Traceback (most recent call last):
[  393s]   File "/usr/lib64/FreeCAD/Mod/Test/UnitTests.py", line 131, in testSchemeTranslation
[  393s]     print (u" ".join(e).encode("utf-8").strip())
[  393s] TypeError: can only join an iterable
[  393s] 
[  393s] ----------------------------------------------------------------------
[  393s] Ran 9 tests in 0.082s
[  393s] 
[  393s] FAILED (errors=1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by donovaly** [comment]
Please first open a forum thread (you can always use the general Help forum).

When people there agree there is a bug, the issue can be reopened.
