### ISSUE TITLE
Estimate WB installation issues

### ISSUE THREAD

**Issue by g3grau** [FreeCAD/FreeCAD#8450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: openSUSE Tumbleweed (XFCE//usr/share/xsessions/xfce)
Word size of FreeCAD: 64-bit
Version: 0.21.0.31812 (Git) AppImage
Build type: Release
Branch: master
Hash: c074fe1c95e5aa4f21a11d1387c2ae38f5014a4d
Python 3.10.9, Qt 5.15.6, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Silk 1.0.0
  * sheetmetal 0.2.61
  * kicadStepUpMod 10.17.1
  * CfdOF 1.21.4
  * Assembly4 0.12.5
  * fasteners 0.4.54
  * offline-documentation 1.0.0-alpha
  * MeshRemodel 1.8919.0
  * LCInterlocking
  * 3D_Printing_Tools
  * A2plus 0.4.60i
  * 3DfindIT 1.2.0
  * EM
  * ExplodedAssembly
  * ThreadProfile 1.84.0
  * Estimate 0.1.2
  * workfeature
  * Lithophane
  * Manipulator 1.5.0
  * lattice2 1.0.0
  * Defeaturing 1.2.0
  * Assembly3 0.11.4
  * freecad.gears 1.0.0
  * CurvedShapes 1.0.4
  * Curves 0.6.6
  * frame 0.1.0
  * FEM_FrontISTR 0.1.0
  * fcgear 1.0.0
  * Pyramids-and-Polyhedrons
  * OpticsWorkbench 1.0.9
  * CommandPanel
[/code]
```

### Subproject(s) affected?

Other (specify in description)

### Issue description

Installation of estimateWB initially causes log messages:

```
Cannot find icon: /home/ggrau/.cache/FreeCAD/Cache/AddonManager/MacroIcons/120px-FCBmpImportScreenshot.png
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Failed to read metadata from /home/ggrau/.local/share/FreeCAD/Mod/frame/package.xml
QXcbConnection: XCB error: 3 (BadWindow), sequence: 4677, resource id: 6030220, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 4740, resource id: 5842330, major code: 40 (TranslateCoords), minor code: 0
Release of profile requested but WebEnginePage still not deleted. Expect troubles !
Release of profile requested but WebEnginePage still not deleted. Expect troubles !

```

The missing icon exists in the Macro folder, the message can thus be removed by copying it to the mentioned Cache folder. Upon the next start I get a longer error related to unicode:

During initialization the error "'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)" occurred in freecad.estimateWB
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ggrau/.local/share/FreeCAD/Mod/Estimate/./freecad/estimateWB/tools.py", line 99, in __init__
    self.language = json.loads(jsonfile.read().replace('\n', ''))
  File "/tmp/.mount_FreeCApV7X85/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<string>", line 226, in InitApplications
  File "/tmp/.mount_FreeCApV7X85/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ggrau/.local/share/FreeCAD/Mod/Estimate/./freecad/estimateWB/init_gui.py", line 4, in <module>
    from . import ICONPATH, tools
  File "/tmp/.mount_FreeCApV7X85/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/ggrau/.local/share/FreeCAD/Mod/Estimate/./freecad/estimateWB/tools.py", line 105, in <module>
    LANG=language()
  File "/home/ggrau/.local/share/FreeCAD/Mod/Estimate/./freecad/estimateWB/tools.py", line 102, in __init__
    self.language = json.loads(jsonfile.read().replace('\n', ''))
  File "/tmp/.mount_FreeCApV7X85/usr/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 246: ordinal not in range(128)
--------------------------------------------------------------------------------

```

As a consequence, Estimate WB does not appear in the WB list. Deinstallation works.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Should be closed and an issue opened in https://github.com/erroronline1/estimateWB
