### ISSUE TITLE
Freecad SIGSEGV, Segmentation fault when edit face on cube 

### ISSUE THREAD

**Issue by navr32** [FreeCAD/FreeCAD#8839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
Version freecad-git 0.21.0.32249.gda98cfc4d1-1 manjaro package.

[code]
OS: Manjaro Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.0.32249 (Git)
Build type: None
Branch: master
Hash: da98cfc4d1dab6e5f0f0fc6ca1f4f39cfdf1d729
Python 3.10.9, Qt 5.15.8, Coin 4.0.1, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * sheetmetal 0.2.49
  * Plot 2022.4.17
  * FeedsAndSpeeds 0.4.0
  * LCInterlocking
  * fasteners 0.3.46
  * GDML 1.8.0
  * BCFPlugin 1.0.0
  * EM
  * BIM 2021.12.0
  * parts_library
  * workfeature
  * Curves 0.5.0
  * Design456 0.0.1
  * Trails 2022.1.0
  * POV-Ray-Rendering
  * kicadStepUpMod 10.13.2
  * CurvedShapes 1.0.3
  * Pyramids-and-Polyhedrons
  * fcgear 1.0.0
  * 3D_Printing_Tools
  * InventorLoader 1.3.0
  * 3DfindIT 1.2.0
  * Render 2022.2.0
  * BOLTSFC
  * Reinforcement
  * CubeMenu
  * OpticsWorkbench 1.0.8
  * Manipulator 1.4.5
  * lattice2 1.0.0
  * Glass
  * FEM_FrontISTR 0.1.0
  * WebTools
  * Beltrami 1.0.6-alpha
  * ThreadProfile 1.81.0
  * pyrate
[/code]
```

### Subproject(s) affected?

PartDesign

### Issue description

When i try to edit a second face a cube create from extrude from a sketch.

Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x38f50) [0x7f6f3e086f50]
#1  0x7f6ee64f3e17 in Part::Geometry::hasExtension(Base::Type const&) const from /usr/lib/freecad/lib/Part.so+0x57
#2  0x7f6ebe7a0ead in auto getSafeGeomLayerId<Part::Geometry const*>(Part::Geometry const*) from /usr/lib/freecad/lib/SketcherGui.so+0x3d
#3  0x7f6ebe79e051 in SketcherGui::ElementItemDelegate::paint(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const from /usr/lib/freecad/lib/SketcherGui.so+0x81
#4  0x7f6f3f4372a5 in QListView::paintEvent(QPaintEvent*) from /usr/lib/libQt5Widgets.so.5+0x3f5
#5  0x7f6f3f1ca514 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x7a4
#6  0x7f6f3f278a23 in QFrame::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x23
#7  0x7f6f3e71abb2 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x92
#8  0x7f6f3f193b4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x8c
#9  0x7f6f40a091a9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#10  0x7f6f3e71af48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#11  0x7f6f3f1be3eb in QWidgetPrivate::sendPaintEvent(QRegion const&) from /usr/lib/libQt5Widgets.so.5+0x3b
#12  0x7f6f3f1bf7b6 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0xdb6
#13  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#14  0x7f6f3f1c005c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x31c
#15  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#16  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#17  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#18  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#19  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#20  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#21  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#22  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#23  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#24  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#25  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#26  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#27  0x7f6f3f1c005c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x31c
#28  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#29  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#30  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#31  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#32  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#33  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#34  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#35  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#36  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#37  0x7f6f3f1c01fe in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x4be
#38  0x7f6f3f1c005c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x31c
#39  0x7f6f3f1c005c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x31c
#40  0x7f6f3f1bec8e in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) from /usr/lib/libQt5Widgets.so.5+0x28e
#41  /usr/lib/libQt5Widgets.so.5(+0x184aa5) [0x7f6f3f19faa5]
#42  0x7f6f3f1ca1e4 in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x474
#43  0x7f6f3f193b5c in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x9c
#44  0x7f6f40a091a9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x99
#45  0x7f6f3e71af48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x128
#46  0x7f6f3e71ba53 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /usr/lib/libQt5Core.so.5+0x193
#47  /usr/lib/libQt5Core.so.5(+0x2d4e88) [0x7f6f3e761e88]
#48  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x19b) [0x7f6f3c55582b]
#49  /usr/lib/libglib-2.0.so.0(+0xaccc9) [0x7f6f3c5accc9]
#50  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x7f6f3c5540e2]
#51  0x7f6f3e765c6c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x6c
#52  0x7f6f3e7136ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x12c
#53  0x7f6f3e71e219 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x99
#54  0x7f6f4093c232 in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x1e92
#55  /usr/bin/FreeCAD(+0x85b9) [0x55d6451ff5b9]
#56  /usr/lib/libc.so.6(+0x23790) [0x7f6f3e071790]
#57  /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f6f3e07184a]
#58  /usr/bin/FreeCAD(+0x8905) [0x55d6451ff905]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Please put output in code tags especially if there are is #<number> which will spam unrelated tickets. I've edited your ticket to reflect the change. TIA

**Comment by luzpaz** [comment]
Please provide an example file for testers to quickly reproduce the bug. Also provide a clear step-by-step. TIA!

**Comment by luzpaz** [comment]
@navr32 ping

**Comment by luzpaz** [comment]
@navr32 please respond

**Comment by adrianinsaval** [comment]
I suggest closing, this stinks of an AUR package that was not recompiled after a system upgrade.

The description is too vague to even attempt to reproduce and no example file is provided, if OP is sure his installation is actually working and can provide clear reproduction steps as well as a file, then they can reopen the issue.

**Comment by adrianinsaval** [comment]
Please close the issue then, like I said this was most likely just a case of not rebuilding the AUR package after dependencies where updated.

**Comment by luzpaz** [comment]
Closing
