### ISSUE TITLE
[Problem] Path Inspect tool is broken

### ISSUE THREAD

**Issue by sliptonic** [FreeCAD/FreeCAD#9485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Linux Mint 20 (i3/i3)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33085 (Git)
Build type: Unknown
Branch: fmaster
Hash: b4834dc580e17cca2ead1388854739b0f093a82f
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/United States (en_US)
Installed mods: 
  * DynamicData 2.46.0
  * Assembly4 0.12.5
  * fasteners 0.4.55
  * Behave-Dark-Colors 0.1.1
  * 3DfindIT 1.2.0
  * Render 2023.2.2
  * ProDarkThemePreferencePack 1.0.0
  * sheetmetal 0.2.59
  * QuickMeasure 2022.10.28
  * Nodes 0.1.36
  * FeedsAndSpeeds 0.5.0
  * Assembly3 0.11.4
  * ExtremeProDark 2.6.4
  * FeedsAndSpeeds.bak
  * Curves 0.6.5
  * A2plus 0.4.60k
  * Dracula 0.0.2
[/code]
```

### Subproject(s) affected?

Path

### Problem description

The inspect tool is now broken.  Attempting to use it shows the following error in the console.

Select an operation with a toolpath and launch the Path_Inspect tool.  Then scrub through the command list.
The following error is shown in the console
```
09:20:35  Traceback (most recent call last):
09:20:35    File "/home/brad/FCD/FC/Mod/Path/Path/Main/Gui/Inspect.py", line 186, in highlightpath
09:20:35      commands = PathUtils.getPathWithPlacement(self.PathObj).Commands
09:20:35  NameError: name 'PathUtils' is not defined
```

This is fixed by adding an import to the file

```
import PathScripts.PathUtils as PathUtils
```

Then the console shows this error
```
09:00:27  Traceback (most recent call last):
09:00:27    File "/home/brad/FCD/FC/Mod/Path/Path/Main/Gui/Inspect.py", line 186, in highlightpath
09:00:27      commands = PathUtils.getPathWithPlacement(self.PathObj).Commands
09:00:27    File "/home/brad/FCD/FC/Mod/Path/PathScripts/PathUtils.py", line 849, in getPathWithPlacement
09:00:27      return pathobj.Path
09:00:27  AttributeError: 'Path.Toolpath' object has no attribute 'Path'
```

### Anything else?

This is a regression caused by merging of PR #8459 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cam72cam** [comment]
Looks like I was confused by the following code:
```
def __init__(self, PathObj, parent=FreeCADGui.getMainWindow()):
        self.PathObj = PathObj.Path
```

Simple fix, should have a PR soon
