### ISSUE TITLE
[Problem] Freecad crash when filletting a border in part design of a fused/unioned body

### ISSUE THREAD

**Issue by amreo** [FreeCAD/FreeCAD#9931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: KDE Flatpak runtime (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: (HEAD detached at 0.20.2)
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.6, Qt 5.15.9, Coin 4.0.0, Vtk 8.2.0, OCC 7.6.3
Locale: Italian/Italy (it_IT)
Installed mods: 
  * fasteners 0.4.56
  * 3DfindIT 1.2.0
  * freecad.gears 1.0.0
  * LCInterlocking
  * ModernUI (Disabled)
  * boltsfc 2022.11.5
  * sheetmetal 0.2.63
  * parts_library
[/code]
```

### Subproject(s) affected?

PartDesign

### Problem description

The problem is that freecad crash when I try to fillet a border in this project [gettone-nd.zip](https://github.com/FreeCAD/FreeCAD/files/12061062/gettone-nd.zip)

Steps to reproduce:

1.  Open the provided file [gettone-nd.zip](https://github.com/FreeCAD/FreeCAD/files/12061062/gettone-nd.zip)
2. Go to part design workbench and active **Body002**
3. Select gettone_nd.Body002.Boolean.Edge26 ![bug-freecad-edge](https://github.com/FreeCAD/FreeCAD/assets/12671924/f9c6282b-38bb-44dc-bee4-76e82a079907)
4. Click to "fillet" 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grubertechnic** [comment]
stacktrace

```
Err: Program received signal SIGSEGV, Segmentation fault.
Err: #0  /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7f66234add60]
Err: #1  0x7f64ebd2c95b in ChFi3d_Builder::PerformIntersectionAtEnd(int) from /usr/local/lib/libTKFillet.so.7.7+0x5ecb
Err: #2  0x7f64ebcd69ba in ChFi3d_Builder::PerformFilletOnVertex(int) from /usr/local/lib/libTKFillet.so.7.7+0x3ea
Err: #3  0x7f64ebcd756e in ChFi3d_Builder::Compute() from /usr/local/lib/libTKFillet.so.7.7+0xa7e
Err: #4  0x7f64ebe58e0d in BRepFilletAPI_MakeFillet::Build(Message_ProgressRange const&) from /usr/local/lib/libTKFillet.so.7.7+0x1d
Err: #5  0x7f64e87e12d7 in PartDesign::Fillet::execute() from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/_PartDesign.so+0x757
Err: #6  0x7f66255b017a in App::DocumentObject::recompute() from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0xba
Err: #7  0x7f64ece90369 in Part::Feature::recompute() from /home/user/Programs/FreeCADmaster/build/Mod/Part/Part.so+0x9
Err: #8  0x7f662555d3ed in App::Document::_recomputeFeature(App::DocumentObject*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x29d
Err: #9  0x7f66255648ae in App::Document::recompute(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, bool, bool*, int) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x56e
Err: #10  0x7f6625611fa5 in App::DocumentPy::recompute(_object*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x2d5
Err: #11  0x7f6625612154 in App::DocumentPy::staticCallback_recompute(_object*, _object*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADApp.so+0x24
Err: #12  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x10cc74) [0x7f6624c0ec74]
Err: #13  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x90) [0x7f6624bc8a50]
Err: #14  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x8632) [0x7f6624b7a2f2]
Err: #15  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x1a4ddc) [0x7f6624ca6ddc]
Err: #16  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x4e) [0x7f6624ca712e]
Err: #17  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3e) [0x7f6624ca717e]
Err: #18  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(PyEval_EvalCode+0x1b) [0x7f6624ca272b]
Err: #19  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x1e9735) [0x7f6624ceb735]
Err: #20  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(PyRun_StringFlags+0x93) [0x7f6624cec013]
Err: #21  0x7f66251f0718 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADBase.so+0x58
Err: #22  0x7f6625f097ef in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x7f
Err: #23  0x7f6625f0994f in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0xcf
Err: #24  0x7f6625f09a53 in Gui::Command::updateActive() from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x33
Err: #25  0x7f64e8184285 in finishFeature(Gui::Command const*, App::DocumentObject*, App::DocumentObject*, bool, bool) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0x2c5
Err: #26  0x7f64e8185d32 in finishDressupFeature(Gui::Command const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Part::Feature*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0x6c2
Err: #27  0x7f64e819279d in makeChamferOrFillet(Gui::Command*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0xbd
Err: #28  0x7f64e819296c in CmdPartDesignFillet::activated(int) from /home/user/Programs/FreeCADmaster/build/Mod/PartDesign/PartDesignGui.so+0x3c
Err: #29  0x7f6625f0d42b in Gui::Command::_invoke(int, bool) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x1fb
Err: #30  0x7f6625f0d7de in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0xfe
Err: #31  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e45a6) [0x7f6623b145a6]
Err: #32  0x7f6624599b62 in QAction::triggered(bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x42
Err: #33  0x7f662459c3a1 in QAction::activate(QAction::ActionEvent) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xe1
Err: #34  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2521b2) [0x7f662468f1b2]
Err: #35  0x7f662468f2d1 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xf1
Err: #36  0x7f662477e9ca in QToolButton::mouseReleaseEvent(QMouseEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xa
Err: #37  0x7f66245dffae in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1ce
Err: #38  0x7f66245a015f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7f
Err: #39  0x7f66245a704b in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x49b
Err: #40  0x7f6625ed0618 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x68
Err: #41  0x7f6623addfca in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12a
Err: #42  0x7f66245a6076 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1d6
Err: #43  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bb011) [0x7f66245f8011]
Err: #44  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1be33e) [0x7f66245fb33e]
Err: #45  0x7f66245a015f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7f
Err: #46  0x7f6625ed0618 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x68
Err: #47  0x7f6623addfca in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12a
Err: #48  0x7f6623eb8583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x653
Err: #49  0x7f6623e8e64c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0xac
Err: #50  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x697da) [0x7f661ddc37da]
Err: #51  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x25b) [0x7f662187ae6b]
Err: #52  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52118) [0x7f662187b118]
Err: #53  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2f) [0x7f662187b1cf]
Err: #54  0x7f6623b3551f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x5f
Err: #55  0x7f6623adc98b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
Err: #56  0x7f6623ae4c00 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x90
Err: #57  0x7f6625e39148 in Gui::Application::runApplication() from /home/user/Programs/FreeCADmaster/build/lib/libFreeCADGui.so+0x2498
Err: #58  /home/user/Programs/FreeCADmaster/build/bin/FreeCAD(+0x98ac) [0x5628650d28ac]
Err: #59  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f6623498d0a]
Err: #60  /home/user/Programs/FreeCADmaster/build/bin/FreeCAD(+0x9b5a) [0x5628650d2b5a]
```

Duplicate from #8179
